import type Game from '../game';
import { HitFlashPipeline } from './pipelines/hit-flash-pipeline';
import { ElementGlowPipeline } from './pipelines/element-glow-pipeline';

export type AnimState =
  | 'idle' | 'run' | 'hurt' | 'die'
  | 'attack-01' | 'attack-02' | 'attack-03' | 'attack-04' | 'attack-05'
  | 'attack-06' | 'attack-07' | 'attack-08' | 'attack-09' | 'attack-10';

// Which states are direction-aware (0=N, 1=E, 2=S, 3=W)
const DIRECTIONAL = new Set<AnimState>([
  'idle', 'run',
  'attack-01', 'attack-02', 'attack-03', 'attack-04', 'attack-05',
  'attack-06', 'attack-07', 'attack-08', 'attack-09', 'attack-10',
]);

const ANIM_CFG: Record<AnimState, { frames: number; fps: number; repeat: number }> = {
  'idle':      { frames: 8,  fps: 8,  repeat: -1 },
  'run':       { frames: 8,  fps: 10, repeat: -1 },
  'hurt':      { frames: 4,  fps: 8,  repeat: 0  },
  'die':       { frames: 10, fps: 8,  repeat: 0  },
  'attack-01': { frames: 6,  fps: 10, repeat: 0  },
  'attack-02': { frames: 6,  fps: 10, repeat: 0  },
  'attack-03': { frames: 6,  fps: 10, repeat: 0  },
  'attack-04': { frames: 6,  fps: 10, repeat: 0  },
  'attack-05': { frames: 6,  fps: 10, repeat: 0  },
  'attack-06': { frames: 6,  fps: 10, repeat: 0  },
  'attack-07': { frames: 6,  fps: 10, repeat: 0  },
  'attack-08': { frames: 6,  fps: 10, repeat: 0  },
  'attack-09': { frames: 6,  fps: 10, repeat: 0  },
  'attack-10': { frames: 6,  fps: 10, repeat: 0  },
};

// Texture key: char-{id}-{state}-{dir} (directional) or char-{id}-{state} (non-dir)
// Spritesheet format: 128×192 px frames, horizontal strip
// Generated by meshyanim/anim pipeline — falls back to circle when absent
function texKey(charId: number, state: AnimState, dir: 0 | 1 | 2 | 3): string {
  return DIRECTIONAL.has(state)
    ? `char-${charId}-${state}-${dir}`
    : `char-${charId}-${state}`;
}

export class CharSprite {
  private scene: Game;
  private charId: number;
  private dir: 0 | 1 | 2 | 3 = 2; // South = default camera-facing direction
  private state: AnimState = 'idle';

  private sprite: Phaser.GameObjects.Sprite | null = null;
  private gfx: Phaser.GameObjects.Graphics | null = null;

  /** True when spritesheets are loaded; false = circle fallback active */
  readonly hasSpritesheet: boolean;

  constructor(
    scene: Game,
    charId: number,
    elemColor: number,
    teamColor: number,
  ) {
    this.scene = scene;
    this.charId = charId;

    // Probe for south-facing idle as proxy for "spritesheets baked"
    this.hasSpritesheet = scene.textures.exists(texKey(charId, 'idle', 2));

    if (this.hasSpritesheet) {
      this._registerAnims();
      this.sprite = scene.add
        .sprite(0, 0, texKey(charId, 'idle', 2))
        .setScrollFactor(1)
        .setScale(0.5); // 128 px frames → 64 px on screen
      this._applyPipelines(elemColor);
      this.play('idle');
    } else {
      // Circle fallback — same visual as the original CombatUnit body
      this.gfx = scene.add.graphics().setScrollFactor(1);
      this.gfx.fillStyle(elemColor, 1);
      this.gfx.fillCircle(0, 0, 13);
      this.gfx.lineStyle(3, teamColor, 1);
      this.gfx.strokeCircle(0, 0, 13);
    }
  }

  private _registerAnims() {
    const states = Object.keys(ANIM_CFG) as AnimState[];
    for (const s of states) {
      const dirs: Array<0 | 1 | 2 | 3> = DIRECTIONAL.has(s) ? [0, 1, 2, 3] : [0];
      for (const d of dirs) {
        const key = texKey(this.charId, s, d);
        if (this.scene.anims.exists(key)) continue;
        if (!this.scene.textures.exists(key)) continue;
        const { frames, fps, repeat } = ANIM_CFG[s];
        this.scene.anims.create({
          key,
          frames: this.scene.anims.generateFrameNumbers(key, { start: 0, end: frames - 1 }),
          frameRate: fps,
          repeat,
        });
      }
    }
  }

  /**
   * Play an animation state. For directional states uses the current facing.
   * `onComplete` fires once at the end of non-looping states.
   */
  play(state: AnimState, onComplete?: () => void): this {
    this.state = state;
    if (!this.sprite) return this;

    const key = texKey(this.charId, state, DIRECTIONAL.has(state) ? this.dir : 0);
    if (!this.scene.anims.exists(key)) return this;

    this.sprite.play(key, true /* ignoreIfPlaying = false so direction changes work */);
    if (onComplete) {
      this.sprite.once(Phaser.Animations.Events.ANIMATION_COMPLETE, onComplete);
    }
    return this;
  }

  /** Change facing and immediately re-play the current directional anim if running */
  setDirection(dir: 0 | 1 | 2 | 3): this {
    if (this.dir === dir) return this;
    this.dir = dir;
    if (this.sprite && DIRECTIONAL.has(this.state)) this.play(this.state);
    return this;
  }

  setPosition(x: number, y: number): this {
    this.sprite?.setPosition(x, y);
    this.gfx?.setPosition(x, y);
    return this;
  }

  setDepth(depth: number): this {
    this.sprite?.setDepth(depth);
    this.gfx?.setDepth(depth);
    return this;
  }

  setAlpha(alpha: number): this {
    this.sprite?.setAlpha(alpha);
    this.gfx?.setAlpha(alpha);
    return this;
  }

  setVisible(visible: boolean): this {
    this.sprite?.setVisible(visible);
    this.gfx?.setVisible(visible);
    return this;
  }

  /** Tint the body (element glow, hit flash, etc.) */
  setTint(color: number): this {
    this.sprite?.setTint(color);
    // Graphics can't be tinted — fallback ignores this
    return this;
  }

  clearTint(): this {
    this.sprite?.clearTint();
    return this;
  }

  /**
   * Flash white (or element color) on hit.
   * Sprite mode: drives HitFlashPipeline uniform.
   * Circle mode: quick alpha dip.
   */
  flash(duration = 260): void {
    if (this.sprite) {
      const pipe = this.sprite.getPostPipeline(HitFlashPipeline) as HitFlashPipeline | undefined;
      if (pipe) {
        pipe.flashAmount = 1;
        const prog = { v: 1 };
        this.scene.tweens.add({
          targets: prog,
          v: 0,
          duration,
          ease: 'Power2',
          onUpdate: () => { pipe.flashAmount = prog.v; },
        });
      }
    } else if (this.gfx) {
      // Circle fallback: dim → restore
      this.gfx.setAlpha(0.15);
      this.scene.tweens.add({
        targets: this.gfx,
        alpha: 1,
        duration: duration * 0.8,
        ease: 'Power2',
      });
    }
  }

  /** Enable / update element glow. Pass amount=0 to disable. */
  setGlow(elemColor: number, amount = 0.28): void {
    if (!this.sprite) return;
    const pipe = this.sprite.getPostPipeline(ElementGlowPipeline) as ElementGlowPipeline | undefined;
    if (!pipe) return;
    pipe.setElementColor(elemColor);
    pipe.glowAmount = amount;
  }

  private _applyPipelines(elemColor: number): void {
    if (!this.sprite) return;
    try {
      this.sprite.setPostPipeline([HitFlashPipeline, ElementGlowPipeline]);
      this.setGlow(elemColor, 0.28);
    } catch (_) {
      // Canvas renderer — pipelines not supported, silently skip
    }
  }

  destroy(): void {
    this.sprite?.destroy();
    this.gfx?.destroy();
  }
}

/**
 * Build the texture key for preloading a character spritesheet.
 * Call from game.ts preload() once the asset path is known:
 *   scene.load.spritesheet(
 *     charSpriteTexKey(id, 'idle', 2),
 *     `/characters/${folder}/idle-2.png`,
 *     { frameWidth: 128, frameHeight: 192 }
 *   );
 */
export function charSpriteTexKey(
  charId: number,
  state: AnimState,
  dir: 0 | 1 | 2 | 3,
): string {
  return texKey(charId, state, dir);
}
