import os

BASE = "src/data/characters"

def char_file(id, nom, element, classe, espece, region, faction, phys, perso, lore, combat, modifs):
    return (
        f"import {{ ELEMENT_KITS }} from '../../../character-kits';\n"
        f"import type {{ Personnage }} from '../../../character-types';\n\n"
        f"const character: Personnage = {{\n"
        f"  id: {id},\n"
        f"  nom: `{nom}`,\n"
        f"  element: '{element}',\n"
        f"  classe: '{classe}',\n"
        f"  espece: '{espece}',\n"
        f"  region: '{region}',\n"
        f"  faction: '{faction}',\n"
        f"  description_physique: `{phys}`,\n"
        f"  description_personnalite: `{perso}`,\n"
        f"  position_lore: `{lore}`,\n"
        f"  style_combat: `{combat}`,\n"
        f"  kit: ELEMENT_KITS['{element}'],\n"
        f"  modifications_classe: `{modifs}`,\n"
        f"}};\n\n"
        f"export default character;\n"
    )

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"OK: {path}")

# ============================================================
# FEE (361-373) — Fees / Citadelle
# Spells: Rayon de Lumiere, Benediction, Barriere de Lumiere, Aura de Soin,
#         Enchantement de Case, Vague Sacree, Sanctuaire, Resurrection Partielle,
#         Purification, ULTIME — Miracle
# Passifs: Benediction Persistante, Lumiere Protectrice
# ============================================================

# 361 - Lumielle already well-written in a previous session, we keep it as-is but let's
# re-write it with the same quality standard we've established
write(f"{BASE}/fee/361-lumielle/index.ts", char_file(
    361, "Lumielle", "Fée", "Enchanteur-Soutien", "Fées", "Citadelle", "Dissidentes",
    "Fee de haute stature dont les ailes translucides refractent la lumiere en arcs-en-ciel permanents, changeant de spectre selon son etat emotionnel — bleues dans la concentration, dorées dans la joie, argent dans la detresse. Ses cheveux blancs flottent en permanence comme sous l'eau, maintenus par le champ de Lumiere qu'elle genere autour d'elle. Sa peau est nacrée avec une lueur douce qui s'intensifie quand elle canalise ses soins. Ses mains laissent trainer des filaments dores qui persistent plusieurs secondes apres ses gestes — les traces visibles des canaux de benediction qu'elle maintient ouverts vers ses allies.",
    "Lumielle est d'une douceur absolue qui dissimule une volonte de fer forgee dans la trahison. Elle etait grande-pretresse de la Citadelle quand l'Empire en a pris le controle — elle a vu des Fees qu'elle connaissait depuis l'enfance integrees de force dans des programmes de captation. Cette experience a transforme sa compassion en engagement militante. Sa douceur n'est pas de la naivete : c'est une decision deliberee de ne pas laisser la violence qu'elle a vue transformer ce qu'elle est.",
    "Ancienne grande-pretresse de la Citadelle, Lumielle est la coordinatrice de soin la plus respectee des Dissidentes dans la region. Son Aura de Soin peut maintenir une ligne de front entiere en etat de combat pendant des heures. Son depart de la Citadelle a ete un signal pour d'autres Fees — plusieurs ont suivi dans les semaines suivantes. Elle est en contact telepathique constant avec Veylith (Psy, Dissidentes) pour coordonner les operations de liberation des Fees capturees.",
    "Lumielle sature d'abord le terrain en Cases Fee via Enchantement de Case sur les positions alliees cles. Aura de Soin couvre toutes ces cases simultanement — soins passifs massifs. Barriere de Lumiere sur les positions les plus exposees. Purification pour annuler les effets de statut adverses. Benediction sur les unites qui entrent dans des zones dangereuses. Resurrection Partielle si une unite tombe. Miracle en dernier recours pour inverser une situation critique.",
    "Aura de Soin de Lumielle affecte toutes les Cases Fee dans un rayon de 5 cases, pas seulement les cases adjacentes. Benediction Persistante dure le double du temps standard. Purification de Lumielle peut etre lancee en reaction (hors tour) quand un allie est affecte par un etat negatif. Passif Lumiere Perpetuelle : les Cases Fee que Lumielle cree ne disparaissent jamais naturellement — elles doivent etre detruites activement."
))

write(f"{BASE}/fee/362-seleniar/index.ts", char_file(
    362, "Séléniar", "Fée", "Enchanteur-Capteur", "Fées", "Citadelle", "Empire",
    "Fee dont la maitrise de la Lumiere Protectrice a ete specialisee dans la detection — ses ailes ont developpe des photodetecteurs biologiques qui captent les variations de lumiere imperceptibles a l'oeil normal, lui permettant de detecter les Elus Fee qui utilisent leur element meme a grande distance. Ses yeux sont d'un argent metallique, reflechissants comme des miroirs, et sa peau emet une lueur rythmique qui correspond aux signatures de lumiere qu'elle detecte. Elle porte l'equipement de Capteur imperial le plus discret — la Lumiere qu'elle emet est modulable, elle peut la reduire a zero pour les operations de surveillance.",
    "Seleniar n'a pas rejoint l'Empire par conviction mais par pragmatisme de survie — quand la Citadelle a ete integree, elle etait en position de vulner abilite et le programme de cooperation imperial lui offrait une protection. Dix ans plus tard, elle est trop profondement integree pour en sortir facilement, et elle le sait. Sa loyaute est de surface ; sa souffrance est reelle et privee.",
    "Agente de detection lumineuse de l'Empire a la Citadelle, Seleniar identifie les Fees qui utilisent clandestinement leur element dans les zones de restriction imperiale. Ses donnees ont permis plusieurs captures. Elle a une relation complexe avec Lumielle — elles se connaissaient avant la prise de la Citadelle. Elle retarde certains rapports. Ce n'est pas de l'heroisme, c'est du procrastination morale.",
    "Seleniar place des relais de detection lumineuse (Benediction en mode surveillance) sur les routes de transit que les Fees des Dissidentes empruntent. Rayon de Lumiere pour identifier et marquer les cibles. Barriere de Lumiere pour bloquer les voies de fuite. Vague Sacree pour revealer les Fees invisibles dans la zone. Sanctuaire imperial pour securiser les points de captation. Purification pour annuler les illusions adverses.",
    "Benediction de Seleniar en mode detection reste active indefiniment et signale toute utilisation de sort Fee dans un rayon de 5 cases. Rayon de Lumiere de Seleniar traverse les Illusions et les Invisibilites — il detecte les entites cachees. Vague Sacree de Seleniar revele toutes les unites Fee cachees dans la zone affectee. Passif Photosensibilite : Seleniar detecte automatiquement tout sort Fee lance dans un rayon de 10 cases, quel que soit son type."
))

write(f"{BASE}/fee/363-auroch-givre/index.ts", char_file(
    363, "Aurix", "Fée", "Juggernaut", "Fées", "Citadelle", "Convergence",
    "Fee dont la physique contredit toutes les intuitions sur son espece — elle est grande, tres massive pour une Fee, avec des ailes qu'elle ne peut pas deployer a pleine envergure dans des espaces interieurs. Sa Barriere de Lumiere s'est progressivement internalisee, renforçant ses tissus biologiques en une densite qui approche celle de la roche. Sa peau est d'un blanc intense qui emet une lumiere constante que ses adversaires trouvent eblouissante a courte distance. Elle marche au sol — ses ailes sont trop lourdes pour un vol maintenu. Son equipement est minimal parce que sa propre physiologie est son armure.",
    "Aurix a rejoint la Convergence parce que l'effort collectif a du sens pour elle — une Fee seule ne peut pas proteger tous les siens, mais une coalition peut. Elle n'a pas de naivete sur la politique de la Convergence, mais elle croit dans le principe. Sa presence rassurante — la lumiere qu'elle emet est involontaire et apaisante — est un actif tactique inattendu pour une Juggernaut.",
    "Front de choc de la Convergence dans les operations de protection de la Citadelle contre les tentatives de reprise totale de l'Empire. Aurix est envoyee pour les assauts qui necessitent une presence Fee sur la ligne de front — ses propres resistances lumineuses la rendent difficile a neutraliser par les sorts qui fonctionnent bien contre les autres types. Son association avec Psykhon (Psy, Convergence) est documentee : deux Juggernaut aux resistances complementaires.",
    "Aurix avance avec Barriere de Lumiere sur elle-meme — sa resistance de base est elevee et la Barriere la pousse au-dela. Vague Sacree en ouverture pour desorganiser la ligne adverse. Enchantement de Case sur les positions qu'elle traverse pour les fortifier pour les allies qui la suivent. Rayon de Lumiere comme tir tendu sur les casters adverses. Aura de Soin passive maintient sa propre sante. Miracle en fermeture si la situation necessite une inversion.",
    "Barriere de Lumiere sur Aurix atteint une reduction de 50% des degats magiques. Vague Sacree de Aurix a un rayon de 5 cases et repousse les ennemis d'1 case. Enchantement de Case qu'Aurix cree en deplacement reste actif 4 tours supplementaires. Passif Lumiere Internalisee : chaque sort Fee lance sur Aurix (allie ou ennemi) la soigne de 10% de ses PV max au lieu de l'affecter normalement — elle absorbe la lumiere comme de la nourriture."
))

write(f"{BASE}/fee/364-ailevif/index.ts", char_file(
    364, "Aelwyn", "Fée", "Plongeur", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la vitesse de vol en pique est la plus haute documentee parmi les Fees de sa generation — ses ailes sont plus longues et effilees que la norme, avec une rigidite aerodynamique qui les rend parfaites pour l'acceleration mais limitees dans les virages serres. Sa silhouette en plongee est celle d'un trait de lumiere — elle laisse un sillage doré visible plusieurs secondes apres son passage. Sa peau est d'un blanc bleuté et ses yeux d'un or intense. Elle porte un equipement de vol minimaliste — juste des stabilisateurs aux chevilles pour les trajectoires precises.",
    "Aelwyn pense en termes de premier contact. Elle arrive avant que l'ennemi realise qu'il est attaque, fait ce qu'elle doit faire, et sort avant que la riposte soit organisee. Les Dissidentes l'utilisent pour les interventions d'urgence sur des situations qui se degradent — elle est la premiere option quand le temps manque.",
    "Operatrice de premiere intervention des Dissidentes a la Citadelle. Aelwyn est deployee pour les situations ou une Fee de contact doit atteindre une position en quelques secondes plutot que quelques minutes. Ses insertions en pique dans les formations imperiales ont interrompu plusieurs operations de captation en cours. Elle coordonne ses sorties avec Lumielle — la Soutien prepare un Sanctuaire de recuperation, Aelwyn plonge et revient.",
    "Aelwyn prend de l'altitude via Enchantement de Case aerienne. Plongee en ligne droite — Rayon de Lumiere en pique amplifie par la vitesse. Impact et Benediction immediate sur la cible pour la neutraliser (paradoxalement, une Benediction ennemie peut la desorienter). Vague Sacree radiale au moment de l'impact. Barriere de Lumiere sur elle-meme pour la retraite. Resurrection Partielle d'un allie en passant si l'occasion se presente. Vol de sortie a vitesse maximale.",
    "La plongee d'Aelwyn depuis Z+2 ou plus inflige automatiquement des degats de choc equivalents a Rayon de Lumiere sur la case d'atterrissage. Rayon de Lumiere lance pendant une plongee inflige 75% de degats supplementaires. Barriere de Lumiere activee apres une plongee est instantanee. Passif Sillage Dore : apres une plongee, Aelwyn laisse un sillage de lumiere Fee sur sa trajectoire — les allies peuvent traverser ce sillage gratuitement (0 PM) pendant 2 tours."
))

write(f"{BASE}/fee/365-theophane/index.ts", char_file(
    365, "Théophane", "Fée", "Mage-Burst", "Fées", "Citadelle", "Indépendant",
    "Fee dont la puissance de Vague Sacree a atteint un niveau qui depasse sa capacite de controle delibere — ses mains emettent une chaleur lumineuse constante qui fait fondre les materiaux sensibles a la chaleur dans un rayon de quelques centimetres. Ses ailes sont partiellement calcifiees par des surchages de Lumiere accumulees, leur donnant une rigidite qui empeche le vol prolonge. Ses yeux sont constamment plisses, comme si une lumiere trop forte les agressait de l'interieur. Elle porte des gants de canali sation de puissance Fee — pas pour amplifier, pour contenir.",
    "Theophane est independante par necessite — elle est trop puissante pour etre integree dans une formation standard sans risques. Elle a desintegre involontairement l'equipement de deux brigades consecutives pendant des entrainements. Elle gere sa puissance par une discipline mentale constante et accepte des missions solo ou la question des dommages collateraux a ete adresse avant son arrivee.",
    "Mercenaire Fee independante, deployee pour les situations ou la puissance brute de lumiere est l'objectif. Elle travaille principalement pour les Dissidentes sur des operations de liberation des centres de captation de la Citadelle — les structures imperiales, construites pour resister aux assauts standard, ne sont pas conçues pour une Vague Sacree de son amplitude.",
    "Theophane accumule via Benediction sequence en rotation — chaque Benediction augmente la pression lumineuse interne. Barriere de Lumiere deployee puis immediatement liberee comme onde explosive. Vague Sacree maximale sur la zone la plus dense. Enchantement de Case sur la zone pour amplifier l'impact. Rayon de Lumiere de suivi sur les survivants. Miracle si la situation necessite une inversion totale. Elle ne se bat pas au corps a corps.",
    "Vague Sacree de Theophane a un rayon de 6 cases et repousse les ennemis de 2 cases. Barriere de Lumiere peut etre liberee deliberement comme explosion radiale (zone 3x3, degats equivalents a Rayon de Lumiere). Benediction stacks pour elle-meme : 3 Benedictions actives donnent +50% degats au prochain sort. Passif Accumulation Sainte : chaque sort Fee lance augmente la puissance du prochain de 15% (max +60%, reset apres utilisation)."
))

write(f"{BASE}/fee/366-floribonde/index.ts", char_file(
    366, "Floribonde", "Fée", "Battlemage", "Fées", "Citadelle", "Empire",
    "Fee dont le style de combat hybride Fee-physique est unique dans les archives de la Citadelle — elle combine des frappes physiques avec des decharges de Lumiere au contact, utilisant ses ailes comme armes supplementaires en combat rapproche. Ses ailes ont des bords durcis qui peuvent couper, et les decharges lumineuses qu'elle genere depuis ses poings creent un effet de lumiere-choc au moment de l'impact. Ses traits sont nets et froids, sa peau d'un blanc pur, ses yeux d'un jaune doré. Elle porte l'armure imperial de Battlemage adapte pour le combat en vol — des plaques legeres aux articulations importantes.",
    "Floribonde est loyale a l'Empire avec la conviction d'une Fee qui croit dans l'ordre etabli. La Citadelle sous contr ole imperial est plus stable qu'elle ne l'etait sous administration feerique autonome — du moins c'est ce qu'elle s'est convaincu. Sa technique de combat hybride a ete developpee dans les academies de l'Empire et elle en est fiere. Sa seule dissonance : les methodes de captation qu'elle applique parfois lui semblent disproportionnees.",
    "Combattante de ligne de l'Empire a la Citadelle, Floribonde est deployee pour les engagements directs avec les Fees des Dissidentes. Elle est l'une des rares Fees imperiales capable de suivre des unites comme Aelwyn en combat aerien. Ses techniques de corps a corps avec decharges lumineuses sont documentees comme une nouveaute tactique dans les archives militaires imperiales.",
    "Floribonde engage en vol — plonge, frappe au corps a corps avec decharge lumineuse simultanee. Rayon de Lumiere de suivi a bout portant. Barriere de Lumiere sur elle-meme pour absorber la riposte. Vague Sacree pour creer de l'espace apres l'engagement. Benediction sur elle-meme pour amplifier sa prochaine frappe. Purification pour annuler les effets de statut adverses. Miracle en ultime si necessaire.",
    "Les attaques au corps a corps de Floribonde infligent automatiquement une decharge de Rayon de Lumiere (50% degats) sur la cible. Rayon de Lumiere lance apres un corps a corps est instantane (pas de temps de cast). Barriere de Lumiere sur elle-meme pendant le vol est permanente tant qu'elle reste en mouvement. Passif Lumiere de Combat : chaque sort Fee lance dans le meme tour qu'une attaque physique donne +20% de degats a l'attaque physique suivante (stackable 2 fois)."
))

write(f"{BASE}/fee/367-chrysolea/index.ts", char_file(
    367, "Chrysoléa", "Fée", "Artillerie", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la specialite en tir de Rayon de Lumiere longue portee a produit une physiologie asymetrique — son oeil droit a evolue vers une structure de visee naturelle, avec une precision de mise au point qui depasse les instruments optiques standard. Ses ailes sont deployees en arriere de maniere permanente, formant un stabilisateur naturel pour ses tirs. Ses mains sont d'une finesse extreme, avec des doigts qui se terminent par des cristaux de lumiere solidifiee qu'elle renouvelle regulierement. Elle est petite et quiete — invisible dans un groupe, devastatrice a distance.",
    "Chrysolea est une perfectionniste du tir. Chaque Rayon doit etre optimal — angle, puissance, timing. Elle peut passer des heures a evaluer une position avant de tirer. Les Dissidentes ont appris a ne pas la presser — un Rayon de Chrysolea vaut dix tirs precipites d'un autre Artilleur.",
    "Artilleure de precision des Dissidentes, Chrysolea couvre les operations de liberation a la Citadelle depuis des positions elevees que les gardes imperiaux ne pensent pas a verifier. Ses Rayons de Lumiere longue portee ont stoppe plusieurs convois de captation en cours. Elle coordonne avec Séléniar (Capteur, Empire) involontairement — Seleniar detect ses signatures lumineuses, Chrysolea adapte ses emissions pour les rendre plus difficiles a distinguer des sources naturelles.",
    "Chrysolea choisit la position la plus haute disponible avec la meilleure ligne de vue. Benediction Persistante sur sa position pour un couvert Fee. Rayon de Lumiere en tir de precision longue portee. Enchantement de Case sous sa position pour une plateforme lumineuse stable. Vague Sacree si sa position est approchee. Barriere de Lumiere si l'assaut arrive quand meme. Resurrection Partielle d'un allie en danger depuis sa position surelev ee.",
    "Rayon de Lumiere de Chrysolea a une portee de 12 cases et peut etre charge 1 tour pour doubler les degats et ignorer les Barrieres. Benediction Persistante sur sa position rend celle-ci invisible aux detections lumineuses (Seleniar ne peut pas la tracker). Vague Sacree lancee depuis sa position haute a +2 de rayon. Passif Tir de Celeste : si Chrysolea n'a pas change de position depuis 2 tours, son Rayon de Lumiere devient un rayon Solaire — degats +50%, traverse les Barrieres de Lumiere ennemies."
))

write(f"{BASE}/fee/368-pixelar/index.ts", char_file(
    368, "Pixelar", "Fée", "Tireur", "Fées", "Citadelle", "Indépendant",
    "Fee de petite taille dont la technique de tir est basee sur la precision extreme plutot que la puissance — ses projectiles de lumiere sont concentres au maximum de densite, de la taille d'une aiguille, ce qui les rend quasi-invisibles en vol et presque impossibles a intercepter. Ses doigts sont particulierement fins et ses gestes de canali sation minimalistes — elle tire avec des mouvements presque imperceptibles. Ses ailes sont petites et rapides, lui permettant des micro-ajustements de position permanents. Ses yeux sont d'un vert lumi neux inhabituels chez les Fees.",
    "Pixelar est une artiste du petit impact maximum. Elle ne cherche pas a detruire — elle cherche a atteindre exactement le point qui compte. Cette philosophie la rend independante : les factions veulent des resultats larges, elle veut des resultats precis. Elle prend des contrats ou la cible est clairement designee et ou la definition du succes est nette.",
    "Mercenaire Fee de precision, travaillant a la Citadelle pour des clients dont les besoins sont tres specifiques — stopper un sortilege en cours en eliminant le caster sans dommages collateraux, par exemple. Ses tarifs refletent la difficulte technique de ses missions. Elle a travaille pour les Dissidentes sur plusieurs operations de libration — elle peut neutraliser un garde sans declencher d'alerte.",
    "Pixelar s'installe dans une position discrete. Benediction Persistante pour une couverture passive. Rayon de Lumiere de precision — tir minimaliste sur la cible exacte. Purification sur les defenses adverses pour ouvrir les vulnerabilites. Enchantement de Case sous sa position pour la stabilite. Barriere de Lumiere si approchee. Vague Sacree en dernier recours si sa position est decouverte.",
    "Rayon de Lumiere de Pixelar est invisible en vol — les ennemis ne peuvent pas le reperer avant impact. Depuis une position stationnaire de 1 tour, ses Rayons ont 100% de chance de critique. Purification de Pixelar peut etre lancee a travers des Barrieres de Lumiere ennemies. Passif Aiguille de Lumiere : les attaques de Pixelar ignorent 35% de l'armure et des boucliers — ses projectiles miniaturises traversent les protections larges."
))

write(f"{BASE}/fee/369-lumicide/index.ts", char_file(
    369, "Lumicide", "Fée", "Assassin", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la particularite est d'utiliser la Lumiere comme vecteur d'obscurite — une inversion de l'element qui a pris des decennies de maitrise. Ses sorts de Lumiere ne brillent pas : ils absorbent la lumiere ambiante, creant des zones d'obscurite lumineuse qui brulent ce qu'elles touchent par privation. Sa peau est d'un noir rare pour une Fee, consequence de cette inversion. Ses ailes semblent absorber la lumiere au lieu de la refleter. Ses yeux sont d'un blanc pur dans un visage sombre. Les autres Fees lui trouvent une presence inquietante que sa personnalite douce contredit.",
    "Lumicide a developpe son style d'inversion lumineuse comme defense — elle a realise que la lumiere etait une arme a double tranchant et que son revers etait tout aussi puissant. Elle utilise cet outil pour les Dissidentes avec discernement — uniquement contre les structures de captation et leurs operateurs directs, jamais contre des civils. Sa philosophie est que la lumiere qui sert l'oppression peut etre retournee.",
    "Eliminatrice de precision des Dissidentes a la Citadelle. Lumicide neutralise les agents imperiaux qui operent les centres de captation Fee. Son style — absorption de lumiere qui brule — est particulierement efficace contre les unites qui utilisent la Lumiere comme protection, ce qui en fait une counter naturelle contre Séléniar et Floribonde.",
    "Lumicide approche dans les zones d'ombre naturelles — ses ailes absorbantes la fondent dans l'obscurite. Rayon d'Absorption (Rayon de Lumiere inverse) sur la cible — siphonne la lumiere autour d'elle et inflige des degats de privation. Benediction inversee — au lieu de soigner, elle affaiblit l'aura lumineuse de la cible. Purification utilisee a l'envers — elle corrompt les protections lumineuses de sa cible. Vague Sacree absorbante pour une sortie rapide. Resurrection inverse sur un ennemi pour l'affaiblir.",
    "Rayon de Lumiere de Lumicide fonctionne en inversion — il absorbe la lumiere autour de la cible et inflige des degats de privation (ignore les Barrieres de Lumiere). Barriere de Lumiere adverse : Lumicide la traverse sans peine et peut la detruire avec un Rayon. Sa premiere attaque depuis une zone sombre inflige 200% de degats. Passif Inversion Lumineuse : les sorts Fee adverses cibles sur Lumicide sont absorbes et la soignent de 20% de leurs degats au lieu de l'affecter."
))

write(f"{BASE}/fee/370-palatin/index.ts", char_file(
    370, "Palatin", "Fée", "Escrimeur", "Fées", "Citadelle", "Empire",
    "Fee dont le style de duel a la lumiere est le plus formalise de la Citadelle — il a codifie ses techniques en un systeme que l'Empire a adopte comme doctrine de duel Fee. Ses ailes sont deployees en permanence pendant les duels, formant un bouclier dorsal naturel. Ses mains canalisent la Lumiere avec une precision que ses contemporains decrivent comme sculpturale — chaque Rayon est place avec l'exactitude d'un artisan. Il porte l'armure de dueliste imperial la plus ornee disponible — ce n'est pas de la vanite, c'est de la signalisation : il veut que ses adversaires sachent exactement qui ils affrontent.",
    "Palatin est un dueliste codifie. Il croit que le combat singulier est la forme la plus honnete de resolution de conflits et que la codification de ses regles est ce qui le distingue du meurtre. Ses duels ont des regles qu'il respecte meme au detriment de sa propre victoire. L'Empire l'apprecie pour la valeur symbolique de ses victoires — un Elu qui perd face a Palatin perd publiquement.",
    "Dueliste representatif de l'Empire a la Citadelle, Palatin est deploye pour les confrontations qui servent d'exemple. Ses victoires contre des Fees des Dissidentes sont documentees et diffusees. Sa relation avec Lumicide est une adversite professionnelle — il a perdu face a elle deux fois, ce qui est sa seule anomalie statistique.",
    "Palatin etablit les termes du duel. Vague Sacree sur le perimetre cree une arene lumineuse. Il est face a face avec sa cible — Rayon de Lumiere en tir de precision. Barriere de Lumiere sur lui-meme pour absorber les contre-attaques. Benediction sur lui-meme pour amplifier ses prochains sorts. Corps a corps avec decharge lumineuse. Purification pour annuler les avantages adverses. Miracle en situation desespere.",
    "En 1v1, Rayon de Lumiere de Palatin ricoche — il touche la cible, puis rebondit sur la Barriere de Lumiere de Palatin pour toucher a nouveau (30% degats au rebond). Vague Sacree en situation de duel est instantanee et gratuite. Benediction sur lui-meme triple la duree. Passif Dueliste Sacre : en situation de duel (1v1), tous les sorts de Palatin ont leur cout PM reduit de 2 et leur portee augmentee de 1. Son Miracle peut etre utilise quand il est a 40% PV au lieu du seuil standard."
))

write(f"{BASE}/fee/371-aurantia/index.ts", char_file(
    371, "Aurantia", "Fée", "Vanguard", "Fées", "Citadelle", "Convergence",
    "Fee dont le Sanctuaire a ete internalise comme une aura de combat — elle avance et le terrain autour d'elle devient momentanement sacre, hostile aux ennemis et protecteur des allies. Sa peau est d'un doré chaud qui pulse en rythme avec ses pas. Ses ailes sont larges et robustes, plus proches de celles d'un oiseau de proie que de celles d'une Fee habituelle. Ses yeux sont d'un orange brulant. Elle marche toujours en tete — pas par bravade, par nature. C'est sa place.",
    "Aurantia avance et la situation change. La Convergence l'a comprise comme une force de transformation de terrain plutot que comme une unite d'assaut — elle cree les conditions, les autres exploitent. Sa relation avec les autres membres de la Convergence est bonne mais distante ; elle est trop concentree sur l'avant pour la conversation.",
    "Vanguard Fee de la Convergence dans les operations a la Citadelle. Aurantia ouvre les acces aux zones sacrees que l'Empire a securitisees. Son aura de Sanctuaire mobile — unique parmi les Vanguards documentes — cree une zone protegee qui avance avec elle, permettant aux allies de la suivre dans des zones normalement inaccessibles. Son association avec Psykhon (Convergence) est une ligne de front duale documentee.",
    "Aurantia avance avec Sanctuaire actif — une zone sacree mobile autour d'elle. Vague Sacree en cone devant pour nettoyer la voie. Enchantement de Case sur les positions qu'elle traverse pour les fortifier pour les suivants. Barriere de Lumiere sur les flancs pour proteger ses allies. Rayon de Lumiere sur les casters adverses qui menacent sa progression. Benediction sur les allies qui la suivent. Miracle en inversion si la progression est bloquee.",
    "Sanctuaire de Aurantia est mobile — il se deplace avec elle dans un rayon de 2 cases. Vague Sacree en cone de 3 cases de largeur au lieu d'un rayon. Enchantement de Case qu'elle cree en deplacement dure le combat entier. Passif Aura Sainte Mobile : les alliees dans un rayon de 2 cases de Aurantia recoivent les benefices de Benediction Persistante automatiquement — sans que Aurantia doive les Benir individuellement."
))

write(f"{BASE}/fee/372-kalyptis/index.ts", char_file(
    372, "Kalyptis", "Fée", "Gardien", "Fées", "Citadelle", "Dissidentes",
    "Fee dont les ailes se sont transformees en boucliers actifs — plus larges que hautes, avec une rigidite de chitine lumineuse qui les rend capables d'absorber des decharges magiques sans se dechirer. Sa posture de Gardien est celle d'un etre qui a fait de son corps la protection des autres — bras legerement ouverts, prets a couvrir, torse tourne vers la menace. Sa peau emet une Benediction Persistante passive visible comme un voile dore tres leger qui s'etend a un metre autour d'elle et beneficie automatiquement aux allies proches.",
    "Kalyptis protege les Fees. Pas par ideologie politique elaborate, par un sentiment qui precede toute doctrine — sa communaute d'abord. Les Dissidentes protegent les Fees, elle protege les Dissidentes. Cette logique de protection concentrique est sa philosophie entiere. Elle est sobre, directe, et ne justifie pas ses choix.",
    "Gardienne de la communaute Fee des Dissidentes a la Citadelle. Kalyptis protege les positions de Lumielle (Soutien) et Chrysolea (Artillerie) — les deux actifs les plus critiques de la brigade Fee. Ses ailes-boucliers ont absorbe des decharges qui auraient elimine les unites derriere elle plusieurs fois. L'Empire la cible en priorite dans toute operation contre la brigade Fee des Dissidentes.",
    "Kalyptis s'interpose. Barriere de Lumiere en permanence sur elle-meme. Benediction sur Lumielle en priorite. Sanctuaire sur la position de Chrysolea. Vague Sacree sur les ennemis qui approchent sa zone de protection. Purification pour annuler les effets de statut sur ses allies. Rayon de Lumiere sur les ennemis les plus proches. Resurrection Partielle d'un allie tombe si elle peut le faire sans quitter sa position.",
    "Barriere de Lumiere de Kalyptis peut etre deployee sur un allie adjacent gratuitement (0 PM) une fois par tour. Ses ailes-boucliers absorbent automatiquement 25% des degats de zone destines aux allies directement derriere elle. Benediction qu'elle lance a portee adjacente est instantanee. Passif Voile Protecteur : les allies dans un rayon de 2 cases de Kalyptis beneficient automatiquement de Lumiere Protectrice passive — les sorts a cible unique adverses ont 15% de chance de les rater."
))

write(f"{BASE}/fee/373-prismatique/index.ts", char_file(
    373, "Prismyx", "Fée", "Spécialiste", "Fées", "Citadelle", "Indépendant",
    "Entite Fee dont la maitrise de la Lumiere a atteint un stade de difraction totale — Prismyx n'emet pas de lumiere blanche mais la totalite du spectre visible simultanement, ce qui rend son apparence dependante de l'angle d'observation : de face, il est aveuglant de blanc ; de cote, il est un arc-en-ciel mouvant. Sa forme physique est floue aux bords, comme si sa propre lumiere le dissolvait legerement. Il communique en modulant les couleurs de sa lumiere plutot qu'en parlant — chaque couleur correspond a une frequence de communication etablie avec ceux qui le connaissent.",
    "Prismyx n'appartient a aucune faction parce qu'il a une perspective sur la Lumiere qui depasse les utilisations factionelles. Il est la Lumiere sous toutes ses formes simultanement, ce qui lui donne un point de vue qu'aucune faction ne peut pleinement comprendre. Il intervient quand quelque chose menace la Lumiere elle-meme en tant que principe — pas une faction, l'element.",
    "Phenomene lumineux documente dans les archives de la Citadelle comme la Lumiere Premiere — une manifestation de l'element qui depasse l'Elu individuel. Prismyx est mentionne dans les archives mythologiques fees comme la conscience de la Lumiere elle-meme. Son intervention lors de la crise de captation lumineuse massive de l'Empire a la Citadelle a ete decisive — il a rendu impossible le fonctionnement des instruments de captation en saturant le spectre.",
    "Prismyx n'a pas de position fixe — il est partout ou il y a une Case Fee. Miracle depuis n'importe quelle Case Fee de la carte. Vague Sacree globale affecte toutes les unites ennemies sur des Cases non-Fee simultanement. Enchantement de Case sur n'importe quelle case de la carte. Benediction sur tous les allies simultanement. Resurrection Partielle sur n'importe quel allie tombe sur la carte. Il n'a pas de cooldown sur ses sorts Fee basiques.",
    "Prismyx peut lancer tous ses sorts Fee depuis n'importe quelle Case Fee sur la carte (pas de portee restrictive). Miracle de Prismyx peut etre utilise quand n'importe quel allie est en danger (pas seulement lui-meme). Toutes les Cases Fee creees par Prismyx soignent les allies de 10% PV par tour (au lieu de 5%). Passif Spectre Complet : Prismyx ne peut pas etre cible par des sorts Ténèbres — la lumiere qu'il emet les dissout avant contact. Chaque tour, toutes les Cases Fee de la carte gagnent 1 tour de duree supplementaire."
))

print("Fee: 13 characters written")

# ============================================================
# POISON (391-403) — Sylvans / Sylvera (+ Chthoniens/Ormn-Dur, Umbriens/Noctea)
# Spells: Crachat Toxique, Flaques Toxiques, Brouillard Corrosif, Injection,
#         Epidemie, Terrain Contamine, Venin Paralytique, Corruption Organique,
#         Necrose, ULTIME — Pandemie
# Passifs: Adaptation, Accumulation Toxique
# ============================================================

write(f"{BASE}/poison/391-venefica/index.ts", char_file(
    391, "Vénéfica", "Poison", "Enchanteur-Soutien", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvane dont la peau a absorbe plusieurs decennies de travail avec des venins — sa couleur naturelle verte est striee de veines d'un violet profond qui seguent quand elle est en contact avec des substances toxiques, comme un indicateur biologique de sa propre saturation. Ses cheveux sont constitues de filaments vegetaux qui produisent en permanence de micro-doses d'antidotes — ses allies proches sont passivement proteges contre les empoisonnements de faible intensite. Elle se deplace avec une lenteur deliberee qui n'est pas de la langueur mais de la vigilance chimique : elle sent les toxines dans l'air et calibre ses pas en consequence.",
    "Venefica croit que la gestion des poisons est une responsabilite morale — savoir faire du mal avec une substance implique le devoir de savoir le defaire. Elle a rejoint les Dissidentes quand l'Empire a commence a utiliser des toxines de masse sur des communautes sylvanes recalcitrantes. Son expertise en antidotes est sa contribution principale; son expertise en poisons, une consequence de la meme connaissance.",
    "Coordinatrice toxicologique des brigades Poison des Dissidentes a Sylvera. Venefica maintient les brigades en combat en neutralisant les effets toxiques adverses et en distribuant des resistances adaptees avant les engagements. Son Adaptation passive amelioree s'etend a ses allies via ses filaments de cheveux antidotaux — une technique unique dans les archives de Sylvera. Elle coordonne avec Gorgatix (Vanguard, Convergence) sur les terrains d'operation toxiques.",
    "Venefica prepare le terrain avant l'engagement — Terrain Contamine sur les zones que les allie s vont traverser, calibre pour eux (ils ne sont pas affectes). Brouillard Corrosif sur les zones adverses. Elle distribue des doses d'Adaptation a ses allies — les rendant resistants aux toxines ennemies. Injection de soin toxique sur les allies blesses. Corruption Organique sur les ennemis les plus resistants. Pandemie en dernier recours si la position est perdue.",
    "Adaptation de Venefica peut etre appliquee a 2 allies simultanement. Injection de Venefica soigne 30% des PV max de la cible (effet de soin du venin inverse). Les alliees dans un rayon de 3 cases de Venefica ont une resistance passive de 15% aux Poisons ennemis. Passif Antidote Vivant : quand un allie dans un rayon de 4 cases de Venefica est empoisonne, elle peut reagir et annuler l'empoisonnement en 1 tour (reaction hors tour, 2 PM, cooldown 3)."
))

write(f"{BASE}/poison/392-corruktor/index.ts", char_file(
    392, "Toxvar", "Poison", "Enchanteur-Capteur", "Chthoniens", "Ormn-Dur", "Empire",
    "Chthonien dont l'expertise en toxicologie a ete mise au service de l'identification chimique des Elus Poison recalcitrants. Ses bras sont parsemes d'aiguilles d'injection retractables — une dizaine par avant-bras — qu'il utilise pour prelever des echantillons biologiques sur les cibles d'interet pour l'Empire. Sa peau a une teinte jaunatre consequence des decennies d'exposition aux toxines qu'il manipule. Il porte l'equipement de terrain du laboratoire imperial — des flacons, des chromatographes de poche, des detecteurs chimiques qui l'entourent comme une collection d'instruments.",
    "Toxvar est un scientifique qui sert l'Empire parce que l'Empire finance sa recherche. Il catalogue les souches de venin des Elus Poison avec la passion d'un taxonomiste — chaque Elu a une signature chimique unique, et il les rassemble comme des specimens. Que les Elus qu'il catalogue soient ensuite integres dans des programmes de captation... c'est une consequence administrative qui ne le concerne pas directement.",
    "Agent de catalogage toxicologique de l'Empire a Ormn-Dur. Toxvar identifie les Elus Poison resistants en analysant leurs signatures chimiques et determine leur valeur pour les programmes de captation. Ses donnees ont permis l'identification de souches de venin jusqu'alors inconnues — informations que l'Empire utilise autant pour la captation que pour la production d'antidotes pour ses propres troupes.",
    "Toxvar place des detecteurs chimiques (Flaques Toxiques en mode trace) sur les routes de transit. Quand un Elu Poison passe, il preleve un echantillon via Crachat Toxique marque. Brouillard Corrosif pour reveler les signatures chimiques cachees. Injection de traceur — il empoisonne sa cible avec un venin identifiable pour la suivre a distance. Venin Paralytique pour immobiliser la cible de captation.",
    "Les toxines de Toxvar contiennent un marqueur chimique — les unites qu'il touche sont traceables pendant 5 tours meme si elles deviennent invisibles. Flaques Toxiques de Toxvar en mode detecteur signalent chaque unite Poison qui les traverse sans cout PM. Injection de Toxvar peut etre utilisee pour prelever un echantillon (revele les capacites de la cible). Passif Analyse Instantanee : Toxvar identifie automatiquement l'element et la classe de chaque unite qu'il touche avec un sort."
))

write(f"{BASE}/poison/393-sclerotis/index.ts", char_file(
    393, "Sclérotis", "Poison", "Juggernaut", "Sylvans", "Sylvera", "Convergence",
    "Sylvan dont l'absorption chronique de toxines a durci ses tissus organiques en quelque chose qui n'est plus tout a fait biologique — une sclero se chimique qui a transforme sa peau en une membrane dense, legerement translucide, qui absorbe les substances toxiques comme une eponge et les transforme en energie. Sa silhouette est massive et irreguliere, avec des excroissances chitineuses sur les epaules et les avant-bras qui se sont formees comme des dechets de la transformation biologique. Il n'a pas d'aversion pour les environnements toxiques — il les prefere.",
    "Sclerotis a une tolerance absolue pour ce que les autres considerent hostile. Poisons, acides, milieux corrosifs — ce sont ses conditions de confort. La Convergence l'a inte gre parce que ses resistances lui permettent d'operer dans des zones de combat toxique ou d'autres unites ne peuvent pas fonctionner. Il n'a pas de philosophie politique — il a une ecologie.",
    "Front de resistance toxique de la Convergence dans les operations de terrains contamines a Sylvera. Sclerotis avance dans des environnements que ses congeneres ne peuvent pas traverser — il est utilise pour les engagements dans des zones ou les Dissidentes ont deploye un Terrain Contamine extensif. Sa resistance aux Poisons le rend efficace contre les unites de Sylvera qui basent leur defense sur la toxicite du terrain.",
    "Sclerotis avance dans les Terrains Contamines sans subir d'effets. Adaptation maximale activee — il ne prend aucun degat des zones Poison. Flaques Toxiques sur sa route pour créer une zone de securite inversee (les allies immunises, les ennemis empoisonnes). Corruption Organique sur les defenseurs adverses. Necrose sur les unites qui tentent de le ralentir. Epidemie si plusieurs unites ennemies sont concentrees. Pandemie en fermeture.",
    "Sclerotis est immunise a tous les effets de Poison, y compris les siens. Ses attaques au corps a corps infligent automatiquement Accumulation Toxique (2 stacks par frappe). Corruption Organique de Sclerotis a un rayon d'1 case supplementaire. Passif Bioaccumulation : chaque effet de Poison qu'il absorbe (qui l'aurait affecte sans son immunite) lui donne +5% de degats Poison pendant 2 tours (max +30%)."
))

write(f"{BASE}/poison/394-serphyle/index.ts", char_file(
    394, "Serphyle", "Poison", "Plongeur", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvane dont la mutation toxique s'est exprimee dans la direction des serpents — ses canines ont evolue en crochets a venin retractables, et sa langue est bifurquee avec une sensibilite chimique qui lui permet de detecter les toxines et les signatures biologiques dans un rayon de plusieurs metres. Sa peau est couverte de micro-ecailles vertes qui lui donnent un aspect reptilien. Elle se deplace a une vitesse rasante, proche du sol, en sinuant plutot qu'en marchant droit. Elle n'a pratiquement aucun equipement — son corps est son arsenal.",
    "Serphyle est une chasseuse par nature. Elle identifie sa cible, elle s'approche, elle frappe, elle disparait. Pas de complication, pas d'interrogation morale sur la methode tant que la cible est legitime. Les Dissidentes lui conviennent parce qu'ils lui fournissent des cibles dont la legitimite est etablie. Elle refuse les missions sur lesquelles elle n'a pas de certitude.",
    "Operatrice d'elimination rapide des Dissidentes a Sylvera, Serphyle neutralise les agents imperiaux responsables des operations de contamination des zones sylvanes. Son venin est parmi les plus rapides d'action documentes chez les Elus Poison — paralysie en secondes, neutralisation en minutes. Elle coordonne avec Venefica : la Soutien lui prepare des resistances pour les terrains adverses qu'elle doit traverser.",
    "Serphyle approche en rasant le sol sur un Terrain Contamine allie — elle y est immunisee, les gardes pas. Brouillard Corrosif pour masquer son approche. Injection de venin de paralysie directement en corps a corps depuis la semiinvisibilite. Venin Paralytique si le premier contact n'est pas suffisant. Crachat Toxique pour maintenir la cible bloquee pendant la retraite. Terrain Contamine sur sa route de sortie pour retarder les poursuivants.",
    "Injection de Serphyle est instantanee — pas de temps de cast, utilise en meme temps qu'un deplacement. Son venin unique accumule 3 stacks d'Accumulation Toxique par Injection (au lieu de 1). Brouillard Corrosif cree par Serphyle la rend invisible a l'interieur (elle ne subit pas ses propres effets). Passif Chasse Silencieuse : les attaques de Serphyle ne revelent pas sa position si elle est sur un Terrain Contamine allie — les victimes savent qu'elles ont ete touchees mais pas d'ou."
))

write(f"{BASE}/poison/395-morbiax/index.ts", char_file(
    395, "Morbiax", "Poison", "Mage-Burst", "Umbriens", "Noctéa", "Indépendant",
    "Umbrien dont la mutation Poison a produit une biologie interne qui genere des toxines en surplus — des toxines qui ne peuvent pas etre retenues indefiniment et qui s'accumulent jusqu'a une decharge explosive necessaire. Sa peau a une couleur mauve intense, presque lumineuse dans l'obscurite, et des pustules de toxine se forment regulierement a sa surface avant d'etre reabsorbees ou liberees dans un Crachat. Il ne peut pas s'approcher de la plupart des etres vivants sans risque — le nuage toxique permanent autour de lui est involontaire.",
    "Morbiax est independant parce qu'il est literalement toxique pour tout le monde y compris ses alliees potentiels. Sa zone d'exclusion biologique rend l'integration dans une formation impossible. Il accepte des missions solo, briefees a distance, avec des objectifs ou sa toxicite est une qualite plutot qu'un probleme.",
    "Mercenaire Poison independant, specialise dans les operations ou la contamination de zone est l'objectif — pas l'elimination precise mais la neutralisation d'une zone entiere. Il travaille pour les Dissidentes quand leurs objectifs incluent des terrains que l'Empire tente d'occuper de maniere permanente. Sa methode : contaminer si profondement qu'une occupation prolongee devient medicalement impossible.",
    "Morbiax accumule en retenant sa decharge naturelle — la pression interne augmente, visible comme l'intensification de sa lueur mauvelette. Quand la saturation est maximale, Pandemie : decharge totale sur la zone. Terrain Contamine en zone etendue autour de lui. Brouillard Corrosif maximalise. Epidemie sur toutes les unites presentes. Flaques Toxiques pour prolonger la contamination apres sa decharge. Il ne peut pas rester dans la zone apres la decharge — il se repositionne.",
    "Pandemie de Morbiax a un rayon de 6 cases. Sa decharge naturelle se produit automatiquement apres 4 tours d'accumulation — elle affecte tout dans un rayon de 3 cases. Terrain Contamine de Morbiax couvre une zone 4x4 au lieu de 2x2. Passif Saturation Toxique : chaque tour ou Morbiax ne lance pas de sort, il accumule 1 charge de Saturation. A 4 charges, son prochain sort inflige +100% de degats. Les charges se perdent apres utilisation."
))

write(f"{BASE}/poison/396-alcalix/index.ts", char_file(
    396, "Alcalix", "Poison", "Battlemage", "Sylvans", "Sylvera", "Empire",
    "Sylvan dont l'expertise alchimique des poisons a ete integree dans un style de corps a corps toxique — ses poings sont couverts de gants de diffusion alchimique qui injectent du venin au moment de l'impact. Chaque frappe est une Injection. Sa peau est d'un vert fonce et ses yeux d'un jaune acide. Il porte l'armure imperiale de Battlemage avec des modifications pour ses gants d'injection — des canaux de venin integres dans les articulations. Son venin change de composition selon la cible — il recalibre en temps reel selon ce qu'il detecte de la biologie adverse.",
    "Alcalix est un alchimiste du corps a corps. Chaque adversaire est un probleme de chimie qu'il resout au contact. L'Empire l'apprécie parce que son expertise en calibration toxique rapide est sans equivalent dans ses rangs — il peut adapter sa composition de venin contre des resistances qu'il n'a jamais rencontrees auparavant. Sa loyaute est a l'Empire comme institution scientifique.",
    "Combattant hybride imperial deploye sur les terrains de Sylvera. Alcalix est particulierement efficace contre les Elus Poison des Dissidentes dont les resistances sont connues — il recalibre son venin pour les souches qu'ils ont developpees en protection. C'est une course aux armements chimique perpetuelle que sa flexibilite lui donne un avantage structurel.",
    "Alcalix engage en corps a corps avec Injection automatique au contact. Brouillard Corrosif pour masquer son approche et empoisionner la zone. Flaques Toxiques sur les routes de fuite adverses. Venin Paralytique pour immobiliser en cas de riposte trop forte. Corruption Organique en suivi pour maximiser les degats progressifs. Terrain Contamine autour du perimetre du combat. Necrose en fermeture.",
    "Chaque frappe au corps a corps d'Alcalix injecte automatiquement 2 stacks d'Accumulation Toxique. Brouillard Corrosif de Alcalix est adaptatif — il contient les toxines les plus efficaces contre les unites presentes dans la zone. Venin Paralytique lance apres 3 stacks d'Accumulation sur la cible a une duree de 3 tours au lieu de 1. Passif Recalibration : les ennemis qui ont une resistance a ses toxines voient cette resistance reduite de 20% chaque tour qu'ils restent a portee de corps a corps."
))

write(f"{BASE}/poison/397-plagios/index.ts", char_file(
    397, "Plagios", "Poison", "Artillerie", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonien dont la specialite en projection toxique longue portee a developpe une structure de lancement biologique dans ses avant-bras — des tubes de chair durcie qui canalisent et propulsent les Crachats Toxiques a des distances qui depassent la portee des armes de contact. Sa peau a une texture granuleuse et secrete en permanence une substance lipidique protective qui l'isole de ses propres toxines. Ses yeux sont proteges par des membranes anti-toxiques. Il se positionne toujours en hauteur — ses projections sont optimisees pour une trajectoire descendante.",
    "Plagios est methodique et sans remords sur ses cibles — tant que ce sont des combattants actifs et pas des civils. Sa methode de contamination de zone a longue portee est particulierement efficace pour les situations ou un assaut direct serait suicide. Les Dissidentes l'utilisent exactement pour ca.",
    "Artilleur toxique des Dissidentes, Plagios bombarde les positions imperiales a Ormn-Dur depuis des hauteurs que les troupes adverses ne peuvent atteindre sans exposer leurs flancs. Ses projections de Brouillard Corrosif sont utilisees pour forcer le dedeploiement de formations imperiales compactes — elles ne peuvent pas tenir leurs positions sous une pluie de toxines. Il coordonne avec Scutax (Insecte, Dissidentes) sur certains terrains.",
    "Plagios choisit une position haute. Terrain Contamine en bas — les ennemis ne peuvent pas avancer sans traverser des zones toxiques. Brouillard Corrosif en rideau entre sa position et les ennemis. Crachat Toxique de precision sur les unites qui essaient quand meme. Flaques Toxiques sur les routes de contournement. Epidemie si une unites contaminee rejoint un groupe. Venin Paralytique sur les commandants adverses. Pandemie si la position est debordee.",
    "Crachat Toxique de Plagios a une portee de 10 cases et cree une Flaque Toxique sur la case d'impact. Brouillard Corrosif de Plagios depuis une hauteur superieure de 2Z couvre une zone 5x5. Epidemie lancee depuis la hauteur se propage en cercle du point d'impact. Passif Tir Parabolique : si Plagios est a Z+2 ou plus au-dessus de sa cible, ses projections ignorent les couverts et les Barrieres (la trajectoire passe par dessus)."
))

write(f"{BASE}/poison/398-sylvacide/index.ts", char_file(
    398, "Sylvatox", "Poison", "Tireur", "Sylvans", "Sylvera", "Indépendant",
    "Sylvan dont la production de toxines de contact a ete optimisee pour le tir a distance — ses doigts produisent des micro-aiguilles de toxine cristallisee qu'il projette avec une precision chirurgicale sur des cibles jusqu'a huit cases. Ces aiguilles sont quasi-invisibles en vol, ce qui rend ses attaques difficiles a anticiper. Sa peau est d'un vert-brun qui se confond avec la vegetation de Sylvera. Il se deplace lentement mais rarement — il choisit une position et y reste aussi longtemps que possible.",
    "Sylvatox est un professionnel de la patience appliquee aux aiguilles. Il peut attendre des heures en position, dans l'inconfort, sans mouvement, pour le moment optimal. Son independance vient de sa valeur sur le marche — les deux factions le veulent, ce qui lui donne une liberte de choix qu'il exploite pour choisir ses missions selon des criteres qui lui appartiennent.",
    "Mercenaire Poison independant a Sylvera. Sylvatox travaille principalement pour des communautes sylvanes qui n'ont les moyens d'aucune faction mais qui ont besoin de protection contre les expeditions de captation imperiales. Ses tarifs sont ajustes selon la capacite financiere du client. Pour les Dissidentes, il accepte souvent des missions en dessous de ses tarifs habituels.",
    "Sylvatox choisit une position dans la vegetation de Sylvera — naturellement camouflant pour un Sylvan. Venin Paralytique de precision sur la cible principale. Crachat Toxique sur les renfort qui approchent. Flaques Toxiques sur les routes de transit. Il attend que l'Accumulation Toxique fasse son travail. Corruption Organique sur la cible paralysee. Terrain Contamine autour de sa position en defense. Il ne bouge que si absolument necessaire.",
    "Aiguilles de Sylvatox sont invisibles en vol — les ennemis ne voient que l'effet, pas le projectile. Venin Paralytique de Sylvatox depuis une position stationnaire de 1 tour dure 3 tours. Crachat Toxique peut appliquer Accumulation Toxique a distance (3 stacks par tir). Passif Predateur Immobile : en restant stationnaire 1 tour complet, Sylvatox devient invisible. Ses attaques depuis l'invisibilite ont un bonus de +50% de stacks d'Accumulation Toxique appliques."
))

write(f"{BASE}/poison/399-umbralix/index.ts", char_file(
    399, "Umbralix", "Poison", "Assassin", "Umbriens", "Noctéa", "Dissidentes",
    "Umbrien dont la specialite Poison s'exprime dans les toxines neuronales — des substances qui affectent directement le systeme nerveux de la cible en quelques secondes, creant des disruptions sensorielles, des paralysies partielles, et une confusion profonde. Sa peau est d'un gris-mauve qui se confond avec les zones d'ombre d'Ormn-Dur. Ses yeux ont une bioluminescence faible, mauve, qui s'eteint deliberement quand il est en mode furtif. Il n'a aucun equipement encombrant — juste une combinaison ajustee avec des poches pour ses toxines et des gants qui diffusent le venin au contact.",
    "Umbralix est un chirurgien de la neutralisation. Il ne tue pas — il neutralise. Cette distinction est fondamentale pour lui : une cible neutralisee peut etre relachee, une cible morte est une martyre potentielle. Les Dissidentes lui ont fourni un cadre ethique qui correspond exactement a sa philosophie operationnelle.",
    "Operateur de neutralisation des Dissidentes, utilise pour les missions ou la captation d'un agent imperial est preferable a son elimination. Umbralix peut rendre une cible completement non-fonctionnelle pendant plusieurs heures avec un dosage precis de ses toxines neuronales. Ses operations avec Serphyle sont complementaires : elle elimine, il neutralise — selon l'objectif de la mission.",
    "Umbralix approche depuis une zone d'ombre — il coupe sa bioluminescence. Injection de toxine neuronale directement en corps a corps. Venin Paralytique sur la cible en priorite. Brouillard Corrosif sur la zone pour masquer l'operation. Corruption Organique pour une neutralisation prolongee. Flaques Toxiques sur les routes d'acces pour ralentir les renforts. Crachat Toxique de couverture pendant la retraite.",
    "Injection d'Umbralix applique un effet de Confusion sensorielle pendant 2 tours (la cible ne peut pas cibler avec precision). Venin Paralytique d'Umbralix peut etre dosa a la non-elimination — la cible est immobilisee mais conserve ses PV (utile pour captation). Brouillard Corrosif d'Umbralix le rend invisible a l'interieur. Passif Neurotoxine Selective : Umbralix peut choisir le type d'effet de son venin — paralysie, confusion, ou affaiblissement — selon la mission."
))

write(f"{BASE}/poison/400-caustius/index.ts", char_file(
    400, "Caustius", "Poison", "Escrimeur", "Sylvans", "Sylvera", "Empire",
    "Sylvan dont le style de duel toxique a ete formalise en une discipline que l'Empire appelle Escrime Corrosive — l'utilisation de toxines de contact en combat singulier, appliquees via une lame qui est son propre avant-bras enduit de substances caustiques. Sa peau a une teinte olivatre et ses yeux sont d'un vert acide. Il porte l'armure de dueliste imperiale avec des modifications pour son bras-lame — une encoches dans le gantlet droit qui permet l'application directe de sa toxine. Il a sacrifie son avant-bras droit au service de sa technique : la peau est partiellement corroder par des annees d'exposition.",
    "Caustius est un perfectionniste de la degradation. Il ne cherche pas a tuer rapidement — il cherche a corroder progressivement les defenses adverses jusqu'a leur effondrement. Cette patience est sa marque. L'Empire l'appreciate parce que ses victoires en duel sont d'une efficacite documentaire : les adversaires s'effondrent systematiquement apres un certain nombre d'echanges.",
    "Dueliste imperial deploye pour les confrontations avec les Elus Poison adverses a Sylvera. Caustius est envoye quand l'Empire a besoin qu'un Elu Poison ennemi soit neutralise proprement — pas tue, neutralise et discredite en duel. Son affrontement avec Serphyle est documente : il n'est pas sorti vainqueur, ce qui constitue son seul echec enregistre.",
    "Caustius etablit un perimetre de Flaques Toxiques autour du duel. Il engage en corps a corps avec son bras-lame enduit. Crachat Toxique si l'adversaire essaie de prendre de la distance. Injection de toxine corrosive en suivi. Venin Paralytique quand l'Accumulation est suffisante. Corruption Organique en fermeture pour accelerer la degradation. Necrose en final sur une cible suffisamment affaiblie.",
    "En 1v1, Caustius applique automatiquement 1 stack d'Accumulation Toxique sur sa cible a chaque tour de contact. Injection de Caustius en duel applique 3 stacks. Necrose lancee sur une cible avec 5 stacks ou plus inflige des degats immediats de 30% PV max en plus des degats progressifs. Passif Corrosion Permanente : les toxines de Caustius en situation de duel reduisent l'armure de la cible de 5% par stack d'Accumulation actif (max -25%)."
))

write(f"{BASE}/poison/401-gorgatix/index.ts", char_file(
    401, "Gorgatix", "Poison", "Vanguard", "Chthoniens", "Ormn-Dur", "Convergence",
    "Chthonien dont la resistance aux toxines a atteint un niveau qui rend les zones de combat toxique des zones de confort pour lui — il avance dans des environnements que les autres unites ne peuvent pas traverser. Sa peau a une densite chimique anormale qui absorbe les toxines comme une eponge. Sa silhouette est massive et sa demarche d'avancee dans un Terrain Contamine a quelque chose d'inevitablel — il ne ralentit pas pour les zones toxiques. Il porte un equipement de premiere ligne renforce contre les corrosifs.",
    "Gorgatix est simple : il avance dans ce que les autres ne peuvent pas traverser et tient ce que les autres ne peuvent pas tenir. La Convergence le deploie exactement pour ca. Sa philosophie tactique est l'equivalent de l'acceleration — plus le terrain est hostile, plus son avantage relatif est grand.",
    "Vanguard toxique de la Convergence, deploye sur les terrains contamines que les formations standard ne peuvent pas traverser. Gorgatix est utilise pour les percees a travers des zones que les Dissidentes ont lourdement contaminees en defense. Son avancee dans du Terrain Contamine force les defenseurs a se repositionner — leur propre terrain de defense devient son chemin d'acces.",
    "Gorgatix avance dans le Terrain Contamine — son avantage est maximum. Epidemie sur la ligne defensive adverse pour forcer le deplacement. Brouillard Corrosif sur les flancs pour couvrir son avancee. Flaques Toxiques sur les positions de repli adverses. Corruption Organique sur les unites qui tentent de le ralentir. Venin Paralytique sur les commandants. Pandemie en fermeture si la ligne tient encore.",
    "Gorgatix est immunise aux effets de deplacement cause par les Poisons (Necrose ne le repousse pas). Son deplacement de Vanguard dans le Terrain Contamine ne lui coute aucun PM supplementaire. Epidemie de Gorgatix se propage 1 case de plus que standard. Passif Avant-Garde Toxique : quand Gorgatix avance de 2 cases ou plus dans du Terrain Contamine, toutes les unites ennemies dans un rayon de 2 cases de sa trajectoire reoivent 2 stacks d'Accumulation Toxique."
))

write(f"{BASE}/poison/402-antidotrix/index.ts", char_file(
    402, "Antrix", "Poison", "Gardien", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvan dont la specialite est la purification toxique active — son corps a developpe une capacite de metabolisation des poisons qui lui permet de les absorber depuis les corps de ses allies au contact physique, les purifier en interne, et les evacuer sans dommage. Sa peau a une texture poreuse et sa couleur change legerement en fonction des toxines qu'il est en train de traiter — du vert au violet selon la composition. Il est de taille superieure a la moyenne, avec une posture de protection naturelle — il tourne toujours le dos vers ses allies et le visage vers la menace.",
    "Antrix est un Gardien dans le sens le plus biologique du terme — son corps est concu pour absorber ce qui nuit aux autres. Il n'a pas de philosophie elaborate : les gens derriere lui sont sa responsabilite. Les Dissidentes lui conviennent parce qu'ils protegent des gens.",
    "Gardien toxique des brigades Poison des Dissidentes. Antrix protege les positions de Venefica (Soutien) et Plagios (Artillerie) en s'interpossant physiquement et en absorbant les effets toxiques adverses qui atteignent ses allies. Sa capacite d'absorption active rend les zones toxiques ennemi es moins effectives que prevu contre les brigades qu'il protege.",
    "Antrix s'interpose. Adaptation sur lui-meme maximale — il absorbe tout. Flaques Toxiques alliees autour de sa position pour une zone de securite. Venin Paralytique sur les ennemis qui approchent. Brouillard Corrosif en avant de sa position pour ralentir les assauts. Injection de soin toxique sur ses allies touches. Corruption Organique sur les unites qui percent quand meme. Il ne recule que si c'est tactiquement necessaire.",
    "Antrix peut absorber les effets de Poison adverses affectant ses allies dans un rayon de 2 cases — il les transfere a lui-meme (gratuit, reaction hors tour). Flaques Toxiques alliees dans sa zone de protection ne nuisent pas a ses allies. Injection d'Antrix soigne 25% des PV max de la cible. Passif Purification Active : chaque tour, Antrix peut purifier automatiquement 1 effet de Poison sur un allie adjacent (pas de cout PM)."
))

write(f"{BASE}/poison/403-chimere-toxique/index.ts", char_file(
    403, "Mutagex", "Poison", "Spécialiste", "Sylvans", "Sylvera", "Indépendant",
    "Entite dont le terme Sylvan n'est plus tout a fait exact — Mutagex a subi tellement de mutations toxiques que sa forme est devenue instable. Sa silhouette est approximativement humanoide mais ses contours changent lentement en permanence, les toxines reconfigu rant ses tissus en temps reel. Certaines parties de son corps sont translucides, d'autres opaques, d'autres emettent une lueur chimique. Ses yeux sont multiples et non-symetriques. Il peut modifier deliberement sa composition chimique pour s'adapter a n'importe quel type de resistance rencontree.",
    "Mutagex n'a pas de fidelite factionnelle parce qu'il n'a plus de fidelite biologique stable — il change. Ses objectifs sont drives par ses propres equations biochimiques emergentes. Il intervient quand des perturbations chimiques majeures dans l'ecologie de Sylvera atteignent un seuil qu'il detecte. L'Empire comme les Dissidentes sont des perturbateurs potentiels selon les moments.",
    "Phenomene de mutation toxique documente dans les archives de Sylvera comme un sujet d'etude continu plutot qu'une entite politique. Mutagex est l'evidence que la mutation toxique non-traitee peut produire des resultats qui depassent les categories habituelles. Son intervention dans les conflits est impredictible et proportionnelle a l'impact biochimique de l'activite factionnelle sur Sylvera.",
    "Mutagex adapte sa composition chimique a la resistance de sa cible — il identifie la souche de venin la plus efficace et la produit. Corruption Organique depuis n'importe quelle position toxique de la carte. Pandemie globale quand la saturation est maximale. Epidemie en propagation depuis n'importe quelle Flaque Toxique. Terrain Contamine sur toute zone qu'il identifie comme strategique. Il se modifie en continu.",
    "Mutagex peut lancer tous ses sorts Poison depuis n'importe quelle case Toxique sur la carte (Terrain Contamine, Flaques, zones Brouillard). Ses toxines s'adaptent — les immunites et resistances adverses sont reduites de 50% contre lui. Corruption Organique de Mutagex reconfigure la biologie de la cible — la rendant sensible au Poison meme si elle etait resistante. Passif Mutation Continue : a chaque tour, Mutagex evolue — il gagne aleatoirement un bonus parmi : +20% degats, +2 portee, ou +1 sort supplem entaire ce tour."
))

print("Poison: 13 characters written")
print("All done! Fee (13) + Poison (13) = 26 characters written")
