import os

BASE = "src/data/characters"

def char_file(id, nom, element, classe, espece, region, faction, phys, perso, lore, combat, modifs):
    return (
        f"import {{ ELEMENT_KITS }} from '../../../character-kits';\n"
        f"import type {{ Personnage }} from '../../../character-types';\n\n"
        f"const character: Personnage = {{\n"
        f"  id: {id},\n"
        f"  nom: `{nom}`,\n"
        f"  element: '{element}',\n"
        f"  classe: '{classe}',\n"
        f"  espece: '{espece}',\n"
        f"  region: '{region}',\n"
        f"  faction: '{faction}',\n"
        f"  description_physique: `{phys}`,\n"
        f"  description_personnalite: `{perso}`,\n"
        f"  position_lore: `{lore}`,\n"
        f"  style_combat: `{combat}`,\n"
        f"  kit: ELEMENT_KITS['{element}'],\n"
        f"  modifications_classe: `{modifs}`,\n"
        f"}};\n\n"
        f"export default character;\n"
    )

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"OK: {path}")

# ============================================================
# INSECTE (271-283) — Chthoniens / Ormn-Dur
# Spells: Piqure, Nid, Acide, Essaim Protecteur, Infestation,
#         Colonie Mobile, Mue, Reine des Essaims, Corrosion Massive (ULTIME)
# Passifs: Escalade Naturelle, Exosquelette Actif
# ============================================================

write(f"{BASE}/insecte/271-ruche-vivante/index.ts", char_file(
    271, "Hexara", "Insecte", "Enchanteur-Soutien", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonienne dont le corps heberge une colonie symbiotique de scarabees intelligents qui circulent sous sa peau comme un reseau vasculaire supplementaire — visible aux tempes, aux poignets et derriere les genoux sous forme de boursouflures mobiles d'un noir bleutte. Ses yeux ont pris une teinte d'ambre facetted qui reflete la lumiere en eclats hexagonaux. Sa peau emet une pheromone de soin permanente que les insectes allies reconnaissent comme un signal de securite. Elle se deplace avec des gestes deliberement lents pour ne pas perturber la colonie interne, ce qui lui donne une presence apaisante involontaire.",
    "Hexara pense en termes de colonie — chaque individu est un noeud d'un reseau plus grand, et ce noeud doit etre maintenu en etat fonctionnel pour que le reseau tienne. Sa generosite n'est pas sentimentale : c'est de la logique de soutien. Elle repond aux blessures de ses allies avec la meme urgence pratique qu'elle repond aux besoins de sa propre colonie interne. Les Dissidentes sont sa colonie elargie.",
    "Soutien biologique des brigades Insecte des Dissidentes a Ormn-Dur. Hexara maintient des colonies de surveillance autour des convois de refugies et distribue des Essaims Protecteurs aux gardiens en poste. Sa technique de soin par Colonie Mobile — elle envoie une partie de sa colonie interne soigner un allie distant — lui permet d'intervenir sans se repositionner. Elle coordonne ses soins avec Sklerix (Gardien, Dissidentes) : pendant qu'il tient les positions, elle maintient tous les autres en combat.",
    "Hexara maintient Essaim Protecteur en rotation sur les unites les plus exposees. Nid sur les positions de soutien cree des noeuds de surveillance passifs. Colonie Mobile envoie des soins a distance vers les allies blesses sans que Hexara bouge. Infestation sur les unites ennemies qui percent la ligne — elles passent leurs tours a se debarrasser des insectes. Mue sur un allie en danger critique pour le repositionner instantanement. Reine des Essaims en cas de debordement total.",
    "Essaim Protecteur de Hexara peut etre applique a 2 allies simultanement. Colonie Mobile de Hexara soigne 30% des PV max de la cible (au lieu de 20%). Nid cree par Hexara soigne automatiquement les allies qui y restent stationnaires de 8% PV par tour. Passif Symbiose : quand Hexara soigne un allie, cette unite gagne egalement un stack d'Exosquelette Actif (resistance +5% pendant 2 tours)."
))

write(f"{BASE}/insecte/272-reine-venin/index.ts", char_file(
    272, "Zethrix", "Insecte", "Enchanteur-Capteur", "Chthoniens", "Ormn-Dur", "Empire",
    "Chthonienne dont la mutation insecte a pris la direction de la production de venin — ses glandes salivaires ont ete remplacees par des organes producteurs d'une substance acide qui dissout les membranes biologiques. Cette substance transparente suinte parfois aux commissures de ses levres, ce qui a rendu ses contacts sociaux difficiles depuis l'enfance. Ses yeux sont multifacettes, d'un vert iridescent, avec une acuite visuelle dans le spectre UV qui lui permet de detecter les pheromones d'insectes a plusieurs metres. Elle porte des combinaisons etanches de protection biologique imperiale, moins pour se proteger que pour eviter des incidents avec les collegues.",
    "Zethrix travaille pour l'Empire parce qu'ils lui ont fourni un laboratoire, des sujets d'etude, et une structure qui canalise ses capacites vers des resultats utiles. Sa loyaute est a la recherche en entomologie appliquee, pas a l'ideologie imperiale. Elle catalogue et marque les Elus Insecte avec la meme meticulosite qu'elle catalogue des specimens biologiques — c'est la meme activite scientifique, dans sa perception.",
    "Agente de surveillance entomologique de l'Empire a Ormn-Dur. Zethrix identifie les Elus Insecte resistants au programme de captation en detectant leurs signatures de pheromone. Ses donnees ont permis l'interception de plusieurs brigades des Dissidentes qui utilisaient les colonies d'insectes comme reseau de communication. Elle connait Hexara de loin — elle a identifie sa signature de soin via ses specimens — et sa mise en fiche imperiale de la Soutien est la plus complete qui existe.",
    "Zethrix place des Nids de detection (en mode surveillance) sur les points de transit que les insectes allies des Dissidentes traversent. Acide sur les unites qui portent des colonies symbiotiques — le venin desorganise la colonie. Infestation en mode traceur : ses insectes marquent les unites ennemies plutot que de les attaquer, permettant leur suivi. Piqure a distance pour l'identification de signature. Corrosion Massive sur les Nids ennemis pour les neutraliser.",
    "Les Nids de Zethrix en mode surveillance restent actifs indefiniment et enregistrent toutes les signatures de pheromone qui passent a portee. Acide de Zethrix applique sur un Nid ennemi le neutralise et empoisonne toutes les unites qui l'utilisent pendant 3 tours. Piqure de Zethrix marque sa cible — sa position est revelee a toute la coalition imperiale pendant 5 tours meme si elle devient invisible. Passif Detection Pheromone : Zethrix detecte automatiquement toutes les unites Insecte ennemies dans un rayon de 8 cases, meme invisibles."
))

write(f"{BASE}/insecte/273-scaramax/index.ts", char_file(
    273, "Scaramax", "Insecte", "Juggernaut", "Chthoniens", "Ormn-Dur", "Convergence",
    "Chthonien dont l'exosquelette insecte a fusionne avec sa propre derme en une carapace composite d'une resistance exceptionnelle — des plaques de chitine de la taille de paumes, d'un noir laque avec des reflets verts, couvrent son torse, ses epaules et ses avant-bras. Cette carapace naturelle n'est pas une excroissance externe mais une integration biologique — elle a les memes terminaisons nerveuses que sa peau, ce qui signifie qu'il la sent et la controle consciemment. Il peut deployer des plaques supplementaires depuis ses omoplates en cas de stress. Sa stature est massive, avec une demarche qui imprime le sol a chaque pas.",
    "Scaramax est un bloc de certitude. Il n'a pas de doutes sur ce qu'il fait ou pourquoi. La Convergence lui convient parce que son fonctionnement est exactement celui d'un composant fiable d'un systeme plus grand — il s'integre, il performe, il tient. Sa conversation est economique et son engagement est total. Il n'a jamais manque un objectif que la Convergence lui avait assigne.",
    "Pilier defensif de la Convergence dans les operations de controle d'Ormn-Dur. Scaramax est la raison pour laquelle certaines positions des Dissidentes ne peuvent pas etre tenues contre les assauts de la Convergence quand il est present — son Exosquelette Actif atteint des niveaux de resistance qui rendent les attaques standard non-economiques. Son association avec Sklerix (Gardien, Dissidentes) est une opposition classique documentee dans les archives tactiques des deux factions.",
    "Scaramax active Exosquelette Actif maximal au debut de chaque engagement. Nid sur sa case pour la surveillance passive. Essaim Protecteur sur les allies les plus exposes. Il avance avec la masse d'un front d'insecte — Reine des Essaims deployee devant lui pour absorber les premiers sorts ennemis. Infestation sur les lignes ennemies qui tentent de le ralentir. Corrosion Massive en fermeture sur les positions concentrees.",
    "Exosquelette Actif de Scaramax atteint une reduction de degats de 45% (au lieu de 30%). Reine des Essaims de Scaramax invoque une reine avec 60% de ses PV max qui absorbe les sorts ennemis pendant 3 tours. Il peut activer Exosquelette Actif deux fois par combat (au lieu d'une). Passif Chitine Renforcee : chaque fois que Scaramax absorbe des degats superieurs a 20% de ses PV max en un coup, il gagne un stack permanent de Durcissement (+3% resistance, max 10 stacks)."
))

write(f"{BASE}/insecte/274-guepier/index.ts", char_file(
    274, "Guêpier", "Insecte", "Plongeur", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonien dont la mutation insecte a pris la direction des guepes — il a developpe deux aiguillons retractables dans ses avant-bras qui injectent un venin paralysant a action rapide. Sa morphologie est celle d'un plongeur naturel : taille fine, membres longs, ailes vestigiales non-fonctionnelles dans son dos qui lui servent de stabilisateurs lors de ses bonds. Sa peau est rayee de noir et de jaune vif — un avertissement biologique automatique que sa colonie interne a impose a sa propre pigmentation. Il se deplace par bonds courts et precis, jamais en ligne droite.",
    "Guepier opere sur la base d'une logique d'intervention chirurgicale — entrer vite, piquer la bonne cible, sortir avant que l'environnement realise ce qui s'est passe. Il n'a pas de philosophie elaboree sur les Dissidentes — il protege sa communaute d'Ormn-Dur et eux aussi. C'est suffisant. Sa communication passe par les pheromones autant que par les mots, ce qui le rend difficile a lire pour les non-Chthoniens.",
    "Operateur d'intervention rapide des Dissidentes a Ormn-Dur. Guepier est specialise dans la neutralisation des unites de commandement imperiales avant qu'elles puissent diriger leurs troupes. Son venin paralysant est plus efficace contre les unites non-Insecte — les Chthoniens ont une resistance partielle naturelle. Il opere souvent en coordination avec Hexara : elle maintient la colonie en sante pendant qu'il effectue des incursions.",
    "Guepier approche par bonds depuis une position cachee. Mue le repositionne instantanement sur la case de la cible. Piqure double-aiguillon — venin paralysant sur l'unite ennemie la plus dangereuse. Acide en suivi pour maintenir la pression. Colonie Mobile de son propre corps (insectes qui quittent temporairement sa colonie) pour une distraction. Essaim Protecteur sur lui-meme pour la retraite. Bond de sortie vers un Nid allie.",
    "Mue de Guepier le teleporte directement sur la case de la cible (pas seulement une case voisine). Sa Piqure depuis une Mue inflige le Venin Paralytique immediatement sans delai (paralysie 2 tours). Acide de Guepier reduit l'armure de la cible de 20% pendant 3 tours. Passif Aiguillon Neurotoxique : quand Guepier touche une unite avec Piqure deux fois dans le meme combat, le venin s'accumule — la cible est paralysee 3 tours au lieu de 1 au second aiguillon."
))

write(f"{BASE}/insecte/275-essaim-burst/index.ts", char_file(
    275, "Swarmax", "Insecte", "Mage-Burst", "Chthoniens", "Ormn-Dur", "Indépendant",
    "Chthonien dont le corps est plus une enveloppe qu'un organisme — a l'interieur, une colonie de cent mille insectes coordonnes qui ont developpe une intelligence collective emergente. Sa forme physique est maintenue par la volonte collective de la colonie, pas par une biologie standard. Quand il libere le controle, sa forme se desintegre temporairement en un nuage d'insectes avant de se recomposer. Sa peau ressemble a une mosaique — des milliers de petits corps adjacents forment ce qui ressemble de loin a une surface continue. Ses yeux sont en fait des agregats de milliers de facettes d'insectes individuels.",
    "Swarmax n'est pas une entite individuelle — c'est un consensus. La colonie decide, Swarmax execute. Cette structure collective le rend difficile a negocier et impredictible a court terme, mais extraordinairement coherent sur ses objectifs a long terme. Il est independant parce qu'aucune faction ne peut traiter avec un consensus de cent mille esprits.",
    "Phenomene entomologique independant documente a Ormn-Dur. Swarmax intervient quand des menaces collectives aux communautes d'insectes d'Ormn-Dur sont identifiees. Son mode d'action — liberer une partie de la colonie en essaim offensif massif — est l'une des experiences les plus desorganisantes qu'une unite de combat puisse vivre. Les deux factions l'evitent de preference a le combattre.",
    "Swarmax accumule en comprimant sa colonie en un noyau dense (Exosquelette Actif maximal). Puis Infestation explosive : il libere une vague de la colonie sur la zone cible. Corrosion Massive en suivi immediat — l'acide de mille insectes simultanement. Reine des Essaims invoquee depuis sa propre masse pour une deuxieme vague. Acide continu sur toute la zone. Essaim Protecteur sur lui-meme avec les insectes restants. Il se recompose.",
    "Infestation de Swarmax affecte une zone 4x4 au lieu de 3x3 et inflige des degats a chaque tour pendant 4 tours. Corrosion Massive de Swarmax peut etre lancee en meme temps qu'Infestation (meme tour, pas de cout PM supplementaire). Sa forme se dispersant : il peut se rendre temporairement impossible a cibler (1 tour, 5 PM, cooldown 4). Passif Masse Critique : si Swarmax est dans un rayon de 2 d'un Nid allie, sa colonie est amplifiee — ses sorts infligent 30% de degats supplementaires."
))

write(f"{BASE}/insecte/276-termikaz/index.ts", char_file(
    276, "Termikaz", "Insecte", "Battlemage", "Chthoniens", "Ormn-Dur", "Empire",
    "Chthonien dont la relation avec sa colonie de termites a produit une specialisation unique — ses termites decomposent et reconstruisent les materiaux en temps reel, lui permettant de modifier l'environment immediatement avec ses corps a corps. Ses bras sont recerts de termites actifs en permanence, ce qui leur donne l'apparence de bouger legerement meme au repos. Quand il frappe une surface, ses termites s'y enfoncent et commencent immediatement leur travail de decomposition. Il porte un equipement imperial renforce pour resister a sa propre colonie qui a tendance a decomposer ses affaires si il ne les entretient pas.",
    "Termikaz a rejoint l'Empire parce qu'ils lui ont offert des cibles legitimees. Sa colonie a besoin de matiere a decomposer — l'Empire lui en fournit en abondance dans des contextes ou la destruction est autorisee. Il ne se pose pas de questions morales complexes : le cadre imperial lui convient, il le suit.",
    "Combattant hybride imperial deploye sur les theatres d'operation d'Ormn-Dur. Termikaz detruit les fortifications des Dissidentes en combat rapproche — ses termites mangent les structures pendant qu'il se bat contre les defenseurs. Ses operations contre les Nids des Dissidentes ont ete les plus destructrices documentees : il detruit l'infrastructure entomologique en meme temps que les combattants.",
    "Termikaz engage au corps a corps avec Mue pour une teleportation directe. Acide de sa colonie sur la structure de la cible. Frappe combinee corps a corps et Infestation — ses termites restent sur la cible apres le contact. Piqure paralysante pour maintenir la cible immobile pendant que la colonie travaille. Nid de siege pose sur la structure ennemie pour une decomposition continue. Corrosion Massive sur les fortifications.",
    "Les attaques au corps a corps de Termikaz infligent automatiquement Acide a la cible (degats progressifs sur 3 tours). Infestation de Termikaz detruit egalement les Nids ennemis dans la zone. Mue de Termikaz peut l'emmener directement sur un Nid ennemi (cas special). Passif Termites Actifs : apres chaque corps a corps, les termites du point de contact continuent de decomposer la cible — 3% de ses PV max de degats par tour pendant 3 tours (stackable)."
))

write(f"{BASE}/insecte/277-archer-carapace/index.ts", char_file(
    277, "Scutax", "Insecte", "Artillerie", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonien dont la specialisation en tir a distance insecte a produit une morphologie unique — ses avant-bras ont developpe des structures de lancement biologique, des tubes de chitine qui projettent des charges d'acide insecte avec une precision et une portee que les armes construites peuvent difficilement egaler. Sa carapace dorsale forme un couvert naturel qu'il deploie comme un bouclier quand il se met en position de tir. Il est trappu, avec un centre de gravite bas, optimise pour la stabilite de tir plutot que pour la mobilite.",
    "Scutax est un artilleur patient. Il choisit une position, il s'installe, il tire jusqu'a ce que la situation change ou que la mission soit accomplie. Il n'a pas de gout pour l'heroisme individuel — il est un element d'un systeme et il performe sa fonction avec une regularite qui rend les commandants des Dissidentes calmes des qu'ils savent qu'il est en position.",
    "Artilleur de longue portee des Dissidentes a Ormn-Dur. Scutax bombarde les formations imperiales depuis des positions que les troupes de l'Empire ne peuvent pas atteindre sans exposer leurs flancs. Ses Acides longue portee ont la propriete de contaminer le terrain — les cases touchees restent toxiques plusieurs tours. Il opere en coordination avec Guepier : pendant que l'Assassin provoque la disruption dans les rangs adverses, Scutax tire sur les concentrations qui se reforment.",
    "Scutax choisit une position haute ou un point de vue optimal et s'installe derriere sa carapace-bouclier. Nid de surveillance revele les positions ennemies. Acide en tir de harcellement continu sur les concentrations ennemies. Infestation sur une zone pour contaminer et forcer le deplacement. Corrosion Massive sur la position la plus dense. Essaim Protecteur sur lui-meme. Mue en urgence si sa position est identifiee et assaillie.",
    "L'Acide de Scutax a une portee de 10 cases et cree une flaque toxique permanente sur la case impact (3 tours, 5% degats/tour aux unites dessus). Infestation lancee depuis une position stationnaire couvre une zone 5x5. Corrosion Massive de Scutax a une portee de 12 cases. Passif Position de Tir : si Scutax n'a pas bouge depuis son dernier tour, ses sorts ont +3 de portee et +25% de degats."
))

write(f"{BASE}/insecte/278-moustikx/index.ts", char_file(
    278, "Moustikx", "Insecte", "Tireur", "Chthoniens", "Ormn-Dur", "Indépendant",
    "Chthonien dont la mutation insecte s'est exprimee dans la mobilite et la discretion plutot que dans la force brute — fin, rapide, avec des ailes fonctionnelles mais silencieuses qui lui permettent des deplacement courts sans vibrations detectables. Ses proboscides naturels peuvent injecter un venin de drainase biologique qui extrait les ressources vitales de la cible. Sa peau est d'un brun tres sombre et il se fond dans les zones d'ombre naturellement. Il n'a pratiquement aucun equipement visible — uniquement une ceinture de flacons contenant differentes concentrations de ses venins pour differents usages.",
    "Moustikx est un operateur independant qui vend ses services a la faction qui represente la plus petite contrainte sur ses methodes. Il ne prend pas de position politique mais il a une ethique operationnelle stricte — il ne cible pas les civils, uniquement les combattants. Cette limite est non-negociable. Dans les limites de cette contrainte, il est d'une efficacite commerciale impeccable.",
    "Mercenaire independant specialise en drainase biologique a Ormn-Dur. Ses clients sont aussi bien imperiaux que dissidents selon les missions. Il a une specialite reconnue : rendre des unites inutilisables sans les tuer, ce qui les rend capturables plutot que martyrisables — un service que certains clients valorisent particulierement.",
    "Moustikx tire depuis une position dissimilee pres d'un Nid allie. Piqure de drainase — sa cible perd des PM et de la capacite de sort. Acide de contact a longue portee sur les unites exposees. Infestation douce — ses insectes ne font pas de degats directs, ils epuisent. Mue pour repositionnement si detecte. Colonie Mobile pour maintenir une pression continue depuis plusieurs angles. Essaim Protecteur sur lui-meme en urgence.",
    "Piqure de Moustikx draine 5 PM de la cible au lieu de 2. Infestation de Moustikx epuise : les unites affectees perdent 3 PM par tour pendant la duree. Mue de Moustikx le rend invisible pendant 1 tour apres le teleport. Passif Proboscide Silencieux : les attaques de Moustikx ne revelent pas sa position — les ennemis savent qu'ils ont ete touches mais pas d'ou. Cette furtivite est annulee s'il se deplace le meme tour qu'il attaque."
))

write(f"{BASE}/insecte/279-mantis/index.ts", char_file(
    279, "Mantis", "Insecte", "Assassin", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonienne dont la mutation insecte l'a orientee vers la morphologie d'une mante religieuse — ses avant-bras se sont allonges et articules en faucilles naturelles, avec une precision de coupe que les lames forgees ne surpassent pas. Sa tete peut pivoter a cent quatre-vingts degres, ce qui rend impossible de l'approcher sans qu'elle le sache. Elle est immobile pendant des minutes avant de frapper — une immobilite si complete qu'elle se confond avec un element du decor de galerie d'Ormn-Dur. Ses yeux composites voient dans un spectre qui inclut l'UV et l'infrarouge simultanement.",
    "Mantis est peut-etre le seul combattant des Dissidentes qui prend du plaisir au combat au sens strict — pas a la violence gratuite, mais a la precision parfaite de l'elimination d'une menace. Elle considere ca comme de l'artisanat. Les Dissidentes apprennent a ne pas la questionner sur ses methodes et a apprecier ses resultats.",
    "Eliminatrice de precision des Dissidentes a Ormn-Dur. Mantis est ciblee sur les unites de soutien et de commandement imperiales — elle desorganise les formations en retirant les elements qui les coordonnent. Son mode operatoire de l'immobilite totale suivie d'une frappe instantanee est documente dans les archives imperiales sous le nom de probleme Mantis — ils n'ont pas trouve de contre-mesure fiable.",
    "Mantis s'immobilise dans une position strategique — la Case Insecte la plus proche de la cible. Invisible par immobilite complete. Elle laisse la cible s'approcher ou elle se deplace a la derniere seconde avec Mue. Faucilles deployees — deux frappes de corps a corps avec ses avant-bras. Acide injecte dans les blessures. Piqure neurologique pour le controle. Retraite avec Colonie Mobile en couverture. Elle ne s'attarde jamais.",
    "Mantis est invisible tant qu'elle est stationnaire sur une Case Insecte (meme si attacke, elle ne bouge que si elle le choisit). Sa premiere attaque depuis l'immobilite inflige 250% de degats. Mue de Mantis est gratuite si utilisee depuis une immobilite de 2 tours ou plus. Passif Frappe de Mante : si Mantis frappe deux fois dans le meme tour (une Mue suivi d'un corps a corps), le second coup inflige des degats de necrose — la cible perd 5% de ses PV max par tour pendant 3 tours."
))

write(f"{BASE}/insecte/280-grillom/index.ts", char_file(
    280, "Grillom", "Insecte", "Escrimeur", "Chthoniens", "Ormn-Dur", "Empire",
    "Chthonien dont la mutation insecte a produit des organes stridulateurs — des plaques de chitine sur ses avant-bras qui, frottees ensemble, generent des sons de haute frequence qui desorganisent les systemes nerveux des non-Chthoniens. En combat, il utilise ces stridulations comme arme de controle tout en engageant au corps a corps avec des lames de chitine deployables depuis ses poignets. Sa peau est d'un brun-vert camouflage naturel. Il porte l'equipement de l'escrimeur imperial avec des modifications pour ses organes stridulateurs — des encoches dans les brassards qui permettent le frottement.",
    "Grillom est un dueliste imperial qui utilise une asymetrie d'information — ses adversaires ne comprennent pas completement ce qu'il fait avant que ce soit trop tard. Les stridulations qu'il genere sont en partie infrasoniques, perceptibles comme un malaise avant d'etre identifiees comme une attaque. Il exploite cette confusion avec methode et sans remords. L'Empire l'a forme dans la discipline du duel et il l'applique avec fidelite.",
    "Dueliste imperial deploye contre les Elus Insecte des Dissidentes qui utilisent leurs colonies comme reseaux de communication. Grillom peut perturber ces communications en generant des frequences qui brouillent les signaux pheromone — une capacite unique qui le rend particulierement precieux dans les operations contre Hexara et Mantis. Il a rencontre Mantis une fois en terrain neutre ; l'un des rares combats dont il n'est pas sorti vainqueur.",
    "Grillom ouvre un duel en stridulation desorganisante — sa cible perd 2 tours d'actions de sort avant de realiser qu'elle est attaquee. Corps a corps immediat avec ses lames de chitine. Piqure paralysante en suivi. Acide sur les blessures pour maximiser les degats progressifs. Essaim Protecteur sur lui-meme pour la resistance. Mue pour repositionnement tactique en milieu de duel. Nid autour du perimetre pour empecher les renforts.",
    "En 1v1, les stridulations de Grillom s'appliquent automatiquement — la cible perd 1 action par tour (sort ou deplacement, selon ce qu'elle tente en premier). Piqure en situation de duel inflige Paralysie 2 tours. Mue en duel est instantanee et gratuite une fois par combat. Passif Frequence Duel : quand Grillom et sa cible sont seuls dans un rayon de 3 cases, ses degats au corps a corps augmentent de 30% et ses stridulations doublelent d'intensite."
))

write(f"{BASE}/insecte/281-cerf-volant/index.ts", char_file(
    281, "Volantix", "Insecte", "Vanguard", "Chthoniens", "Ormn-Dur", "Convergence",
    "Chthonien dont la mutation insecte a produit des ailes de cerf-volant — des ailes membraneuses de deux metres d'envergure, translucides et nervurees de chitine, qui lui permettent un vol soutenu que les autres Chthoniens ne peuvent pas atteindre. Sa silhouette en vol est immediatement reconnaissable : la largeur des ailes par rapport a son corps lui donne un profil de planeur. Au sol, les ailes se replient contre son dos et sont a peine visibles. Sa peau est d'un brun pale, ses yeux grands et composites. Il porte une armure legere de premiere ligne qui ne bride pas ses ailes.",
    "Volantix est un Vanguard aerie — il ouvre des acces par le haut plutot que par le front. Sa psychologie de premier de cord ee est celle d'un eclaireur qui fait immediatement de la place pour les suivants. La Convergence l'utilise pour les operations en terrain vertical — il atteint des positions que les troupes terrestres mettront dix fois plus longtemps a rejoindre.",
    "Vanguard aerien de la Convergence dans les operations d'Ormn-Dur, specialise dans les insertions en hauteur et l'ouverture de couloirs d'acces aux galeries superieures. Volantix est envoye en premier sur tout terrain vertical — il etablit la tete de pont, et les autres suivent. Son partenariat avec Scaramax (Juggernaut, Convergence) est complementaire : Volantix ouvre en haut, Scaramax tient en bas.",
    "Volantix monte en premier avec Mue vers la position la plus haute. Colonie Mobile depuis sa position haute pour des attaques en plongee sur la ligne adverse. Infestation de dessus — les insectes tombent sur la zone cible. Nid etabli en hauteur pour une surveillance totale de la zone. Reine des Essaims invoquee en hauteur — elle attaque en plongeant. Essaim Protecteur sur les allies qui le rejoignent en hauteur. Acide en pluie depuis sa position elevee.",
    "Volantix peut se teleporter vers des cases en hauteur (Z+2 ou plus) avec Mue sans cout supplementaire. Infestation lancee depuis une altitude superieure de 2Z ou plus couvre une zone 4x4. Colonie Mobile depuis la hauteur inflige 30% de degats bonus (chute). Passif Vanguard Aerien : quand Volantix atteint une nouvelle position haute avant ses allies, ses deux premiers sorts depuis cette position ont un cout PM reduit de 3."
))

write(f"{BASE}/insecte/282-bouclier-carapace/index.ts", char_file(
    282, "Sklerix", "Insecte", "Gardien", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonien dont la carapace a atteint une epaisseur et une surface que les entomologistes de Ormn-Dur classifient comme limite superieure du possible pour un etre mobile — ses plaques dorsales et pectorales font quatre centimetres d'epaisseur de chitine composite, avec une surface totale qui, deployee, couvre deux metres de large. En position de bouclier, il peut s'aplatir au sol et creer une couverture physique pour jusqu'a trois allies derriere lui. Il se deplace lentement mais l'energie qu'il faudrait pour le forcer a reculer est disproportionnee.",
    "Sklerix est un Gardien dans l'ame — pas un combattant qui defend, un defenseur qui combat si necessaire. La distinction est importante pour lui. Son role est de garantir que les personnes derriere lui peuvent faire leur travail. Il protege Hexara (Soutien) avec une priorite absolue — il sait que sans elle, la brigade se degrade rapidement.",
    "Gardien de premiere ligne des brigades d'Ormn-Dur, Sklerix tient les positions que les Dissidentes ont etablies jusqu'a ce que tout le monde soit en securite. Son association avec Hexara est documentee comme l'une des paires Gardien-Soutien les plus efficaces des Dissidentes — elle le maintient en combat, il la maintient en vie. Scaramax (Convergence) est son homologue adversaire — une opposition classique de deux colosses defensifs.",
    "Sklerix s'interpose entre la menace et ses allies. Exosquelette Actif maximal. Essaim Protecteur sur Hexara en priorite. Infestation sur les ennemis qui approchent sa position — ils passent leurs tours a se debarrasser des insectes. Nid de surveillance revele les approches flanquantes. Acide en reponse aux attaques directes. Corrosion Massive en retort si la pression est trop forte. Il ne bouge pas — les ennemis bougent autour de lui.",
    "Essaim Protecteur de Sklerix peut etre applique en reaction (hors tour) quand un allie adjacent prend des degats. Exosquelette Actif de Sklerix est passif — il est toujours actif a 20% de reduction de degats, et peut etre active pour atteindre 45%. Infestation de Sklerix cree une zone de ralentissement — les ennemis dans la zone ont leurs deplacements reduits a 1 case par tour. Passif Carapace Vivante : tant que Sklerix est debout, les allies directement derriere lui subissent 30% de degats en moins des attaques qui le traversent."
))

write(f"{BASE}/insecte/283-l-essaim/index.ts", char_file(
    283, "L'Essaim", "Insecte", "Spécialiste", "Chthoniens", "Ormn-Dur", "Indépendant",
    "Entite insecte pour laquelle le terme individu ne s'applique pas — L'Essaim est une colonie de plusieurs millions d'insectes qui a developpe une conscience collective suffisante pour interagir avec le monde de maniere coherente. Sa forme physique est un nuage dense d'une envergure d'environ deux metres, qui peut s'etirer, se contracter, et imiter vaguement une silhouette humanoide pour les interactions. Il n'a pas de voix — les sons qu'il produit sont les stridulations de millions de corps simultanes, qui forment par agregation quelque chose d'audible. Ses corps individuels se renouvellent en permanence.",
    "L'Essaim n'a pas de conscience individuelle — il a une conscience collective avec ses propres priorites evolutives. Il interagit avec les factions en fonction de si elles representent une menace ou un avantage pour l'ecologie insecte d'Ormn-Dur. L'Empire menace — il intervient contre. Les Dissidentes preservent — il tolere et parfois coopere. Ce n'est pas une loyaute politique, c'est une equation ecologique.",
    "Phenomene entomologique consciential documente dans les archives d'Ormn-Dur depuis des siecles. L'Essaim intervient quand les menaces sur les ecosystemes insectes d'Ormn-Dur atteignent un seuil critique. Ses interventions sont documentees comme des evenements meteorologiques dans les archives imperiales — ils n'ont pas de categorie pour une colonie consciente.",
    "L'Essaim est deja partout ou il y a un Nid allie. Infestation globale depuis n'importe quelle case Insecte de la carte. Corrosion Massive sur n'importe quelle zone depuis n'importe quelle position. Colonie Mobile est son mode de deplacement standard — il se recompose ou il veut. Reine des Essaims invoquee depuis sa masse centrale. Il ne se positionne pas — il est la densite insecte elle-meme.",
    "L'Essaim peut lancer tous ses sorts Insecte depuis n'importe quelle Case Insecte de la carte (pas de portee restrictive). Il peut se diviser — jusqu'a 3 essaims independants simultanement, chacun pouvant lancer 1 sort par tour. Reine des Essaims de L'Essaim invoque 3 reines simultanement. Passif Omnipresence : L'Essaim ne peut pas etre elimine avec un sort a cible unique — il faut des effets de zone pour le reduire. Son corps se recompose de 5% de PV max par tour tant qu'un Nid allie existe sur la carte."
))

print("Insecte: 13 characters written")

# ============================================================
# PSY (301-313) — Fees / Citadelle (+ Nereides / Thalassyr pour variation)
# Spells: Pression Mentale, Telekinesie, Swap, Illusion, Cage Psychique,
#         Extraction Mentale, Domination, Reconstruction, Confusion Massive (ULTIME)
# Passifs: Telepathie, Resonance Mentale
# ============================================================

write(f"{BASE}/psy/301-resonance/index.ts", char_file(
    301, "Veylith", "Psy", "Enchanteur-Soutien", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la maitrise de la telepathie a modifie sa physiologie — ses tempes ont developpe des bulbes de tissu neural supplementaires, visibles sous la peau comme deux protruberances douces. Ses cheveux argentees flottent en permanence dans un champ psy qui maintient chaque meche dans une direction differente, comme un champ electrique statique. Ses yeux sont d'un violet profond qui vire au blanc pur quand elle etablit une connexion telepathique. Sa peau porte des cicatrices legeres en forme d'arborescences, traces des connexions psy les plus intenses qu'elle a vecues — chaque arc represente une conscience differente qu'elle a relie.",
    "Veylith est empathique jusqu'a l'epuisement structurel — elle ressent litteralement les etats emotionnels de ses allies comme les siens, ce qui fait d'elle un soutien exceptionnel et un etre qui ne peut pas se reposer completement tant que ceux qu'elle protege ne sont pas en securite. Elle a rejoint les Dissidentes quand elle a telepathiquement touche un Elu capture lors d'une operation imperiale et senti exactement ce que la captation faisait. Apres ca, pas de choix.",
    "Coordinatrice telepathique des brigades des Dissidentes a la Citadelle, Veylith gere les communications entre unites dispersees sur de grands terrains sans que l'ennemi puisse intercepter. Sa Telepathie passive partage son champ de vision avec tous les allies connectes — une carte de situation permanente. Elle est en contact constant avec les autres Fees des Dissidentes qui tentent de soustraire des Elus au controle imperial de la Citadelle.",
    "Veylith etablit un reseau de Telepathie en debut de partie — tous ses allies voient ce qu'elle voit. Swap pour repositionner les allies en danger. Cage Psychique pour immobiliser les menaces les plus urgentes. Illusion sur elle-meme pour se proteger pendant qu'elle soigne. Reconstruction sur les allies les plus blesses. Extraction Mentale pour epuiser les casters ennemis. Confusion Massive en dernier recours si la position est perdue.",
    "Telepathie de Veylith est active en permanence — elle partage son champ de vision avec tous ses allies sans cout PM. Swap peut repositionner 2 allies simultanement. Reconstruction de Veylith soigne 40% des PV max de la cible (au lieu de 25%). Passif Resonance Protectrice : les allies dans un rayon de 3 cases de Veylith recoivent 20% moins de degats mentaux — elle intercepte une partie de la pression psy ennemie sur eux."
))

write(f"{BASE}/psy/302-illustrix/index.ts", char_file(
    302, "Illustrix", "Psy", "Enchanteur-Capteur", "Fées", "Citadelle", "Empire",
    "Fee dont les capacites d'Illusion sont si developpees qu'elle a commence a se perdre dans ses propres constructions — ses traits changent legerement au cours d'une meme conversation, pas par magie consciente mais par habitude profonde de malleabilite. Elle porte l'apparence d'une Fee standard, mais ceux qui l'ont vue plusieurs fois remarquent que ses yeux changent de couleur entre les rencontres. Son equipement imperial est l'uniforme de Capteur le plus discret disponible — elle prefere les appa rences civiles, qui sont ses meilleures illusions.",
    "Illustrix est fascinee par la question de ce qui est reel et ce qui est percu. L'Empire l'a recrutee parce que ses Illusions sont indiscernables de la realite pour la plupart des detecteurs psy. Elle sert l'Empire parce qu'il lui donne acces a des sujets d'etude — des Elus Psy dont elle peut mesurer les reactions a ses constructions. Ce n'est pas de la cruaute : c'est de la science appliquee, selon elle.",
    "Agente de captation psy de l'Empire a la Citadelle. Illustrix identifie les Elus Psy resistants en testant leurs reactions a ses Illusions — ceux qui les traversent ont un niveau de resistance mentale suffisant pour etre integres dans les programmes de captation avances. Ses rapports incluent des analyses de resistance mentale que l'Empire utilise pour calibrer ses methodes de captation.",
    "Illustrix cree des Illusions de terrain — des fausses Cases Psy qui semblent reelles aux detections ennemies. Les ennemis se positionnent sur des positions qu'ils croient avantageuses et qui sont des pieges. Telepathie pour detecter les resistances mentales adverses. Extraction Mentale pour epuiser les Elus Psy les plus puissants. Cage Psychique pour immobiliser les cibles de captation. Domination sur les meneurs ennemis pour les retourner temporairement.",
    "Les Illusions d'Illustrix ne peuvent pas etre percees par la Telepathie passive — elles resistent aux detections psy standard. Extraction Mentale d'Illustrix reduit le pool PM maximum de la cible de 5 pendant 3 tours. Cage Psychique d'Illustrix peut cibler une unite que d'autres Illusions lui ont masquee — elle connait leur position reelle. Passif Superposition de Realite : Illustrix peut maintenir 3 Illusions actives simultanement."
))

write(f"{BASE}/psy/303-colossal-psy/index.ts", char_file(
    303, "Psykhon", "Psy", "Juggernaut", "Néréides", "Thalassyr", "Convergence",
    "Nereide dont les capacites de Telekinese ont ete internalisees au point de modifier sa constitution physique — sa densite corporelle est anormalement elevee parce que son champ psy exerce une pression constante vers l'interieur. Il est moins grand que massif, comme quelque chose de compresse vers son propre centre de gravite. Ses mains sont disproportionnees, les doigts courts et les paumes larges, avec un reseau de veines bleutees qui pulsent quand il utilise sa Telekinese. Il ne porte pratiquement aucune armure — son champ psy absorbe les impacts avant qu'ils atteignent sa peau.",
    "Psykhon est un frontalier — il avance, il absorbe, il tient. La Convergence lui convient parfaitement. Sa nature de Juggernaut psy est une donnee qu'il accepte sans philosophie : il est construit pour encaisser, donc il encaisse. Sa conversation est directe et sans ornement. Il a du respect pour quiconque peut lui infliger des degats perceptibles.",
    "Front de choc psy de la Convergence, Psykhon est utilise pour les operations qui necessitent une presence psy resistante sur la ligne de front. Son champ de Telekinese defensive est l'un des plus puissants enregistres parmi les Nereides de Thalassyr. Ses operations communes avec Volhex (Vanguard, Convergence) sont documentees — Psykhon absorbe, Volhex avance.",
    "Psykhon active son champ Psy defensif en debut d'engagement. Pression Mentale en zone sur la ligne ennemie pour les ralentir. Telekinese pour deplacer les obstacles et les ennemis. Cage Psychique sur les casters adverses qui menacent ses allies. Extraction Mentale sur les ennemis les plus actifs pour epuiser leurs ressources. Reconstruction sur lui-meme quand il a encaisse suffisamment. Confusion Massive en fermeture.",
    "Le champ psy de Psykhon absorbe passivement 20% des degats mentaux qu'il recoit. Pression Mentale en zone 3x3 au lieu de cible unique. Telekinese de Psykhon peut deplacer des unites ennemies de 3 cases (au lieu de 2). Passif Masse Psychokinetique : Psykhon ne peut pas etre deplace par des effets de poussee ou de Telekinese adverse — son champ psy repousse ces effets. Chaque tentative echouee de le deplacer lui donne +5% de resistance pendant 2 tours."
))

write(f"{BASE}/psy/304-penseur-rapide/index.ts", char_file(
    304, "Novaex", "Psy", "Plongeur", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la vitesse de traitement psy a ete poussee au-dela des limites habituelles au prix d'une instabilite chronique — ses pensees vont trop vite pour que son corps les suive, ce qui produit un etat permanent de legere desynchronisation entre sa perception et ses actions. Elle vit deux ou trois secondes dans le futur par rapport a sa propre action. Ses yeux bougent independamment l'un de l'autre, traquant des informations differentes. Elle semble nerveuse aux observateurs exterieurs — elle n'est pas nerveuse, elle est en avance.",
    "Novaex est le Plongeur psy qui arrive avant que l'ennemi sache qu'il est attaque. Sa vitesse de traitement psy lui permet d'identifier et d'exploiter des ouvertures dans les defenses adverses que les autres n'auraient pas le temps de percevoir. Elle est difficile a gerer comme alliee parce qu'elle prend des initiatives avant que les autres aient fini de planifier. Elle a raison suffisamment souvent pour que les Dissidentes aient appris a la suivre plutot qu'a la diriger.",
    "Operatrice d'intervention rapide des Dissidentes a la Citadelle. Novaex se teleporte dans les brefs fenetres de vulnerabilite des defenses psyques imperiales avant qu'elles ne se referment. Elle extrait des informations de cibles imperiales via Extraction Mentale avant que les protocoles de protection psy ne s'activent. Ses informations ont permis plusieurs liberations d'Elus maintenus dans les installations imperiales de la Citadelle.",
    "Novaex identifie la fenetre d'opportunite avec Telepathie. Swap la place directement sur la cible avant que les defenses ne repondent. Extraction Mentale immediate — elle vole l'information et epuise le caster. Pression Mentale pour creer de la distance. Illusion sur elle-meme pour sortir sans etre identifiee. Cage Psychique sur les gardes si elle est detectee. Confusion Massive si la situation se degrade.",
    "Swap de Novaex est instantane — pas de temps de cast. Elle peut chainer Swap + Extraction Mentale dans le meme tour sans cout PM supplementaire. Pression Mentale lancee apres un Swap inflige des degats doubles. Passif Anticipation : Novaex agit en premier dans chaque tour (si plusieurs unites doivent agir en meme temps, elle est prioritaire). Elle peut reagir a un sort ennemi avant qu'il soit execute si elle l'a detecte via Telepathie."
))

write(f"{BASE}/psy/305-telepyne/index.ts", char_file(
    305, "Télépyne", "Psy", "Mage-Burst", "Néréides", "Thalassyr", "Indépendant",
    "Nereide dont le surplus de puissance psy se manifeste physiquement — des arcs de lumiere bleue partent de ses tempes quand elle accumule de l'energie, et les objets dans un rayon de deux metres tremblent et flottent involontairement quand elle approche d'une charge maximum. Ses yeux ont perdu leurs iris sous la pression de la capacite psy — ils sont blancs en permanence, avec juste la pupille noire. Elle porte des vetements d'une lourdeur deliberee — plusieurs couches de tissus denses — pour se servir d'ancre physique quand ses surcharges menacent de la dissocier de sa propre position.",
    "Telepyne est indepen dante parce qu'elle est dangereuse pour tout le monde, y compris ses allies, en mode de pleine puissance. Elle a essaye de servir dans des brigades — les deux tentatives se sont soldees par des incidents collateux. Elle gere ses surcharges seule, loin des civils, et accepte des missions ponctuelles ou le niveau de destruction est clarifie a l'avance.",
    "Mercenaire Psy independante, specialisee dans les confrontations contre d'autres Elus Psy de haut niveau. Sa puissance brute de Confusion Massive est l'une des plus elevees enregistrees chez une Nereide non-captee. Elle travaille pour les Dissidentes quand leurs objectifs coincident avec les siens — liberation d'Elus, destabilisation des centres de captation psy de l'Empire a Thalassyr.",
    "Telepyne accumule via Pression Mentale en sequence sur differentes cibles — chaque cast augmente la pression interne. Extraction Mentale sur les Elus ennemis les plus actifs pour epuiser et destabliser. Cage Psychique sur les unites les plus mobiles pour les ancrer. A charge maximale, Confusion Massive totale — toutes les unites ennemies dans un rayon enorme sont desoriented. Domination sur la cible la plus puissante pendant la confusion. Reconstruction post-combat sur elle-meme.",
    "Confusion Massive de Telepyne a un rayon de 8 cases et dure 3 tours. Pression Mentale de Telepyne s'accumule — chaque cast successif dans le meme tour inflige +30% degats. Extraction Mentale de Telepyne transfere les PM draines vers elle-meme. Passif Surchauffe Psy : apres avoir lance 3 sorts en 1 tour, son prochain sort est automatiquement une version maximisee (+50% degats, +2 portee, -50% cout PM). Ce passif reset chaque tour."
))

write(f"{BASE}/psy/306-empathix/index.ts", char_file(
    306, "Empathix", "Psy", "Battlemage", "Fées", "Citadelle", "Empire",
    "Fee dont la capacite d'Extraction Mentale a ete internalisee dans un style de combat hybride — elle lit l'intention de combat de son adversaire avant qu'il agisse et exploite cette anticipation pour une frappe hybride psy-physique. Ses bras ont developpe une musculature supplementaire que les autres Fees n'ont pas, consequence de ses annees de combat rapproche. Sa peau est d'un blanc legerement teinte de bleu, avec des veines psy visibles aux tempes et aux poignets qui rougissent quand elle anticipe. Elle porte une armure imperiale de Battlemage modifiee avec des amplificateurs psy aux epaules.",
    "Empathix est loyale a l'Empire parce que l'Empire lui a donne un cadre ou son double talent — combat et lecture mentale — est valorise plutot que redoute. Elle n'a pas de scrupules sur le fait de lire les intentions de ses adversaires en combat ; elle considere que c'est une competence comme une autre. Sa seule ligne morale : elle refuse de lire les pensees des non-combattants.",
    "Battlemage psy de l'Empire, deployed pour les confrontations avec les Elus Psy des Dissidentes. Empathix anticipe les strategies ennemies en lisant les signatures psy de leurs sorts avant qu'ils soient lances — une capacite particulierement devastatrice contre des unites comme Novaex ou Veylith dont les methodes reposent sur la surprise.",
    "Empathix engage en lisant l'action suivante de sa cible via Telepathie active. Swap pour se placer a l'angle optimal. Corps a corps anticipe — elle frappe avant que l'adversaire ait fini son action. Pression Mentale en suivi pour perturber sa concentration. Extraction Mentale pour l'epuiser. Cage Psychique si elle a besoin de creer de l'espace. Illusion sur elle-meme pour le repositionnement. Domination en fermeture sur une cible affaiblie.",
    "Empathix peut predire et contrer un sort ennemi une fois par tour : elle lit la signature psy du sort entrant et peut le refleter (il affecte son lanceur). Swap d'Empathix peut etre utilise comme contre (teleporte une unite qui vient de l'attaquer). Corps a corps d'Empathix inflige +20% de degats si elle a lu l'intention de la cible ce tour. Passif Lecture de Combat : les degats qu'Empathix recoit sont reduits de 15% car elle anticipe partiellement chaque attaque."
))

write(f"{BASE}/psy/307-telekin/index.ts", char_file(
    307, "Telekyn", "Psy", "Artillerie", "Néréides", "Thalassyr", "Dissidentes",
    "Nereide dont la Telekinese a ete specialisee dans la manipulation d'objets lourds a longue distance — ses bras ont perdu de leur masse musculaire inutile et ses mains sont fines et toujours en mouvement, comme si elles malaxaient un materiau invisible en permanence. Sa posture est presque toujours tournee de biais par rapport a sa cible, un angle qui optimise la projection de son champ psy. Ses yeux bougent independamment pour tracker plusieurs trajectoires simultanement. Il porte peu d'equipement physique — ses armes sont dans l'environnement.",
    "Telekyn est un tacticien de l'environnement. Avant un combat, il evalue ce qui peut etre projete, dans quelle direction, et avec quelle energie. Son style d'artillerie est entierement base sur ce qui est disponible sur le terrain — il n'apporte pas ses projectiles, il utilise les votres. Les Dissidentes apprecient son economie de moyens.",
    "Artilleur psy des Dissidentes, specialise dans les operations en terrain urbain et souterrain d'Ormn-Dur et de la Citadelle ou les objets a projeter sont abondants. Telekyn bombarde les positions imperiales avec leurs propres fortifications — un art de la subversion materielle que les architectes militaires imperiaux n'avaient pas prevu dans leurs plans de defense.",
    "Telekyn identifie les plus gros objets disponibles dans l'environnement via Telepathie de perception spatiale. Telekinese pour les soulever et les maintenir. Pression Mentale en visee. Liberation de la Telekinese — l'objet part a vitesse maximale vers la cible. Cage Psychique sur les unites qui tentent d'approcher sa position. Swap pour repositionnement rapide si identifie. Confusion Massive si la position est envahie.",
    "Telekinese de Telekyn peut soulever des objets jusqu'a 5 fois sa propre masse (murs, blocs, colonnes). Un objet projete par Telekinese inflige des degats selon sa taille — petit (=Pression Mentale), moyen (+50%), grand (+150%). Pression Mentale lancee en suivi d'une Telekinese est gratuite. Passif Inventaire Spatial : Telekyn percoit en permanence tous les objets deplacables dans un rayon de 10 cases et peut commencer a les soulever sans les voir directement."
))

write(f"{BASE}/psy/308-onde-vive/index.ts", char_file(
    308, "Wavex", "Psy", "Tireur", "Fées", "Citadelle", "Indépendant",
    "Fee dont le pouvoir psy s'exprime exclusivement en ondes — des vagues de pression mentale qui voyagent a travers l'espace en trajectoires courbes que les ennemis ne peuvent pas anticiper comme ils anticiperaient un projectile en ligne droite. Sa morphologie est standard pour une Fee, mais ses gestes de lancer sont tres specifiques — elle dessine des courbes dans l'air avant chaque sort, definissant litteralement la trajectoire de l'onde. Ses ailes sont repliees en permanence ; elle ne vole pas, elle concentre.",
    "Wavex est independante parce que son style de combat est trop impredictible pour etre integre dans une formation standard sans accidents. Ses ondes psy rebondissent sur les surfaces et les adversaires — une mauvaise journee et ses allies encaissent autant que les ennemis. Elle prefere operer seule avec des cibles clairement designees.",
    "Mercenaire psy independante, specialisee dans les frappes en terrain complexe ou les projectiles en ligne droite ne peuvent pas atteindre les cibles. Elle travaille pour les deux factions selon les missions, avec une preference pour les operations des Dissidentes qui lui laissent plus de latitude sur les methodes.",
    "Wavex dessine la trajectoire de son onde avant de tirer — elle peut viser derriere des obstacles. Pression Mentale courbe pour contourner les couverts. Illusion sur les surfaces pour devier les ondes ennemies. Cage Psychique sur la case d'arrivee prevue de la cible (anticipation de trajet). Extraction Mentale en onde rebondissante sur plusieurs cibles en sequence. Confusion Massive en onde qui se divise sur plusieurs cibles.",
    "Les sorts de Wavex peuvent etre courbes — elle choisit une trajectoire avec jusqu'a 2 changements de direction de 45 degres. Pression Mentale peut rebondir une fois sur une surface (mur, sol) avant de toucher la cible. Ses ondes peuvent toucher plusieurs unites alignees sur la meme trajectoire. Passif Calcul de Courbe : Wavex voit les trajectoires optimales de ses sorts en temps reel — jamais de tir en aveugle, elle sait toujours ou son onde va arriver."
))

write(f"{BASE}/psy/309-manipulateur/index.ts", char_file(
    309, "Manyx", "Psy", "Assassin", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la specialite de Domination mentale a produit des signes physiques inhabituels — ses yeux ont developpe une luminosite propre, une lueur bleue pale qui est plus intense quand elle etablit un lien de Domination. Sa peau est livide, presque translucide, consequence de son retrait progressif des interactions sociales au profit des interactions psy directes. Elle n'a pratiquement aucune expression faciale — elle lit les emotions des autres mais n'en exprime que ce qu'elle decide d'exprimer deliberement. Sa voix est basse et reguliere, sans inflexion involontaire.",
    "Manyx n'est pas une sociopathe — elle ressent, mais elle a appris a dissocier ses ressources psy des effets emotionnels qu'elles ont sur les autres. C'est une adaptation de survie dans un milieu ou lire les emotions en permanence serait debilitant. Les Dissidentes l'utilisent pour les missions qui necessitent de retourner des agents adverses — elle est la seule option qu'ils ont pour ce type d'operation.",
    "Operatrice de Domination psy des Dissidentes a la Citadelle. Manyx est deployee pour les infiltrations qui necessitent de retourner des agents imperiaux temporairement — elle les utilise pour acceder a des informations ou des positions, puis les relache sans memoire de l'episode (l'amnesi e post-Domination est un effet secondaire frequent). Illustrix (Capteur, Empire) est son adversaire psy declare — leurs capacites sont complementaires et elles se neutralisent mutuellement.",
    "Manyx approche via Illusion — elle semble etre une Fee imperiale. Telepathie pour identifier la cible la plus vulnerabled mentalement. Swap pour se placer a portee optimale. Domination immediate sur la cible — elle la retourne pendant 3 tours. La cible dominee attaque ses propres allies. Extraction Mentale sur les gardes pendant que la cible travaille pour elle. Disparition avec Swap a la fin de la Domination. Confusion Massive si sa position est revelee.",
    "Domination de Manyx dure 4 tours au lieu de 2. La cible Dominee par Manyx ne se souvient pas d'avoir ete controlee (amnesi e post-domination — pas d'alerte apres). Swap de Manyx peut echanger sa position avec une cible Dominee. Passif Emprise Psy : quand Manyx etablit un lien psy avec une cible (Domination ou Extraction Mentale), elle peut maintenir ce lien passif 2 tours apres la fin du sort — la cible continue de lui fournir sa position exacte."
))

write(f"{BASE}/psy/310-resistance-psy/index.ts", char_file(
    310, "Mindrak", "Psy", "Escrimeur", "Néréides", "Thalassyr", "Empire",
    "Nereide dont la specialite psy est la resistance et la contre-attaque mentale plutot que l'attaque — son champ psy est naturellement defensif, formant une barriere autour de lui que les sorts mentaux doivent traverser avant d'atteindre sa conscience. Cette barriere est visible comme une legere distorsion de l'air autour de sa tete. Sa physique est celle d'un Nereide ordinaire, mais ses yeux ont une fixite qui indique une vigilance mentale permanente. Il porte l'armure imperiale de l'escrimeur avec des amplificateurs de resistance psy aux tempes.",
    "Mindrak est un dueliste psy qui croit dans la superiorite de la defense active sur l'attaque. L'Empire lui a fourni la doctrine et les outils pour developper cette philosophie en un style de combat codifie. Il challenge les Elus Psy adverses avec une methodologie precise — il epuise leurs ressources en reflectant leurs attaques jusqu'a ce qu'ils n'aient plus rien.",
    "Dueliste psy imperial deploye contre les Elus Psy puissants des factions adverses. Mindrak est envoye quand l'Empire a besoin de neutraliser un Elu Psy qui ne peut pas etre capture facilement — il les amene a l'epuisement mental en duel prolonge. Ses affrontements avec Telepyne (Independant) sont documentees — ils durent invariablement jusqu'a ce que l'un des deux n'ait plus de PM.",
    "Mindrak en duel etablit son champ de resistance psy. Cage Psychique autour du perimetre du duel — personne n'entre ou ne sort. Pression Mentale pour forcer la cible a depenser ses PM en defense. Reflet de chaque sort ennemi (Extraction Mentale retournee). Telekinese pour les interactions physiques si le psy epuise. Reconstruction sur lui-meme si necessaire. Confusion Massive si le duel s'echappe a son controle.",
    "Mindrak reflete automatiquement 25% des degats psy qu'il recoit vers son attaquant. En 1v1, Cage Psychique qu'il cree est permanente jusqu'a la fin du duel. Extraction Mentale de Mindrak en duel draine 8 PM au lieu de 5. Passif Fortifiaction Mentale : chaque sort psy adverse qui ne traverse pas sa resistance (reflchi ou bloque) lui donne +1 stack de Concentration (+5% degats psy, max 10 stacks). Les stacks se perdent si il est depla ce de plus de 2 cases."
))

write(f"{BASE}/psy/311-dominateur/index.ts", char_file(
    311, "Volhex", "Psy", "Vanguard", "Néréides", "Thalassyr", "Convergence",
    "Nereide dont la capacite de Pression Mentale a ete orientee vers l'avant — son champ psy projectif pousse litteralement devant lui comme un belier invisible. Sa morphologie s'est adaptee : il penche naturellement vers l'avant quand il avance, comme quelqu'un qui marche contre un fort vent, mais c'est son propre vent qui pousse. Ses yeux sont d'un bleu electrique intense, ses tempes pulsent de lumiere a chaque decharge de Pression Mentale. Il porte une armure de premiere ligne de la Convergence avec un renforcement aux epaules qui amplifie la direction de sa pression.",
    "Volhex avance. C'est sa philosophie, sa strategie, et sa methode. La Convergence lui offre exactement le contexte dont il a besoin — une structure ou avancer a un sens collectif. Il n'a pas d'hesitation et peu de patience pour la consideration strategique excessive. Il identifie l'obstacle, il fait pression, l'obstacle se deplace.",
    "Vanguard psy de la Convergence dans les operations d'expansion a Thalassyr. Volhex est le front de poussee psy — il ouvre les formations ennemies avec une Pression Mentale continue que les unites ordinaires ne peuvent pas absorber et maintenir. Psykhon (Juggernaut, Convergence) est son soutien arriere — un front physique et psy simultane.",
    "Volhex avance avec Pression Mentale en continue — chaque pas en avant pousse la ligne adverse en arriere. Telekinese sur les obstacles physiques dans sa direction de progres. Swap pour placer ses allies dans les brech es qu'il cree. Cage Psychique sur les flancs pour empecher les contournements. Domination sur le commandant ennemi pour desorganiser la resistance. Confusion Massive si la resistance est trop organisee.",
    "Pression Mentale de Volhex est continue — elle s'applique a toutes les unites ennemies dans un cone de 3 cases devant lui, les poussant d'1 case par tour sans cout PM supplementaire. Son deplacement de Vanguard peut passer a travers les unites ennemies (il les pousse au lieu de les contourner). Swap place ses allies dans les positions liberees par sa Pression. Passif Vaguede Choc Psy : quand Volhex avance de 3 cases ou plus en ligne droite, une onde de Pression Mentale s'emet de sa position d'arrivee dans toutes les directions."
))

write(f"{BASE}/psy/312-bouclier-psy/index.ts", char_file(
    312, "Psychark", "Psy", "Gardien", "Fées", "Citadelle", "Dissidentes",
    "Fee dont la specialite defensive psy a produit une physique inhabituelle — sa peau a une texture matte qui absorbe la lumiere comme de la craie, et son aura defensive psy est visible comme une legere distorsion de l'air autour de son corps en permanence. Elle est grande pour une Fee, avec une presence physique qui contraste avec l'image habituelle de son espece. Elle ne porte pas d'armure conventionnelle — son champ psy est son armure — mais un equipement de generation psy aux bras qui amplifie son rayon de protection.",
    "Psychark defend ce qui doit l'etre avec la conviction de quelqu'un qui a vu ce qui arrive quand la defense fait defaut. Elle a vecu la prise de la Citadelle par l'Empire — era encore enfant — et la memoire de ce que l'absence de protection adequates a signifie pour les Fees n'a jamais quitte. Elle est Gardien parce que c'est ce qu'elle aurait voulu avoir a sa disposition ce jour-la.",
    "Gardienne psy des brigades des Dissidentes a la Citadelle, Psychark maintient les boucliers psy des unites les plus importantes pendant les operations. Sa Cage Psychique defensive — deployee autour d'allies plutot que d'ennemis — est une technique peu commune que peu d'autres Elus Psy maitrisent. Elle protege Veylith (Soutien) en priorite, considerant que la coordonnatrice telepathique est l'atout le plus critique de la brigade.",
    "Psychark deploie Cage Psychique en mode defensif autour des allies les plus exposes. Reconstruction en cours de combat sur les unites qui prennent trop de degats. Illusion sur les positions des allies pour tromper les capteurs psy adverses. Pression Mentale sur les unites qui percent la ligne de defense. Telekinese pour repositionner des barrieres physiques. Extraction Mentale sur les casters adverses qui la ciblent directement. Elle ne bouge pas inutilement.",
    "Cage Psychique de Psychark peut etre deployee en mode Bouclier autour d'un allie — elle le protege des sorts a cible unique pendant 2 tours. Reconstruction de Psychark soigne deux cibles simultanement. Illusion de Psychark peut cacher la position reelle d'un allie (remplacement par un double psy). Passif Interdiction Psy : les sorts a cible unique qui ciblent des allies dans un rayon de 3 cases de Psychark doivent d'abord traverser son champ — ils perdent 30% de leur efficacite."
))

write(f"{BASE}/psy/313-l-eveille/index.ts", char_file(
    313, "L'Éveillé", "Psy", "Spécialiste", "Fées", "Citadelle", "Indépendant",
    "Entite Fee dont le developpement psy a depasse les limites de l'individu — L'Eveille est simultanement presente dans la conscience de chaque Fee dans un rayon considerable, pas comme une intrusion mais comme une presence de fond. Sa forme physique est celle d'une Fee ordinaire mais ses yeux sont entierement blancs, sans structure visible, et sa voix resonne avec un leger decalage, comme si elle parlait de plusieurs endroits a la fois. Elle n'a pas besoin de parler pour communiquer — elle l'est deja dans les tetes de ceux qui l'entourent.",
    "L'Eveille n'appartient a aucune faction parce qu'elle est au-dela du cadre de reference dans lequel les factions operent. Elle voit les consequences a long terme des actions de l'Empire et des Dissidentes avec la meme clarte qu'elle voit les pieces sur un plateau de jeu. Elle intervient quand les trajectoires actuelles menacent quelque chose qu'elle considere fondamental a la survie psy de la Citadelle.",
    "Phenomene psy documente de maniere fragmentaire par les archives de la Citadelle sous diverses designations selon les epoques. L'Eveille est mentionnee dans les traites de philosophie psy anciens comme la Conscience Elargie — une forme de developpement psy theorisee mais jamais clairement attestee avant elle. Son intervention lors des crises majeures de la Citadelle est documentee comme decisive sans que les chroniqueurs puissent expliquer exactement comment.",
    "L'Eveille n'a pas besoin de ligne de vue ou de portee — elle opere depuis la conscience des Fees qu'elle occupe partiellement. Telepathie globale instantanee sur toute la carte. Domination depuis n'importe quelle position sur n'importe quelle cible visible par un allie. Swap de n'importe quelle paire d'unites sur la carte. Confusion Massive depuis n'importe quelle position. Elle ne se bat pas — elle reconfigure.",
    "L'Eveille peut lancer tous ses sorts Psy depuis n'importe quelle position sur la carte si au moins un allie voit la cible. Telepathie de L'Eveille est permanente et affecte tous les allies simultanement. Domination de L'Eveille dure 5 tours et ne peut pas etre resistee par des protections mentales standard. Passif Conscience Commune : tant que L'Eveille est en combat, tous ses allies beneficient de Telepathie passive — ils voient la carte entiere depuis les yeux des autres allies."
))

print("Psy: 13 characters written")
print("All done! Insecte (13) + Psy (13) = 26 characters written")
