import os

BASE = "src/data/characters"

def char_file(id, nom, element, classe, espece, region, faction, phys, perso, lore, combat, modifs):
    return (
        f"import {{ ELEMENT_KITS }} from '../../../character-kits';\n"
        f"import type {{ Personnage }} from '../../../character-types';\n\n"
        f"const character: Personnage = {{\n"
        f"  id: {id},\n"
        f"  nom: `{nom}`,\n"
        f"  element: '{element}',\n"
        f"  classe: '{classe}',\n"
        f"  espece: '{espece}',\n"
        f"  region: '{region}',\n"
        f"  faction: '{faction}',\n"
        f"  description_physique: `{phys}`,\n"
        f"  description_personnalite: `{perso}`,\n"
        f"  position_lore: `{lore}`,\n"
        f"  style_combat: `{combat}`,\n"
        f"  kit: ELEMENT_KITS['{element}'],\n"
        f"  modifications_classe: `{modifs}`,\n"
        f"}};\n\n"
        f"export default character;\n"
    )

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"OK: {path}")

# ============================================================
# VENT (211-223) — Aerides / Asterciel
# Spells: Rafale, Propulsion, Vortex, Case Aerienne, Ascension,
#         Cyclone, Courant Dirige, Bourrasque Verticale, Couloir de Vent, ULTIME
# Passifs: Legerete, Courant Ascendant
# ============================================================

write(f"{BASE}/vent/211-brise-ame/index.ts", char_file(
    211, "Aelyx", "Vent", "Enchanteur-Soutien", "Aérides", "Asterciel", "Dissidentes",
    "Aeride dont les ailes ont perdu leur pigmentation suite a une surcharge de manipulation du courant atmospherique — elles sont maintenant translucides, comme du verre fele, et laissent voir la structure osseuse par transparence. Sa silhouette est fine et ses mouvements sont hesitants au sol, mais dans les airs il est d'une grace qui tranche avec sa fragilite apparente. Ses cheveux ont ete convertis en filaments conducteurs qui captent les variations de pression et lui permettent de sentir les courants a plusieurs kilometres. Il porte des habits legers de fibre minerale tresses pour resister aux vents violents qu'il genere pour ses allies.",
    "Aelyx est un amplificateur — il n'a aucun interet pour ce qu'il peut faire seul, uniquement pour ce qu'il permet aux autres de faire. Cette psychologie de soutien est authentique, pas feinte : il ressent une satisfaction profonde quand un allie atteint une position impossible grace a sa Propulsion. Les Dissidentes lui offrent exactement le contexte dont il a besoin — des allies qui ont besoin de mobilite dans des terrains verticaux complexes.",
    "Coordinateur de mobilite des brigades Vent des Dissidentes a Asterciel, Aelyx gere les insertions verticales que les troupes a pied ne peuvent pas realiser. Dans les operations de liberation des Elus Aerides captes par l'Empire dans les structures eleves d'Asterciel, il est le premier qui cree les conditions d'approche. Son association avec Aeryn (Gardien, Dissidentes) est documentee : Aelyx ouvre les routes d'approche, Aeryn tient les positions une fois atteintes.",
    "Aelyx lance Propulsion sur ses allies pour les envoyer en position haute sans cout PM de deplacement pour eux. Courant Dirige entre deux positions alliees cree une autoroute aerienne que tout le monde peut emprunter. Case Aerienne sous les pieds d'allies en danger les sort instantanement des zones de corps a corps. Vortex defensif autour d'une position alliee repousse les assaillants. Ascension de soi-meme pour surveiller et coordonner depuis les hauteurs. Bourrasque Verticale si une colonne ennemie approche.",
    "Propulsion de Aelyx peut cibler 2 allies simultanement. Courant Dirige qu'il cree peut etre emprunte par tous les allies sans cout PM (au lieu de cout reduit). Case Aerienne creee par Aelyx dure 5 tours au lieu de 3. Passif Vent Porteur : quand un allie utilise un deplacement aerien dans un rayon de 4 cases de Aelyx, ce deplacement a +2 de distance bonus."
))

write(f"{BASE}/vent/212-tempestine/index.ts", char_file(
    212, "Tempestine", "Vent", "Enchanteur-Capteur", "Aérides", "Asterciel", "Empire",
    "Aeride dont l'element de Vent a pris une forme interne inhabituelle — elle ne genere pas de vent visible, mais des infra-sons que les corps sentent avant que l'esprit les identifie. Sa presence cree une anxiete diffuse chez les non-Aerides, une impression que l'air manque. Physiquement, elle est de taille standard pour son espece, avec des ailes d'un noir de jais qui absorbent la lumiere plutot que de la refleter, et des yeux d'un gris argente qui semblent evaluer en permanence tout ce qu'ils voient. Elle porte l'equipement de surveillance atmospherique de l'Empire — des capteurs de pression qui enregistrent tout deplacement aerien dans un rayon de quinze cases.",
    "Tempestine est une analyste d'abord, une capteur ensuite. Elle s'est jointe a l'Empire parce que son programme de cartographie des flux de Vent dans Asterciel correspondait exactement a ce qu'elle voulait faire de sa vie. Que ce programme serve aussi a localiser des Elus qui n'ont pas volontairement rejoint les registres imperiaux... c'est une efficacite supplementaire qu'elle note sans s'y attarder. Sa loyaute est a la precision des donnees.",
    "Agente de surveillance atmospherique de l'Empire, Tempestine cartographie les flux de Vent utilises par les Elus Aerides des Dissidentes pour leurs deplacements. Ses donnees ont permis l'interception de plusieurs brigades mobiles en vol — elle peut identifier une signature de Vent individuelle comme d'autres identifient une empreinte digitale. Aelyx la connait de reputation et change systematiquement ses Courants Diriges apres chaque operation dont elle pourrait avoir connaissance.",
    "Tempestine place des capteurs de Vortex passifs (Vortex miniature) sur les couloirs de transit vent que les allies de l'Empire surveillent. Quand un ennemi traverse, elle declenche Rafale pour le projeter hors de sa trajectoire et reveale sa position a la coalition. Cyclone cree une zone d'exclusion aerienne. Bourrasque Verticale projette des unites ennemies en bas de leurs positions sureleves. Courant Dirige detourne les projectiles adverses.",
    "Vortex de Tempestine place en surveillance passive ne depense pas de PM — il s'active quand une unite Vent ennemie le traverse. Rafale de Tempestine peut etre declenchee en reaction (hors tour) quand un ennemi utilise un sort de deplacement dans un rayon de 6. Cyclone de Tempestine dure 5 tours et detecte toutes les unites qui le traversent, meme invisibles. Passif Infra-Sons : les unites ennemies dans un rayon de 3 cases de Tempestine ont -15% de precision sur leurs sorts."
))

write(f"{BASE}/vent/213-vortex-massif/index.ts", char_file(
    213, "Gorwind", "Vent", "Juggernaut", "Aérides", "Asterciel", "Convergence",
    "Aeride dont la stature est exceptionnelle pour une espece naturellement fine — il fait deux metres pour des ailes de quatre metres d'envergure, avec une masse musculaire qui aurait du etre incompatible avec le vol mais qui le rend capable de generer des vents d'une puissance que les Aerides ordinaires ne peuvent pas atteindre. Sa peau est d'un brun-roux bronze, ses yeux sont d'un jaune lumineux. Il porte une armure adaptee aux combats en altitude — plates of composite aerien qui ne brisent pas les ailes. Son vol est lourd et puissant, pas gracieux : il ressemble a une tempete qui avance.",
    "Gorwind est un bloc d'air. Il occupe l'espace, il prend la pression, il avance. La Convergence lui va bien parce qu'il pense en termes de masse collective — il n'est pas le plus intelligent de son groupe, mais il est le plus solide. Sa conversation est directe jusqu'a la brutalite, sans malice. Il a du respect pour quiconque tient sa position sous ses vents.",
    "Pilier des brigades terrestres (et aeriennes) de la Convergence dans les operations de controle du territoire d'Asterciel. Gorwind est envoye pour maintenir des corridors contre lesquels les troupes imperiales ne peuvent pas avancer — ses Vortex de maintien sont des murs d'air que les formations serrees ne peuvent pas traverser. Il a coopere avec Korryn (Electrique, Convergence) sur des operations de liberation de sites de captation — Korryn electrifie pendant que Gorwind neutralise les tentatives de fuite aerienne.",
    "Gorwind cree son Vortex au centre de la zone d'acces ennemi — un mur d'air rotatif que personne ne peut traverser. Cyclone sur les flancs. Il avance dans le vent qu'il genere, immunise aux effets de ses propres sorts. Bourrasque Verticale projette les ennemis qui tentent de passer par les hauteurs. Propulsion de lui-meme cree un impact d'atterrissage qui genere une Rafale radiale. Couloir de Vent derriere lui pour permettre a ses allies d'avancer dans son sillage.",
    "Gorwind est immunise aux effets de projection et aux dommages de ses propres sorts Vent. Vortex cree par Gorwind a un rayon de 4 cases au lieu de 2 et dure 6 tours. Son atterrissage depuis Z+2 ou plus genere automatiquement une Rafale radiale sur toutes les cases adjacentes. Passif Masse Atmospherique : les ennemis dans un rayon de 2 cases de Gorwind ont leurs couts de deplacement augmentes de 2 PM (la pression d'air autour de lui est physiquement resitante)."
))

write(f"{BASE}/vent/214-rafale/index.ts", char_file(
    214, "Rafal", "Vent", "Plongeur", "Aérides", "Asterciel", "Dissidentes",
    "Aeride dont le corps a ete optimise par des annees de vols en pique pour une seule chose — la vitesse de descente. Ses ailes sont repliables en lames, ses os sont creux meme pour un Aeride, et sa peau a developpe une couche de micro-plumes conductrices qui reduisent la resistance de l'air a presque zero. Ses yeux sont proteges par une membrane nictitante qui s'active automatiquement au-dela d'une certaine vitesse. Il n'a aucune musculature defensive notable — tout est concu pour l'attaque en pique. Il cicatrise vite, ce dont il a besoin.",
    "Rafal pense en termes de moments uniques. Sa fenetre d'attaque est breve — quelques secondes de contact apres une descente a vitesse maximale, puis retrait. Ce mode de fonctionnement l'a rendu impatient avec tout ce qui necessite de la duree. Il rejoint les Dissidentes mission par mission, pas par ideologie : ils lui donnent des cibles precises et le laissent les atteindre a sa facon.",
    "Operateur de frappe rapide des Dissidentes, Rafal intervient dans les situations qui necessitent un contact-eclair avec une cible avant que l'environnement adverse ne permette une riposte. Ses descentes en pique depuis les altitudes d'Asterciel atteignent des vitesses qui rendent le suivi visuel impossible. Gorwind cree des corridors de vent dans lesquels Rafal accelere avant le pique — ensemble ils ont developpe une combinaison que les tacticiens imperiaux ont documente sans trouver de contre-mesure fiable.",
    "Rafal prend de l'altitude via Ascension ou Case Aerienne, puis plonge en pique sur la cible. L'impact a vitesse maximale est amplifie par Propulsion de soi-meme. Bourrasque Verticale sur la case au moment de l'impact projette la cible et les adjacents. Il utilise Rafale pour s'eloigner avant que les ripostes arrivent. Courant Dirige prepare la route de sortie avant l'approche. Case Aerienne en sortie le met hors de portee au sol.",
    "La vitesse de Rafal en pique inflige des degats de choc equivalents a 50% de ses degats d'attaque de base a toutes les unites sur la case d'atterrissage. Propulsion utilisee sur lui-meme double sa prochaine distance de deplacement. Bourrasque Verticale utilisee pendant un pique couvre une zone 3x3. Passif Pique Supersonique : si Rafal se deplace de 5 cases ou plus en ligne droite avant une attaque, cette attaque inflige 100% de degats bonus et ignore 25% de l'armure."
))

write(f"{BASE}/vent/215-tornade/index.ts", char_file(
    215, "Velyn", "Vent", "Mage-Burst", "Aérides", "Asterciel", "Indépendant",
    "Aeride dont la relation avec le Vent a depasse le stade du controle pour atteindre la fusion — son corps genere en permanence une rotation d'air qui fait flotter ses cheveux et ses vetements dans tous les sens, independamment de l'air ambiant. Ses yeux sont entierement blancs, la pupille absorbee dans une iris dilatee par des annees de fixation sur les flux atmospheriques. Sa peau est couverte de micro-laceratures paralleles laissees par des vents qu'elle a genera trop pres d'elle-meme. Elle porte des vetements en spirale — des bandes de tissu enroulees qui s'accommodent de sa rotation constante.",
    "Velyn est une force elementaire avec un probleme de precision. Elle peut generer des bourrasques d'une puissance devastatrice mais le controle fin la frustre — elle est trop au-dela des limites du confort pour maintenir des effets delicats. Elle s'est mise independante parce qu'aucune faction ne peut la loger sans que les structures ne vibrent et parce qu'elle cause des degats collateraux dont les autres preferent ne pas etre responsables.",
    "Mercenaire elementaire du Vent a Asterciel, Velyn est engagee pour les situations ou la puissance brute est l'objectif et les dommages collateraux sont acceptes. Ses Cyclones sont les plus puissants enregistres chez un Aeride de sa generation, et son Couloir de Vent peut aspirer des formations entieres. Elle a travaille pour l'Empire une fois — ils l'ont licenciee quand elle a Vortex leur propre garnison dans sa cible. Les Dissidentes la contactent quand ils ont besoin de demolir rapidement sans plan d'extraction elabore.",
    "Velyn accumule en generant plusieurs Cases Aeriennes en rotation autour de sa position — chaque Case Aerienne ajoute a la pression atmospherique ambiante. Puis Cyclone maximise la puissance accumulee dans une zone cible. Vortex maintient l'ennemi dans la zone de degats. Bourrasque Verticale projette ce qui a survie. Couloir de Vent final aspire les renforts ennemis dans la zone de degats en cours. Elle n'a pas de phase defensive.",
    "Cyclone de Velyn inflige des degats a chaque unite dans son rayon a chaque tour (pas seulement a l'entree). Vortex de Velyn a un rayon de 4 cases et aucune unite ne peut en sortir sans un sort de deplacement actif. Couloir de Vent de Velyn aspire toutes les unites sur son chemin plutot que seulement de les deplacer. Passif Oeil du Cyclone : Velyn est immunisee a ses propres Cyclones et Vortex — elle peut etre dans son propre oeil sans prendre de degats."
))

write(f"{BASE}/vent/216-cyclonyx/index.ts", char_file(
    216, "Cyclonyx", "Vent", "Battlemage", "Aérides", "Asterciel", "Empire",
    "Aeride dont le style de combat a fusionne attaque elementaire et engagement physique dans une discipline que l'Academie imperiale d'Asterciel nomme Tourbillon Arme. Ses ailes sont renforcees de lames de metal aux bords, qu'il utilise comme armes de corps a corps tout en generant des effets de Vent. Sa peau est d'un gris-bleu metallique peu commun chez les Aerides, consequence d'une integration de materiaux conducteurs dans sa derme. Il porte une combinaison de combat imperial integrant des buses directionnelles dans les manches qui amplifient et dirigent ses sorts de Vent.",
    "Cyclonyx est un technicien du combat combine — il pense chaque engagement comme une partition ou les coups physiques et les sorts elementaires s'alternent en rythme calcule. L'Empire l'a forme dans la discipline du Battlemage et il en a embrasse la philosophie : la puissance est dans la combinaison, pas dans l'extremite. Il admire la structure imperiale precisement parce qu'elle produit des combattants avec des systemes coerents.",
    "Combattant de ligne de l'Empire deploye sur les theatres d'operation d'Asterciel. Cyclonyx est utilise pour les confrontations avec les Elus Vent des Dissidentes — il est l'un des rares combattants imperiaux capable de suivre les Plongeurs aeriens. Ses rapports d'operation sont une reference dans les archives militaires de l'Empire pour les tactiques d'engagement contre les elements Vent mobiles.",
    "Cyclonyx alterne corps a corps et sorts en sequence calculee. Rafale eloigne d'abord l'ennemi, puis Ascension le rejoint en hauteur, puis frappe aux lames d'ailes, puis Bourrasque Verticale le projette vers le bas, puis Propulsion de lui-meme pour descendre dans le meme mouvement. Vortex autour de la cible isole le duel. Case Aerienne sous lui maintient la superiorite verticale. Cyclone en fermeture si plusieurs ennemis sont impliques.",
    "Les sorts Vent de Cyclonyx ont une portee additionnelle de 2 quand il est en altitude (Z+1 ou plus). Son corps a corps depuis une position aerienne inflige 30% de degats bonus. Bourrasque Verticale utilisee immediatement apres un coup au corps a corps est instantanee (pas de temps de cast). Passif Tourbillon Arme : chaque sort Vent qu'il lance dans le meme tour qu'une attaque de corps a corps donne +15% de degats a la prochaine attaque physique (stackable 3 fois)."
))

write(f"{BASE}/vent/217-ouragan/index.ts", char_file(
    217, "Ouragan", "Vent", "Artillerie", "Aérides", "Asterciel", "Dissidentes",
    "Aeride dont les ailes ont ete partiellement detruites par un accident de surcharge Vent et reconstrruites par les medecins des Dissidentes avec des extensions mecaniques — un cadre de metal leger qui reproduit la forme alaire mais pas la texture biologique. Ces extensions mecaniques contiennent des compresseurs qui lui permettent de generer des rafales dirigees d'une puissance superieure a ses ailes naturelles, mais il ne peut plus voler a proprement parler — il peut planer brievement, pas plus. En compensation, sa stabilite au sol pour les tirs longue portee est exceptionnelle.",
    "Ouragan n'a pas de colere contre l'Empire pour son accident — c'etait une erreur de sa propre part dans un entrainement. Sa colere est plus diffuse et plus reelle : le systeme qui force des Aerides a s'entrainer sans securite adequate jusqu'a ce que des accidents arrivent. Les Dissidentes l'ont soigne et ne lui ont rien demande en retour, ce qui a etabli une loyaute qu'il ne saurait pas autrement formuler.",
    "Artilleur de longue portee des Dissidentes, Ouragan bombarde les positions imperiales fixees a Asterciel avec des bourrasques dirigees qui contournent les formations rocheuses grace a leur nature aerienne — un projectile Vent peut suivre une trajectoire courbe. Sa portee effective depasse celle de la plupart des artilleries Vent standard. Il opere souvent depuis des positions au sol que les ennemis considerent trop basses pour etre des points de tir efficaces.",
    "Ouragan choisit une position stable au sol ou sur une case Aerienne basse. Couloir de Vent ouvre une trajectoire directe sur la cible, meme a travers des obstacles. Cyclone tombe sur la cible apres avoir voyage le long du couloir. Bourrasque Verticale depuis la meme direction projette en hauteur ce qui reste. Vortex maintient la zone sous bombardement continu. Rafale en tir de precision sur les unites qui sortent de la zone. Il ne se repositionne que si absolument necessaire.",
    "Couloir de Vent de Ouragan a une portee de 12 cases et peut suivre une trajectoire courbe (jusqu'a deux changements de direction de 45 degres). Cyclone lance dans un Couloir de Vent voyage le long du couloir et frappe en bout de trajectoire. Bourrasque Verticale depuis une distance de 8 cases au lieu de la portee standard. Passif Tir Stabilise : si Ouragan n'a pas change de position depuis son dernier tour, ses sorts ont +30% de degats et +3 de portee."
))

write(f"{BASE}/vent/218-zephyr/index.ts", char_file(
    218, "Zéphyr", "Vent", "Tireur", "Aérides", "Asterciel", "Indépendant",
    "Aeride dont la specialisation en tir de precision Vent a produit un physique asymetrique — ses ailes gauches sont plus developees que les droites, compensant la rotation naturelle de ses tirs rotatifs. Sa vision est sa caracteristique principale : ses yeux ont evolue pour suivre des projectiles aeriens a des vitesses que l'oeil ordinaire ne peut pas tracker, avec une capacite de zoom naturel tres inhabituelle. Il est de petite taille et se deplace avec une economie de mouvements absolue, ne consommant de l'energie que pour ce qui est necessaire. Il porte un equipement de tir de precision minimal — juste des stabilisateurs aux poignets et des lunettes de protection a niveau de magnification variable.",
    "Zephyr est silencieux, observateur, et tres patient. Il peut rester en position pendant des heures sans bouger. Sa conversation se limite a ce qui est necessaire pour la mission. Il n'est pas hostile — il est concentre. Sa carriere independante lui donne la liberte de choisir ses contrats selon des criteres qui lui appartiennent, criteres qu'il n'a jamais explicites a personne.",
    "Tireur de precision independant a Asterciel, travaillant principalement pour des communautes aerides que ni l'Empire ni les Dissidentes ne couvrent. Il protege des villages isoles contre les expeditions de captation imperiale en eliminant les eclaireurs avant qu'ils puissent retourner avec des informations. Sa methode — tirs Vent de longue portee depuis des positions elevees — laisse peu de traces que les enqueteurs imperiaux peuvent suivre.",
    "Zephyr choisit la position la plus haute disponible et attend. Courant Ascendant lui donne +1 PM apres chaque sort (il ne se deplace presque pas). Rafale de precision a longue portee depuis la hauteur. Si un ennemi s'approche, Case Aerienne dessous le sort immediatement de la zone de corps a corps. Propulsion de lui-meme pour repositionnement rapide. Vortex defensif autour de sa position. Cyclone en couverture si sa position est identifiee.",
    "Zephyr peut maintenir un tir de precision a travers un Couloir de Vent existant, meme sans ligne de vue directe. Rafale a +4 de portee quand lancee depuis une position Z+2 ou plus. Case Aerienne creee par Zephyr est invisible pour les ennemis tant qu'il l'occupe seul. Passif Precision Aeolienne : apres 1 tour d'immobilite, les sorts de Zephyr ont 100% de chance de critique (x1.5 degats). Cette precision est perdue des qu'il se deplace."
))

write(f"{BASE}/vent/219-vent-fantome/index.ts", char_file(
    219, "Fantask", "Vent", "Assassin", "Aérides", "Asterciel", "Dissidentes",
    "Aeride dont les ailes se sont adaptees au silence — leurs plumes ont developpe une structure analogue aux plumes de hibou, avec des bords fractaux qui brisent les turbulences et eliminent pratiquement tout son aerodynamique. Il peut voler a pleine vitesse en silence absolu. Sa peau est d'un gris tres pale qui se confond avec le ciel couvert d'Asterciel. Ses mouvements au sol ont aussi ete optimises — il pose le pied avec une precision qui evite tout son, meme sur des surfaces instables. Dans les airs, il est invisible a la vue et au son; il n'apparait dans la perception que par ses effets.",
    "Fantask est l'incarnation de la discretion comme discipline morale. Il croit que l'intervention la plus efficace est celle dont personne ne se souvient — il aime disparaitre avant que ses cibles comprennent ce qui s'est passe. Sa relation avec les Dissidentes est fonctionnelle : ils lui designent des cibles qui nuisent aux communautes qu'ils protegent, il les elimine, il disparait. Pas de debriefing, pas de rapport.",
    "Eliminateur silencieux des Dissidentes a Asterciel. Fantask opere contre les agents de surveillance de l'Empire — specifiquement ceux comme Tempestine qui cartographient les flux de Vent utilises par les brigades des Dissidentes. Son mode operatoire laisse si peu de traces que certaines de ses eliminations ont ete classees comme accidents meteorologiques dans les archives imperiales.",
    "Fantask approche en vol silencieux a haute altitude, hors de la zone de detection de Tempestine. Propulsion de lui-meme en pique silencieux. Rafale a contact pour un impact-choc. Courant Ascendant lui donne +1 PM pour la retraite immediate. Case Aerienne pour sortir verticalement. Vortex sur la case de la cible post-frappe pour brouiller les pistes. Il utilise Mue atmospherique — des changements de courant qui brouillent sa signature de Vent.",
    "Fantask est invisible quand il est en vol a Z+2 ou plus (les ennemis ne peuvent pas le cibler). Son atterrissage depuis Z+3 ou plus genere automatiquement un Vortex mini sur sa case d'impact, etourdissant les unites adjacentes 1 tour. Rafale utilisee immediatement apres un atterrissage invisible inflige 200% de degats. Passif Silence Aeolien : Fantask ne genere aucune signature de Vent detectable (Tempestine et les capteurs similaires ne peuvent pas le tracker)."
))

write(f"{BASE}/vent/220-tourbillon/index.ts", char_file(
    220, "Tourbillon", "Vent", "Escrimeur", "Aérides", "Asterciel", "Empire",
    "Aeride dont le style d'escrime aerienne est reconnaissable a un detail — il tourne toujours en sens antihoraire, meme en marchant, comme si son corps avait internalise la rotation de ses sorts. Cette rotation permanente donne l'impression qu'il est plus grand qu'il n'est et qu'il occupe plus d'espace. Ses ailes sont courtes et larges — optimisees pour les virages serres en combat rapproche, pas pour la vitesse. Ses deux sabres sont forges dans un alliage aerien qui conduit et amplifie le Vent ; leurs tranches laissent des sillages visibles dans l'air quand il frappe.",
    "Tourbillon est un dueliste par vocation et par plaisir. Il n'est pas cruel — il aime le combat comme d'autres aiment les jeux strategiques. L'Empire lui fournit des adversaires de qualite et une structure qui valorise son excellence individuelle. Sa rotation permanente est une habitude de combat, pas un tic — il dit qu'elle lui permet de toujours avoir un angle d'attaque pret.",
    "Dueliste imperial deploye pour les confrontations avec les Elus Vent adverses qui menacent les operations de l'Empire a Asterciel. Tourbillon est envoye quand l'Empire a besoin qu'un probleme Vent specifique soit resolu par un combat singulier plutot que par une operation de force. Il a affronte Rafal deux fois — les deux rencontres ont ete indecises, ce qui constitue un record pour Tourbillon qui ne tire pas souvent des matchs.",
    "Tourbillon cree un Vortex autour du duel — une arene de vent qui maintient les autres hors de portee et son adversaire dedans. Ascension pour prendre la hauteur. Corps a corps en spirale descendante — chaque tour de sa rotation est une frappe differente. Rafale pour creer de la distance puis Propulsion pour la refermer immediatement. Bourrasque Verticale si l'adversaire tente de passer par-dessus. Case Aerienne sous lui pour maintenir la superiorite aerienne.",
    "En 1v1, Tourbillon gagne 1 stack de Rotation par tour (max 5). Chaque stack donne +10% de vitesse de deplacement et +5% de degats. Vortex en situation de duel est instantane (0 temps de cast). Rafale de Tourbillon en situation de duel repousse de 2 cases au lieu de 1. Passif Rotation Parfaite : si Tourbillon se deplace en cercle autour de sa cible (cases adjacentes en rotation), chaque attaque suivante ce tour inflige +20% de degats cumules."
))

write(f"{BASE}/vent/221-typhon/index.ts", char_file(
    221, "Typhon", "Vent", "Vanguard", "Aérides", "Asterciel", "Convergence",
    "Aeride dont l'envergure atteint cinq metres — la plus grande enregistree dans les archives d'Asterciel depuis deux generations. Ses ailes ne ressemblent pas a des ailes d'oiseau mais a des voiles membraneuses d'un vert-gris sombre qui capterait les courants plutot que de les generer. Sa presence genere un vent continu de basse intensite dans un rayon de dix metres — pas par controle conscient, mais par saturation atmospherique passive. Son visage est serein, presque endormi — il regarde le combat avec la patience d'un front meteorologique qui n'a pas besoin de se presser.",
    "Typhon ne se presse pas parce qu'il est le Vent — il ne peut pas aller plus vite que lui-meme. La Convergence lui convient parce que ses strategies sont des fronts de pression, pas des assauts individuels. Il avance et la carte change devant lui. Ses allies savent qu'ils doivent suivre sa cadence, pas l'inverse.",
    "Front d'avancee de la Convergence dans les grandes operations atmospheriques d'Asterciel. Typhon est utilise pour les offensives qui necessitent de modifier le theatre d'operation en entier — il ne cible pas des unites, il cible des zones. Ses operations avec Gorwind (Juggernaut, Convergence) sont documentees : Gorwind tient une position fixe, Typhon avance et change le terrain atmospherique autour.",
    "Typhon deploie Couloir de Vent sur toute la largeur de la zone — une autoroute atmospherique que ses allies utilisent gratuitement et que les ennemis ne peuvent pas traverser sans payer un lourd tribut en PM. Cyclone sur les positions defensives ennemies. Bourrasque Verticale sur toute la ligne adverse pour briser les formations. Il avance avec Ascension — pas d'urgence, juste une progression constante. Vortex sur les points de concentration ennemie. Rafale de couverture sur quiconque tente de flanquer.",
    "Couloir de Vent de Typhon peut couvrir une largeur de 3 cases (un front) plutot qu'une seule ligne. Cyclone de Typhon a un rayon de 5 cases. Son deplacement de Vanguard peut utiliser les Cases Aeriennes sans cout PM. Passif Pression Frontale : quand Typhon avance d'au moins 1 case par tour, tous les ennemis a moins de 4 cases devant lui ont leurs couts de deplacement vers lui augmentes de 3 PM (la pression atmosepherique les ralentit)."
))

write(f"{BASE}/vent/222-rempart-aerien/index.ts", char_file(
    222, "Aeryn", "Vent", "Gardien", "Aérides", "Asterciel", "Dissidentes",
    "Aeride dont la physiologie a evolue vers la defense statique — inhabituelle pour une espece definie par la mobilite. Ses ailes sont plus larges que hautes, formant un bouclier naturel qu'il peut plaquer contre son corps pour absorber des impacts. Sa peau a developpe une couche de micro-plumes dures sur le torse et les epaules qui absorbent les degats physiques comme une armure naturelle. Il est de taille superieure a la moyenne et sa posture est celle de quelqu'un qui ne reculera pas — pas par bravade, par certitude geometrique.",
    "Aeryn protege les gens parce que c'est ce pour quoi il est fait. Sa psychologie de Gardien est authentiquement Aeride — dans la tradition des anciens protecteurs de nids d'Asterciel, il defend un perimetre contre tout ce qui menace ce perimetre. La politique est secondaire : les Dissidentes protegent les siens, il protege les leurs.",
    "Gardien de position des brigades d'insertion verticale des Dissidentes. Une fois qu'Aelyx a etabli une position haute, Aeryn la tient. Sa presence transforme n'importe quelle case Aerienne en forteresse temporaire que les troupes imperiales ne peuvent pas reprendre facilement. Son association avec Aelyx est la plus documentee de la brigade Vent des Dissidentes.",
    "Aeryn installe une Case Aerienne sur sa position et y reste. Vortex autour de sa position empeche l'approche au sol. Bourrasque Verticale repousse les ennemis qui tentent de monter a sa hauteur. Cyclone en dessous de sa position sur les formations au sol. Il utilise Courant Dirige pour permettre aux allies de rejoindre sa position rapidement. Rafale sur tout ennemi qui passe quand meme. Propulsion sur un allie en danger pour le sortir de la zone de peril vers sa position protegee.",
    "Aeryn peut creer une Case Aerienne sur sa propre position gratuitement (0 PM) une fois par combat. Vortex de Aeryn en position defensive (il n'a pas bouge ce tour) a un rayon de 4 cases au lieu de 2. Bourrasque Verticale de Aeryn peut repousser plusieurs unites simultanement si elles tentent de monter dans le meme tour. Passif Forteresse Volante : tant qu'Aeryn est sur une Case Aerienne, les ennemis ont besoin de 4 PM supplementaires pour atteindre sa case (resistance atmospherique amplifiee)."
))

write(f"{BASE}/vent/223-l-inconstant/index.ts", char_file(
    223, "L'Inconstant", "Vent", "Spécialiste", "Aérides", "Asterciel", "Indépendant",
    "Aeride dont la nature elementaire a atteint un stade que les meteorologistes d'Asterciel categorisent comme instabilite thermodynamique consciente — L'Inconstant ne produit pas de Vent, il est la perturbation atmospherique elle-meme. Sa silhouette change de direction dans l'air, comme une banderole dans le vent, et son corps ne maintient jamais exactement la meme forme deux secondes consecutives. Les parties de lui qui sont physiquement stables sont ses mains et ses pieds — tout le reste ondule. Les courants d'air autour de lui suivent des trajectoires impredictibles meme pour les autres elements Vent.",
    "L'Inconstant ne sait pas ce qu'il va faire avant de le faire — pas par incapacite, par nature. Sa pensee est meteorologique : une serie de conditions qui se combinent en resultats emergents. Il n'appartient a aucune faction parce qu'aucune faction ne peut planifier avec quelqu'un dont les contributions sont par definition impredictibles. Il apparait quand les conditions meteorologiques l'amenent. Certains considerent cela comme une metaphore. Ce n'en est pas une.",
    "Phenomene atmospherique conscient documente par l'Observatoire d'Asterciel depuis des decennies. L'Inconstant est note dans les archives comme une anomalie meteorologique recurrente qui coincide avec des changements significatifs dans les equilibres de pouvoir a Asterciel. Ni l'Empire ni les Dissidentes ne peuvent le recruter — personne ne peut le trouver avant qu'il decide d'apparaitre.",
    "L'Inconstant opere depuis n'importe quelle Case Aerienne de la carte sans deplacement. Il redistribue les effets atmosperiques — un Cyclone allie devient son Cyclone, un Vortex ennemi devient son Vortex. Courant Dirige sur toute la carte cree des lignes de force que personne d'autre ne pouvait planifier. Bourrasque Verticale depuis plusieurs points simultanement. Rafale dans des directions impossibles. Il ne tient pas de position — il n'a pas de position.",
    "L'Inconstant peut lancer tous ses sorts Vent depuis n'importe quelle Case Aerienne sur la carte (pas de portee restrictive). Il peut inverser les effets des sorts Vent ennemis : un Vortex ennemi devient le sien pendant 2 tours. Couloir de Vent qu'il cree dure toute la partie (permanent). Passif Impredictibilite : L'Inconstant ne peut pas etre cible par des sorts qui necessitent de maintenir une ligne de vue entre deux tours consecutifs — il n'est jamais au meme endroit exactement."
))

print("Vent: 13 characters written")

# ============================================================
# DRAGON (241-253) — Pyriens / Varkhol
# Spells: Morsure, Souffle Elementaire, Ecailles, Frappe des Griffes,
#         Rugissement, Vol Draconique, Ecailles Partagees, Destruction Massive,
#         Fureur Ancienne (ULTIME)
# Passifs: Presence Draconique, Resonance des Ecailles
# ============================================================

write(f"{BASE}/dragon/241-dragoryn/index.ts", char_file(
    241, "Dragoryn", "Dragon", "Enchanteur-Soutien", "Pyriens", "Varkhôl", "Dissidentes",
    "Pyrien dont la lignee porte une mutation draconique ancienne — des ecailles dures couvrent ses epaules, son dos et l'arriere de ses bras, en plaques d'un bordeaux sombre qui captent la chaleur ambiante et la redistribuent comme une armure thermique. Son visage est humain mais ses yeux sont verticaux, a pupille de reptile, en ambre dore. Ses mains ont des griffes retractables naturelles qu'il ne deploie pas en situation sociale mais que ses allies ont appris a interpreter comme un indicateur de stress. Il porte des robes amples pour les ceremonies des anciens codes draconiques de Varkhal, avec des encoches sur les epaules pour exposer les plaques d'ecailles dont la chaleur soigne les allies proches.",
    "Dragoryn est un gardien de memoire autant qu'un combattant. Il porte les codes ancestraux des Dragons qui ont jadis habite les formations rocheuses de Varkhal avant que l'Empire n'en commence l'extraction systematique. Sa colere contre l'Empire est profonde et documentee — pas une colere chaude, une indignation froide de quelqu'un qui sait exactement ce qui a ete detruit et qui en a besoin de chaque detail reconnu. Les Dissidentes l'ont rejoint parce qu'ils protegent ce qui reste.",
    "Gardien de la tradition draconique des Dissidentes a Varkhal. Dragoryn opere dans les anciens sites draconiques que l'Empire tente de converter en mines ou en centres de captation — sa connaissance des formations draconiques lui permet de creer des Cases Dragon dans des zones ou personne d'autre ne peut. Son Resonance des Ecailles a une portee etendue qui soutient toute la brigade dans des batailles d'attrition. Il est en contact regulier avec Khossaere (Capteur, Empire) qui tente de cataloguer ces memes sites.",
    "Dragoryn active Resonance des Ecailles au debut de l'engagement — elle s'applique a tous ses allies dans un rayon etendu. Ecailles Partagees sur les unites en premiere ligne. Rugissement de soutien pour amplifier la resistance de la brigade. Vol Draconique sur lui-meme pour une surveillance et coordination depuis les hauteurs. Ecailles qu'il pose sur les cases cles reduisent les degats pour quiconque les traverse cote allie. Destruction Massive en dernier recours si la position est perdue.",
    "Ecailles Partagees de Dragoryn donne son bonus de contre-degats a tous les allies sur les cases cibles (pas seulement l'unite). Resonance des Ecailles s'applique a un rayon de 6 cases autour de lui et dure toute la partie tant qu'il est en combat. Rugissement de Dragoryn n'inflige aucun degat aux allies — uniquement aux ennemis. Passif Memoire des Ecailles : quand un allie sur une Case Dragon prend des degats, ces degats sont reduits de 20% supplementaire."
))

write(f"{BASE}/dragon/242-khossaere/index.ts", char_file(
    242, "Khossaëre", "Dragon", "Enchanteur-Capteur", "Pyriens", "Varkhôl", "Empire",
    "Pyrien dont la mutation draconique s'est exprimee dans la direction de la perception — ses ecailles sont fines et argentees, couvrant uniquement la nuque et les tempes, formant des capteurs sismiques qui detectent les signatures thermiques draconiques dans un rayon considerable. Ses yeux ont developpe une vision infrarouge permanente. Mince et presque fragile en apparence physique, il se distingue par une precision de mouvements qui trahit une maitrise corporelle complete. Il porte des instruments de mesure draconique de fabrication imperiale — des capteurs thermiques calibres pour les signatures specifiques des Cases Dragon.",
    "Khossaere est un scientifique imperial qui croit sincerement que la catalogation et la preservation des sites draconiques passe par leur integration dans la structure imperiale. Il est en desaccord profond avec Dragoryn non pas sur l'importance de la tradition draconique, mais sur la methode — Khossaere croit que l'Empire peut la preserver mieux que les Dissidentes. Il est peut-etre sincere. Il est certainement utile a l'Empire.",
    "Agent de catalogation draconique de l'Empire a Varkhal. Khossaere identifie les sites draconiques actifs, les Elus Dragon recalcitrants, et les sources de Resonance des Ecailles naturelle. Ses rapports alimentent les programmes d'integration forcee. Il connait personnellement Dragoryn — ils ont correspondu avant la rupture politique — et cette connaissance personnelle rend ses rapports sur le Soutien des Dissidentes dangereusement precis.",
    "Khossaere place des capteurs draconiques (Ecailles en mode surveillance) sur les cases a haute signature draconique. Presence Draconique passive l'informe de toutes les utilisations de sorts Dragon dans son rayon de detection. Rugissement en mode capteur pour localiser les sources ennemies. Vol Draconique pour survol de reconnaissance. Destruction Massive ciblee sur les anciennes structures draconiques que les Dissidentes utilisent comme abris. Morsure en urgence au corps a corps si approche.",
    "La Presence Draconique de Khossaere lui revele la position exacte de toutes les unites Dragon ennemies dans un rayon de 10 cases, meme invisibles. Ecailles qu'il pose en mode surveillance enregistrent tous les sorts lances depuis ou vers cette case. Rugissement de Khossaere peut etre utilise en mode silence — sans effet sonore, detectable uniquement par les capteurs draconiques (pas par les adversaires). Passif Emprunte Draconique : Khossaere peut identifier quelle unite a cree une Case Dragon particuliere en l'examinant."
))

write(f"{BASE}/dragon/243-gorrath/index.ts", char_file(
    243, "Gorrath", "Dragon", "Juggernaut", "Pyriens", "Varkhôl", "Convergence",
    "Pyrien dont la mutation draconique a pris une direction de masse — ses ecailles ne sont pas des plaques fines mais des formations rocheuses qui ont pousse sur son corps comme des excroissances geologiques. Deux metres vingt, avec des formations d'ecailles de la taille d'assiettes sur les epaules et la cage thoracique qui lui donnent une silhouette de creature pre-humaine. Ses griffes naturelles ont la densite de la roche volcanique et peuvent s'enfoncer dans du basalte. Sa presence genere une chaleur draconique passive — les vitres fondent dans un rayon de deux metres quand il est a pleine puissance.",
    "Gorrath pense en termes de fronts, pas de cibles. Un front tient ou il cede. Il est le front. La Convergence lui offre ce contexte — il est un element d'une structure collective ou sa fonction est claire. Il n'a pas de nuance philosophique sur les affiliations politiques. Il y a ce qu'il protege et ce qu'il repousse.",
    "Front de choc de la Convergence dans les operations de reprise des formations draconiques de Varkhal. Gorrath est l'element qui absorbe et contre-pousse. Ses operations combinees avec Dragoryn (Dissidentes) sont rares mais existent — quand les objectifs convergent contre les operations imperiales de destruction des formations draconiques, les deux factions operent parallelement sans coordination formelle.",
    "Gorrath active Ecailles sur lui-meme — sa resistance de base est augmentee de 30%. Rugissement en ouverture repousse et intimide les ennemis adjacent. Vol Draconique pour un atterrissage de choc sur la ligne adverse. Ecailles Partagees sur les alliees les plus exposes. Frappe des Griffes en attaque de front. Destruction Massive quand il a suffisamment de Cases Dragon autour pour maximiser l'impact. Morsure en corps a corps sur les adversaires qui percent.",
    "Ecailles sur Gorrath lui-meme ont un effet de contre-degats de 40% (au lieu de 30%). Vol Draconique de Gorrath genere un impact sismique a l'atterrissage — toutes les unites sur les 4 cases adjacentes sont renversees. Rugissement de Gorrath a un rayon de 4 cases au lieu de 2. Passif Armure Draconique : Gorrath absorbe les 15% premiers degats de chaque attaque qu'il recoit (s'applique avant tous autres calculs). Ce seuil augmente de 2% par Case Dragon dans un rayon de 3."
))

write(f"{BASE}/dragon/244-drake-rapide/index.ts", char_file(
    244, "Skarath", "Dragon", "Plongeur", "Pyriens", "Varkhôl", "Dissidentes",
    "Pyrien dont la mutation draconique s'est specialisee dans la vitesse — ses ecailles sont d'une finesse extreme, presque des lamelles, qui glissent sur les surfaces comme des lames et reduisent la resistance a presque zero. Sa silhouette en mouvement laisse une trace lumineuse qui met une demi-seconde a disparaitre — un effet de l'acceleration des particules draconiques dans son sillage. Ses yeux calculent les trajectoires avec une vitesse de traitement que les medecins draconiques classifient comme surclock biologique. Il ne peut pas rester immobile longtemps — son metabolisme draconique accelere l'exige.",
    "Skarath vit dans le moment de l'approche. Le reste du combat l'interesse peu — il aime uniquement la seconde ou il ferme la distance a vitesse maximale. Cette monofocalisation fait de lui un Plongeur d'une efficacite exceptionnelle et un stratege assez mediocre. Les Dissidentes gere cela en lui donnant des cibles precises et en le laissant trouver son propre chemin vers elles.",
    "Operateur de penetration rapide des Dissidentes a Varkhal. Skarath est specialise dans les assauts sur les formations imperiales en mouvement — il ne cible pas les fortifications, il cible les colonnes en transit. Avant qu'une escorte imperiale realise qu'elle est attaquee, il est deja parti. Son partenariat avec Dragoryn : le Soutien amplifie sa Resonance des Ecailles pendant l'approche, lui donnant des degats de base plus eleves au moment de l'impact.",
    "Skarath commence derriere une Case Dragon existante — Ecailles sur lui pour la resistance. Frappe des Griffes pour l'acceleration. Vol Draconique en ligne droite sur la cible — il utilise la portee maximale pour arriver a vitesse maximale. Morsure a l'impact. Ecailles Partagees sur lui-meme pour la retraite. Rugissement pour degager les poursuivants. Destruction Massive si une Case Dragon est a portee pour le retour.",
    "Vol Draconique de Skarath a une portee de 10 cases au lieu de 7. Son atterrissage apres Vol Draconique compte comme un Coup de Griffe automatique (degats sans cout PM). Morsure lancee dans le meme tour qu'un Vol Draconique inflige 150% de degats. Passif Acceleration Draconique : chaque tour ou Skarath se deplace de 4 cases ou plus en ligne droite, sa prochaine attaque inflige +30% de degats (stackable 3 fois, reset apres attaque)."
))

write(f"{BASE}/dragon/245-dracomax/index.ts", char_file(
    245, "Pyraxis", "Dragon", "Mage-Burst", "Pyriens", "Varkhôl", "Indépendant",
    "Pyrien dont la mutation draconique a pris une direction elementaire explosive — son Souffle Elementaire n'est pas une flamme standard mais une surcompression de l'element Dragon pur, une decharge d'energie draconi que concentree qui fracture les surfaces au moment de l'impact. Des ecailles d'un rouge vif couvrent ses avant-bras et sa machoire, et ses yeux sont d'un orange lumineux qui pulsent avant chaque decharge. Il porte des gantlets qui canalisent et amplifient ses souffles, avec des soupapes de securite qui s'ouvrent automatiquement si la pression depasse un seuil — l'explosion resultante n'est pas fatale pour lui, seulement pour les environs.",
    "Pyraxis est passionne par son propre pouvoir de la maniere dont un ingenieur est passionne par une machine qu'il a construite — il l'etudie, l'optimise, l'exploite a sa limite. Son independance vient du fait que ses employeurs precedents n'aimaient pas les tests de charge en conditions reelles qu'il impose systematiquement. Il accepte des contrats ou le niveau de destruction est clairement specifie et ou les dommages collateraux ont ete evalues avant son arrivee.",
    "Specialiste en demolition draconique independant a Varkhal. Pyraxis est appele pour les cibles que les autres methodes ne peuvent pas atteindre — des fortifications imperiales epaisses, des formations rocheuses que l'Empire a mineralise contre les attaques standard, des Gardiens Dragon que seul un Burst peut deborder. Il a travaille pour les Dissidentes sur plusieurs operations — chaque fois avec un briefing exhaustif sur ce qu'il peut et ne peut pas detruire.",
    "Pyraxis accumule des Cases Dragon sur la zone cible via Ecailles multiples. Chaque Case Dragon augmente l'amplitude de son Souffle Elementaire. Resonance des Ecailles maximisee avant le tir. Destruction Massive depuis la position la plus haute disponible — la ligne de degats descend depuis la hauteur et frappe tout ce qui est dessous. Rugissement pour aplatir ce qui a survecu. Fureur Ancienne en final si la cible tient encore.",
    "Souffle Elementaire de Pyraxis inflige 25% de degats supplementaires par Case Dragon dans la trajectoire (max +100%). Destruction Massive de Pyraxis peut etre chargee 1 tour pour doubler son rayon. Resonance des Ecailles de Pyraxis double sa propre puissance draconique (pas celle des allies) pendant 4 tours. Passif Surchauffe : a pleine capacite (3 Cases Dragon dans un rayon de 2), les sorts de Pyraxis passent en Surcharge — +50% degats, -50% cooldown pour 2 sorts consecutifs avant reset."
))

write(f"{BASE}/dragon/246-pyraskale/index.ts", char_file(
    246, "Pyraskale", "Dragon", "Battlemage", "Pyriens", "Varkhôl", "Empire",
    "Pyrien dont le style de combat draconique hybride a produit une posture unique — il combat avec les griffes et le souffle en alternance parfaite, avec des ecailles deployees sur les avant-bras qui servent d'armure offensive (les bords des ecailles sont des lames naturelles). Sa peau est d'un rouge sombre sature, ses ecailles d'un or sombre, et son Souffle Elementaire part de ses mains plaquees ensemble plutot que de sa bouche — une technique Pyriene apprise d'un mage draconique imperial. Il porte une armure imperiale modifiee avec des fentes dans les manches pour le deploiement rapide de ses ecailles-lames.",
    "Pyraskale est loyal a l'Empire avec la conviction d'un soldat qui croit dans l'institution. Il n'analyse pas les ordres — il les execute avec excellence. Sa technique de Battlemage draconique est l'aboutissement de dix ans de formation imperiale et il en est fier. Son seul point d'irritation visible : le gaspillage. Un sort mal vise, une ouverture manquee, un mouvement imprecis — il corrige immediatement et ne repete pas l'erreur.",
    "Combattant de ligne de l'Empire specialise dans les operations contre les Elus Dragon des Dissidentes. Pyraskale est deploy e quand l'Empire a besoin de quelqu'un qui comprend la mecanique draconique et peut l'exploiter en combat direct. Son rapport avec Gorrath (Convergence) est un exemple documente de deux Juggernauts-equivalents se neutralisant sur un terrain d'operation pendant que d'autres unites atteignent leurs objectifs.",
    "Pyraskale alterne corps a corps et sorts draconiques en sequence calculee. Ecailles deployees sur ses bras pour une frappe de griffes amplifiee. Souffle Elementaire immediat apres le contact. Rugissement pour repousser et creer de l'espace. Vol Draconique court pour repositionnement. Ecailles sur sa case pour un couvert tactique. Destruction Massive en fermeture sur un groupe concentre. Morsure en corps a corps si la cible resiste.",
    "Les sorts Dragon de Pyraskale ont une portee additionnelle de 2 quand il est en contact (portee 1) — son Souffle sort en conique depuis la position de corps a corps. Frappe des Griffes de Pyraskale peut etre enchainee 2 fois de suite (2e frappe a -1 PM). Rugissement lance apres un corps a corps est instantane. Passif Ecailles Actives : quand Pyraskale est frappe au corps a corps, ses ecailles-lames infligent automatiquement 25% de degats retour a l'attaquant."
))

write(f"{BASE}/dragon/247-souffre-loin/index.ts", char_file(
    247, "Vrathax", "Dragon", "Artillerie", "Pyriens", "Varkhôl", "Dissidentes",
    "Pyrien dont le Souffle Elementaire a evolue vers une portee extremement longue au detriment de la puissance immediate — il projette des charges draconiques comprimees sur des distances qui depassent la portee visuelle ordinaire. Sa machoire est surdeveloppee par rapport au reste de son visage, consequence des muscles de compression qu'il utilise pour ses tirs. Ses ecailles sont concentrees sur sa gorge et sa poitrine, formant une armure naturelle autour des chambres de compression. Il n'est pas grand — son corps est construit pour la precision a distance, pas pour absorber des impacts.",
    "Vrathax est methodique. Il arrive sur un terrain, evalue les angles, identifie les lignes de tir, et s'installe. Il ne bouge pas sauf necessite absolue — tout repositionnement est du temps perdu. Les Dissidentes l'apprecent parce qu'il est fiable : il fait exactement ce qu'il dit qu'il va faire, dans le temps qu'il a estime, avec la precision qu'il a annoncee.",
    "Artilleur de siege des Dissidentes a Varkhal. Vrathax est deploye contre les fortifications imperiales trop epaisses pour un assaut standard. Son Souffle Elementaire longue portee peut contourner les defenses frontales en utilisant les Cases Dragon comme relais de puissance. Son historique d'operations inclut la destruction de trois tours de surveillance imperiales que les forces au sol des Dissidentes n'avaient pas pu approcher.",
    "Vrathax identifie la Case Dragon la plus proche de la cible — elle servira de relais. Il active Resonance des Ecailles pour maximiser la puissance du prochain tir. Souffle Elementaire en tir tendu, utilisant la Case Dragon comme amplificateur. Rugissement pour repousser les gardes qui se repositionnent vers lui. Ecailles sur sa position pour la durabilite. Si la cible n'est pas detruite, Destruction Massive centree sur la Case Dragon la plus proche d'elle.",
    "Souffle Elementaire de Vrathax a une portee de 12 cases et rebondit sur une Case Dragon dans sa trajectoire (le tir continue apres impact sur la case, avec 75% des degats). Rugissement de Vrathax peut etre lance en silence — sans son perceptible, uniquement l'effet. Ecailles creees par Vrathax servent de relais de puissance qui amplifient ses tirs de 20% si le sort passe par leur case. Passif Compression Maximale : si Vrathax reste stationnaire 2 tours consecutifs, son prochain Souffle Elementaire inflige 200% de degats."
))

write(f"{BASE}/dragon/248-dragun/index.ts", char_file(
    248, "Dragun", "Dragon", "Tireur", "Pyriens", "Varkhôl", "Indépendant",
    "Pyrien dont la mutation draconique s'est exprimee dans la precision de tir plutot que dans la puissance brute. Ses yeux ont evolue vers un systeme de mise au point automatique qui lui permet de verrouiller une cible a distance sans perte de precision due au mouvement. Ses ecailles sont concentrees sur sa main de tir droite, formant une surface de lancement naturelle pour ses charges draconiques condensees. Il est de taille moyenne, economiquement construit, et son seul equipement visible est un cadre de visee augment imperiale qu'il a vole lors d'une operation et adapter a ses capacites non-imperiales.",
    "Dragun n'a pas de passion politique. Il a une passion pour la difficulte technique des angles de tir. Son independance est une consequence de cette passion — il ne veut pas etre limite par des objectifs factionnels qui lui imposent des cibles qui ne l'interessent pas. Il accepte des contrats selon la difficulte technique de la mission, pas selon l'ideologie du client.",
    "Tireur independant a Varkhal, travaillant pour quiconque peut lui proposer un angle de tir qu'il n'a pas encore essaye. Sa clientele est aussi bien imperiale que dissidente selon les periodes. Les deux factions l'utilisent et le tolerent mutuellement parce que sa valeur tactique depasse le cout ideologique de le payer. Il a une rivalite professionnelle avec Ballix (Roche) autour de qui peut realiser le tir le plus techniquement difficile.",
    "Dragun choisit une position avec le meilleur angle disponible. Resonance des Ecailles amplifie sa precision naturelle. Frappe des Griffes a distance equivalente a un tir de precision — il lance des griffes condensees. Ecailles sous sa position pour la stabilite. Rugissement en defense si approche. Vol Draconique court pour repositionnement d'urgence. Morsure si quelqu'un atteint son corps a corps — il n'aime pas ca mais il peut.",
    "Frappe des Griffes de Dragun a une portee de 8 cases et peut etre chargee 1 tour pour traverser les couverts. Rugissement de Dragun peut etre lance silencieusement en depensant 2 PM supplementaires. En restant stationnaire 1 tour, Dragun verrouille sa cible — ses 2 prochains sorts sur cette cible ne peuvent pas etre evites par les effets de deplacement. Passif Visee Draconique : les sorts de Dragun ignorent 30% de l'armure des cibles sur des Cases Dragon."
))

write(f"{BASE}/dragon/249-scalek/index.ts", char_file(
    249, "Scalek", "Dragon", "Assassin", "Pyriens", "Varkhôl", "Dissidentes",
    "Pyrien dont la mutation draconique a pris la direction du camouflage. Ses ecailles peuvent changer de couleur avec une rapidite que les chameleons ordinaires ne peuvent pas rivaliser — en moins d'une seconde, il passe du rouge draconique au gris de la roche de Varkhal. Cette adaptation chromatique est totale, incluant ses vetements qui ont absorbe des particules draconiques. Ses mouvements sont silencieux — ses ecailles ne cliquent pas les unes contre les autres parce qu'elles ont ete genetiquement separees par des couches de tissu mou. Il laisse une odeur de soufre tres faible que seuls les autres Pyriens peuvent detecter.",
    "Scalek est un professionnel de l'elimination sans temoins. Il ne tue pas par plaisir — il tue parce que la cible represente une menace concrete aux gens qu'il protege. Cette precision morale ne le rend pas hesitant : il agit avec la meme efficacite qu'une force naturelle. Les Dissidentes l'emploient pour des missions dont les detai ls ne doivent pas exister dans leurs registres.",
    "Eliminateur specialise des Dissidentes a Varkhal. Scalek cible les agents imperiaux responsables de l'identification et de la capture des communautes draconiques de Varkhal. Khossaere est en haut de sa liste de surveillance — pas encore son objectif d'operation, mais surveille en permanence. Son camouflage draconique lui permet d'approcher des cibles en zones ouvertes que d'autres assassins ne peuvent pas penetrer.",
    "Scalek active son camouflage draconique depuis une Case Dragon — invisible dans les environs draconiques. Aprocher la cible case par case, en utilisant les Cases Dragon comme couverture de signature. Morsure a l'emergence pour une attaque maximale depuis l'invisibilite. Frappe des Griffes apres pour maintenir la pression. Si la cible survit, Rugissement pour la desorienter pendant la retraite. Ecailles pour se proteger pendant la sortie. Vol Draconique en urgence.",
    "Scalek est invisible sur les Cases Dragon — les ennemis ne peuvent pas le cibler tant qu'il reste sur ces cases. Sa premiere attaque depuis l'invisibilite inflige 200% de degats (Morsure ou Frappe des Griffes). Morsure de Scalek depuis une Case Dragon draine 15% des PV max de la cible en bonus. Rugissement de Scalek depuis l'invisibilite ne revele pas sa position. Passif Ecailles Cameleons : chaque tour ou Scalek reste sur une Case Dragon sans attaquer, il gagne 1 charge de Furtivite (max 3, +15% de degats sur la prochaine attaque par charge)."
))

write(f"{BASE}/dragon/250-lanset-ecaille/index.ts", char_file(
    250, "Lancerak", "Dragon", "Escrimeur", "Pyriens", "Varkhôl", "Empire",
    "Pyrien dueliste dont les ecailles se concentrent uniquement sur sa main et son avant-bras droits, formant un gantlet naturel qui est aussi sa principale arme — une griffe-lame de cristal draconique qui peut se deployer et se retracter en combat avec une precision milimetrique. Son corps est minimaliste et taille pour la mobilite : pas de formation rocheuse, pas de masse superflue. Il porte l'uniforme imperial de dueliste avec des modifications pour ses ecailles — des ouvertures aux points d'emergence. Son visage porte les marques d'un duel draconique ancien : deux cicatrices paralleles sur la joue gauche qu'il n'a pas fait soigner, presentees comme un brevet d'experience.",
    "Lancerak est un dueliste imperial d'une elegance calculee. Il parle peu en dehors des duels, mais en duel il est extraordinairement loquace — il commente, analyse, propose, en temps reel. Ce n'est pas de la vantardise, c'est sa maniere de penser a voix haute. Il respecte les adversaires qui repondent au meme niveau. Il a une admiration professionnelle non-declaree pour Granyte (Roche, Dissidentes) avec qui il partage le gout des confrontations techniques.",
    "Dueliste imperial deploye pour les confrontations avec les Elus Dragon des Dissidentes. Lancerak est envoye quand l'Empire a besoin qu'un combat singulier serve d'exemple. Il ne perd pas souvent. Son affrontement avec Skarath (Dissidentes) est reste dans les archives comme un exemple de mobilite contre endurance — Skarath est plus rapide, Lancerak est plus precis. Ils ont fait match nul deux fois.",
    "Lancerak cree un perimetre de Cases Dragon autour du duel — son arene naturelle. Ecailles sur lui-meme pour la resistance. Frappe des Griffes en attaque d'ouverture depuis la distance. Morsure au corps a corps pour le suivi. Rugissement pour creer de l'espace et evaluer la reaction adverse. Vol Draconique court pour repositionnement tactique en milieu de duel. Souffle Elementaire si l'adversaire tient trop bien son terrain.",
    "En 1v1, Lancerak gagne un bonus de 20% sur tous ses degats. Frappe des Griffes en situation de duel peut etre lancee deux fois par tour (2e utilisation gratuite si la premiere touche). Ecailles sur lui-meme durent le double de la duree standard en duel. Passif Precision Draconique : les attaques de Lancerak en situation de duel ne peuvent pas rater — elles touchent toujours (immunite aux effets de reduction de precision et d'esquive)."
))

write(f"{BASE}/dragon/251-rage-drake/index.ts", char_file(
    251, "Kharrath", "Dragon", "Vanguard", "Pyriens", "Varkhôl", "Convergence",
    "Pyrien dont la mutation draconique a atteint un niveau que les geneticiens de Varkhal classifient comme regression vers le type ancestral — il ressemble moins a un Pyrien avec des ecailles qu'a un Dragon qui a garde une forme humanoide. Ses ecailles couvrent 80% de sa surface corporelle, sa machoire s'est allongee, ses yeux sont lateraux comme un predateur, et ses mains se terminent en griffes permanentes qu'il ne peut pas retracter. Il marche avec une posture penchee vers l'avant qui indique une adaptation a la locomotion quadrupede. Sa voix est un grondement bas en permanence — pas de la colere, c'est simplement sa resonance vocale.",
    "Kharrath n'a pas de subtilite et ne pretend pas en avoir. Il a la clarte d'un element — il avance, il frappe, il tient. La Convergence l'apprecie parce qu'il execute avec une fiabilite absolue et sans questionner les ordres. Il parle peu mais ecoute et comprend tout. Sa loyaute est a l'operation en cours, pas a des abstractions politiques.",
    "Front d'assaut de la Convergence dans les operations de reprise des territoires draconiques de Varkhal. Kharrath est la force brute qui ouvre la voie pendant que d'autres unites atteignent leurs objectifs. Son association avec Gorrath (Juggernaut, Convergence) est un cas d'ecole d'epaisseur de front — deux unites d'une resistance qui force l'ennemi a depenser des ressources disproportionnees pour les arreter.",
    "Kharrath fonce en avant avec Vol Draconique de combat — pas le vol elegant mais le plonge de predateur. Ecailles sur lui-meme avant l'engagement. Rugissement en cone sur la ligne adverse. Corps a corps immedait — Morsure et Frappe des Griffes en alternance. Ecailles Partagees sur les allies qui le suivent dans la breche. Destruction Massive si une position ennemie concentree survit. Fureur Ancienne en final si la resistance est plus forte qu'attendu.",
    "Vol Draconique de Kharrath est une charge — il traverse les unites ennemies sur sa trajectoire, leur infligeant des degats et les repoussant d'1 case. Rugissement de Kharrath en cone de 3 cases de largeur. Ecailles sur lui-meme reduisent les degats de 40% (au lieu de 30%). Passif Regression Ancestrale : quand Kharrath tombe sous 50% PV, sa mutation draconique s'intensifie — ses degats au corps a corps augmentent de 50% et Morsure regenere 10% de ses PV max par utilisation."
))

write(f"{BASE}/dragon/252-fortrakken/index.ts", char_file(
    252, "Fortrakken", "Dragon", "Gardien", "Pyriens", "Varkhôl", "Dissidentes",
    "Pyrien dont les ecailles ont developpe une epaisseur et une densite qui depassent celles de tout Pyrien precedemment documente — ses plaques dorsales ont six centimetres d'epaisseur et la composition chimique du mineral le plus dense de Varkhal. Sa posture est permanemment basse et large, comme un animal pret a couvrir le sol avec son corps. Quand il deploie ses ecailles en mode bouclier, sa surface frontale double et devient quasiment impenetrable aux projectiles standard. Il est lent — ses ecailles pese nt plus que son armure musculaire ne peut compenser — mais il n'a pas besoin de vitesse.",
    "Fortrakken n'a pas de conscience politique elaboree mais il a une loyaute profonde aux Pyriens que l'Empire menace. Il protege ce qui est fragile contre ce qui est lourd. Sa philosophie de Gardien est instinctive : interpose-toi. Les Dissidentes le respectent sans le comprendre entierement — sa motivation n'est pas ideologique mais quelque chose de plus ancien que la politique.",
    "Gardien de la communaute draconique de Varkhal, Fortrakken protege les sites d'eclosion draconique que l'Empire cherche a saisir pour ses programmes de captation. Ces sites sont indefendables par des forces conventionnelles — ils sont trop etales, trop vulnerables sur les flancs. Fortrakken les defend en etant l'obstacle physique que les forces imperiales ne peuvent pas contourner sans perdre trop de temps.",
    "Fortrakken deploie ses ecailles en mode bouclier — il interpose sa surface maximale entre la menace et le site protege. Ecailles Partagees sur les allies de soutien derriere lui. Rugissement pour maintenir les ennemis a distance maximale. Destruction Massive si les rangs ennemis se serrent trop. Il ne bouge pas — c'est les autres qui bougent autour de lui. Vol Draconique uniquement pour reposition d'urgence. Morsure sur quiconque s'approche suffisamment.",
    "Ecailles sur Fortrakken lui-meme ont un effet de 50% de reduction des degats physiques et 40% des degats magiques. Ecailles Partagees qu'il lance protegent les allies pendant 5 tours au lieu de 3. Rugissement de Fortrakken ne peut pas etre interrompu et est instantane. Passif Forteresse Vivante : tant que Fortrakken est en vie et debout sur une Case Dragon, les ennemis ne peuvent pas cibler ses allies situes dans un arc arriere de 120 degres derriere lui avec des sorts a cible unique."
))

write(f"{BASE}/dragon/253-l-ancien/index.ts", char_file(
    253, "L'Ancien", "Dragon", "Spécialiste", "Pyriens", "Varkhôl", "Indépendant",
    "Entite draconique pour laquelle le terme Pyrien n'est plus tout a fait exact — L'Ancien est un etre dont la mutation draconique a atteint la regression complete vers une forme draconi que non-humanoide stable. Il peut maintenir une apparence humanoide par effort conscient, mais sa forme naturelle est celle d'un Dragon de taille reduite — deux metres de corps, trois d'envergure, ecailles d'un noir iridescent qui refletent les sept couleurs selon l'angle de lumiere. Il existe dans les archives de Varkhal sous des noms differents depuis trois siecles. La forme humanoide qu'il adopte pour les interactions est un emprunt, pas sa nature.",
    "L'Ancien n'a pas d'affiliation parce qu'aucune institution actuelle n'a une perspective temporelle suffisante pour lui etre utile. L'Empire comme les Dissidentes sont des phenomenes recents dans sa memoire — il les observe avec la patience de quelqu'un qui a vu des dizaines d'organisations comparables se former et se dissoudre. Il intervient quand quelque chose menace la continuite draconique de Varkhal a une echelle que lui seul peut percevoir.",
    "Presence documentee dans les archives draconiques de Varkhal depuis des siecles, sous des noms differents et des formes differentes. L'Ancien est la memoire vivante de ce que les Dragons de Varkhal etaient avant la mutation vers les formes humano ides. Son intervention lors des operations imperiales les plus destructrices sur les formations draconiques cles a ete determinante — pas en combat ouvert, en modification du terrain draconique lui-meme.",
    "L'Ancien opere depuis n'importe quelle Case Dragon de la carte. Resonance des Ecailles qu'il active est globale — elle affecte tous les elements Dragon allies sur la carte simultanement. Fureur Ancienne de L'Ancien est permanente — il est en mode Furie en continu. Destruction Massive depuis n'importe quelle Case Dragon cible n'importe quelle zone. Rugissement global affecte tous les ennemis sur la carte simultanement. Il ne se positionne pas — il se manifeste.",
    "L'Ancien peut lancer tous ses sorts Dragon depuis n'importe quelle Case Dragon sur la carte (pas de portee restrictive). Fureur Ancienne est son etat passif permanent — pas besoin de l'activer. Resonance des Ecailles de L'Ancien s'applique a tous les allies Dragon sur la carte. Passif Memoire Draconique : L'Ancien ne peut pas etre affecte par des effets de peur, de confusion ou de controle mental — il a existe trop longtemps pour que ces effets trouvent prise sur sa psyche."
))

print("Dragon: 13 characters written")
print("All done! Vent (13) + Dragon (13) = 26 characters written")
