#!/usr/bin/env python3
"""Write improved character files for Glace, Electrique, and Plante elements."""
import os, sys
sys.stdout.reconfigure(encoding='utf-8')

def char_file(id, nom, element, classe, espece, region, faction, phys, perso, lore, combat, modifs):
    kit_key = element
    return (
        f"import {{ ELEMENT_KITS }} from '../../../character-kits';\n"
        f"import type {{ Personnage }} from '../../../character-types';\n\n"
        f"const character: Personnage = {{\n"
        f"  id: {id},\n"
        f"  nom: `{nom}`,\n"
        f"  element: '{element}',\n"
        f"  classe: '{classe}',\n"
        f"  espece: '{espece}',\n"
        f"  region: '{region}',\n"
        f"  faction: '{faction}',\n"
        f"  description_physique: `{phys}`,\n"
        f"  description_personnalite: `{perso}`,\n"
        f"  position_lore: `{lore}`,\n"
        f"  style_combat: `{combat}`,\n"
        f"  kit: ELEMENT_KITS['{kit_key}'],\n"
        f"  modifications_classe: `{modifs}`,\n"
        f"}};\n\nexport default character;\n"
    )

def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"OK: {path}")

# =============================================================================
# GLACE — Ice · Conservation · Pureté · Silence · Stase
# Spells: Souffle Glacial, Congélation, Patinoire, Éclat de Glace, Pont Glacé,
#         Avalanche, Tempête de Grêle, Mur de Glace, Fracturation, ULTIME — Âge de Glace
# Passifs: Fragilité Cristalline (ennemis congelés reçoivent +50% dégâts), Hypothermie
# Species: Givrins/Crysalme, Aérides/Asterciel, Néréides/Thalassyr
# =============================================================================

write("src/data/characters/glace/061-crystyne/index.ts", char_file(
    61, "Crystyne", "Glace", "Enchanteur-Soutien", "Givrins", "Crysalme", "Dissidentes",
    "Givrine aux cheveux cristallisés — non pas figés comme de la glace ordinaire, mais structurés en prismes hexagonaux qui captent la lumière en arcs-en-ciel froids. Sa peau est d'un blanc bleuté avec des reflets nacrés aux articulations, signe d'une maîtrise de la Glace intégrée à sa biologie plutôt que simplement exercée par elle. Elle porte des vêtements tissés de fils de givre traité — isolants pour elle, glacants au toucher pour les autres. Ses yeux sont d'un gris argenté translucide qui luisent faiblement dans l'obscurité.",
    "Crystyne croit que la conservation est la forme d'amour la plus durable. Préserver ce qui est précieux — un Élu en danger, une route de fuite, le temps nécessaire pour décider — est selon elle plus difficile et plus noble que de détruire. Sa lenteur délibérée dans ses décisions irrite ses alliés impatients, mais ses positions défensives tiennent quand tout le reste s'effondre.",
    "Archiviste de la Chambre des Serments de Crysalme avant les purges, Crystyne conservait les documents attestant les promesses ancestrales de protection des Élus. Quand l'Empire fit saisir ces archives, elle en avait déjà copié les parties essentielles dans des cristaux-mémoire. Elle rejoignit les Dissidentes avec ces preuves, offrant une documentation irréfutable des droits des Élus que l'Empire prétend avoir toujours respectés.",
    "Crystyne ouvre avec Congélation sur les positions que ses alliés doivent tenir — les cases congelées ralentissent les ennemis qui y entrent et activent Fragilité Cristalline (+50% dégâts). Pont Glacé crée des couloirs d'accès pour ses alliés. Mur de Glace ferme les flancs et bloque les routes de contournement. Elle n'attaque directement qu'en dernier recours — Souffle Glacial pour ralentir une cible qui menace la ligne. Verglass exploite ses cases Congélation comme pièges.",
    "Congélation de Crystyne dure 2 tours supplémentaires et protège les alliés qui y entrent (réduction de dégâts de 15%). Pont Glacé peut être lancé vertical (vers le haut ou le bas) pour créer des élévations. Mur de Glace de Crystyne résiste à 3 fois plus de dégâts. Passif Gardienne du Givre : toute case Glace créée par un allié dans un rayon de 5 est sous son contrôle — elle peut en modifier l'effet."
))

write("src/data/characters/glace/062-verglass/index.ts", char_file(
    62, "Verglass", "Glace", "Enchanteur-Capteur", "Givrins", "Crysalme", "Empire",
    "Givrin dont la peau est traversée de craquelures de verglas actives — non pas des blessures, mais des canaux de magie Glace qui se propagent selon son humeur. Quand il prépare un piège, les craquelures s'étendent vers ses doigts et les extrémités de ses membres. Sa façon de regarder est oblique — jamais directement, toujours en biais, comme s'il calculait l'angle d'attaque optimal en permanence. Il porte une cape de cristaux de neige compressés qui lui donnent une présence sonore inexistante : aucun bruit de mouvement.",
    "Verglass est un stratège dont la patience ressemble à de la froideur — il ne précipite jamais, calcule toujours. Sa loyauté à l'Empire est fondée sur une conviction simple : les Élus non encadrés sont dangereux pour eux-mêmes. Sa méthode de capture par Congélation progressive est, selon lui, plus humaine que la force directe. Il ne blesse pas ses cibles — il les fige dans un moment de pure conservation.",
    "Agent de terrain de l'Empire à Crysalme spécialisé dans la capture d'Élus Glace qui résistent à la catalogisation. Sa méthode : créer des zones de Patinoire en amont de la route de fuite de sa cible, attendre que celle-ci glisse dans sa propre impossibilité de manœuvrer, puis la Congeler à portée maximale. Crystyne connaît ses techniques — ils se sont affrontés trois fois, et chaque fois ni l'un ni l'autre n'a pu conclure.",
    "Verglass prépare le terrain avant d'agir : Patinoire sur les cases de retraite probable de sa cible — tout mouvement rapide devient une glissade incontrôlée. Congélation à portée maximale sur la cible isolée. Éclat de Glace sur les alliés qui tentent d'intervenir — dégâts purs à distance. Mur de Glace pour fermer la cage. Souffle Glacial pour prévenir les contre-attaques. Fracturation sur la cible congelée pour décupler les dégâts via Fragilité Cristalline.",
    "Patinoire de Verglass s'étend automatiquement de 1 case par tour (propagation rampante). Congélation depuis une case Patinoire a sa portée augmentée de 3 cases. Éclat de Glace sur une cible congelée déclenche Fragilité Cristalline (×2.5 dégâts). Passif Architecte du Froid : il voit toutes les cases Glace sur la carte et peut les activer ou désactiver à distance."
))

write("src/data/characters/glace/063-glacurhn/index.ts", char_file(
    63, "Glacûrhn", "Glace", "Juggernaut", "Givrins", "Crysalme", "Convergence",
    "Givrin d'une taille anormale même pour son peuple — presque deux mètres de glace vivante, car sa peau s'est progressivement cristallisée sur les décennies d'utilisation de la Glace, formant une armure naturelle de plusieurs centimètres d'épaisseur sur les parties exposées. Ses bras sont particulièrement développés, chaque impact de ses poings créant des ondes de froid local. Il se déplace lentement mais avec une inertie qui rend chaque contact dévastateur. Sa voix résonne comme de la glace qui craque — profonde, fractale.",
    "Glacûrhn croit à la Convergence comme à un principe naturel : les glaciers avancent lentement mais inévitablement, transformant le paysage sans jamais reculer. Il est ce glacier. Sa force n'est pas dans la frappe ponctuelle mais dans l'inexorable avance qui nivelle tout. Il parle rarement, agit constamment, et ne comprend pas ceux qui cherchent à éviter le conflit plutôt qu'à le résoudre par la supériorité établie.",
    "Avant-garde de la Convergence pour les zones glacées de Crysalme où les Élus Glace récalcitrants se réfugient en pensant que leur élément les protège. Glacûrhn leur prouve que la Glace n'est pas un refuge — c'est son terrain natal. Ses opérations sont simples : avancer, congeler, absorber les contre-attaques dans sa propre armure cristalline, avancer encore.",
    "Glacûrhn crée une Patinoire autour de lui avant d'avancer — les ennemis glissent vers lui plutôt que de fuir. Il absorbe les dégâts dans son armure cristalline (Congélation partielle de ses propres surfaces). Avalanche sur les groupes ennemis qui tentent de l'encercler. Mur de Glace pour fermer les retraites latérales. Âge de Glace comme ultime pour transformer tout le champ en son terrain natif. Crystyne et Boryn le soutiennent depuis l'arrière.",
    "Dans une case Congélation ou Patinoire, Glacûrhn gagne +50% d'armure et ses dégâts de mêlée déclenchent automatiquement Fragilité Cristalline. Avalanche peut être lancée dans toutes les directions simultanément (rayon de 3 cases). Souffle Glacial de contact (portée 1) congèle instantanément sans délai. Passif Glacier Vivant : à chaque dégât reçu, une couche de glace se forme — Glacûrhn accumule une armure régénérative de 5% PV max par tour jusqu'à un plafond de 40%."
))

write("src/data/characters/glace/064-frosta/index.ts", char_file(
    64, "Frosta", "Glace", "Plongeur", "Aérides", "Asterciel", "Dissidentes",
    "Aéride dont la maîtrise de la Glace s'est adaptée à sa nature verticale — elle ne crée pas de glace sur le sol mais dans l'air, formant des plateformes cristallines qui s'effondrent au passage ou des lances de givre en trajectoire parabolique. Sa peau est d'un bleu pâle caractéristique des Aérides d'Asterciel, avec des marques de gel sur les tempes et les clavicules. Ses ailes — vestigiales, comme chez la plupart des Aérides modernes — sont suffisamment développées pour des sauts courts mais pas pour un vol soutenu.",
    "Frosta pense verticalement. Pour elle, une attaque n'est jamais frontale — elle est toujours depuis une position haute ou en dessous d'une ligne. Cette perspective tridimensionnelle lui donne un avantage dans les terrains plats où personne ne regarde vers le haut. Les Dissidentes l'utilisent précisément pour ça : elle arrive par où personne n'anticipe.",
    "Exploratrice des crêtes d'Asterciel reconvertie en agent de terrain des Dissidentes après que sa communauté aérienne fut identifiée comme productrice d'Élus et mise sous surveillance impériale. Ses Ponts Glacés aériens ont permis l'exfiltration de douze Élus depuis des positions apparemment inaccessibles — des plateformes créées à 20 mètres de hauteur que seule elle peut atteindre depuis le sol.",
    "Frosta utilise Pont Glacé pour créer des plateformes en hauteur, puis Ascension (si disponible) ou son saut aéride pour y accéder. Depuis cette position élevée, Éclat de Glace a une portée amplifiée par la hauteur. Congélation sur les cibles en contrebas. Si elle doit plonger dans la mêlée, Souffle Glacial au contact pour ralentir et Fragilité Cristalline pour maximiser les dégâts de ses alliés. Pontage de Lianes — non, Pont Glacé crée les voies, Verglass complète les pièges en bas.",
    "Pont Glacé de Frosta peut être créé en position verticale (lien entre deux hauteurs différentes). Éclat de Glace depuis une position haute inflige des dégâts bonus proportionnels à la hauteur (max ×2). Congélation lancée en hauteur crée une zone de gel suspendue qui tombe au tour suivant. Passif Assaut Vertical : ses attaques depuis une case plus haute que la cible bénéficient de Fragilité Cristalline sans condition."
))

write("src/data/characters/glace/065-cryal/index.ts", char_file(
    65, "Cryal", "Glace", "Mage-Burst", "Givrins", "Crysalme", "Indépendant",
    "Givrin compact aux cheveux entièrement blancs depuis son Éveil à l'âge de dix-sept ans — une décoloration instantanée lors de sa première Fracturation accidentelle qui a vitrifié un pan entier d'une forêt de Crysalme. Ses yeux sont d'un bleu tellement pâle qu'ils semblent presque blancs dans les environnements de forte luminosité. Il porte des gants renforcés qui limitent les fugues de Glace involontaires lors des conversations — sans eux, les gens près de lui accumulent du givre sur leurs vêtements.",
    "Cryal est fasciné par le moment de rupture : la seconde où une structure congelée, portée à son limite structurelle, se fracture en milliers d'éclats simultanément. Fracturation est son art. Il ne travaille pour personne en particulier parce que personne ne lui propose des cibles suffisamment intéressantes sur le plan technique. Ses missions acceptées sont celles qui lui permettent d'expérimenter de nouvelles configurations de Congélation avant de les briser.",
    "Chercheur indépendant et mercenaire de la physique des cristaux de Crysalme. Ses Fracturations ont détruit trois installations impériales et deux fortifications des Dissidentes — les deux fois que les Dissidentes l'ont engagé, il a accepté; les deux fois que l'Empire l'a approché, il a refusé parce que leurs cibles étaient trop faciles. Il vend ses services à qui lui propose un problème thermodynamique non-résolu.",
    "Cryal passe les premiers tours à Congeler stratégiquement — pas n'importe quelle case, mais les cases qui créent la structure cristalline optimale pour sa Fracturation. Tempête de Grêle pour maintenir la pression pendant la préparation. Quand la configuration est parfaite (3-4 cases Congélation adjacentes avec des ennemis dessus ou à côté), Fracturation déclenche — explosion de dégâts massifs amplifiés par Fragilité Cristalline sur chaque cible dans la zone. Âge de Glace pour finaliser.",
    "Fracturation de Cryal frappe toutes les cases Congélation et Patinoire adjacentes simultanément, pas seulement une. Congélation peut être lancée deux fois par tour si la première cible est déjà dans une zone de Glace. Tempête de Grêle a sa durée doublée et ses dégâts augmentés de 30%. Passif Résonance Cristalline : chaque case Congélation adjacent à une autre amplifie mutuellement leur effet — jusqu'à ×3 dégâts en chaîne."
))

write("src/data/characters/glace/066-kryss/index.ts", char_file(
    66, "Kryss", "Glace", "Battlemage", "Givrins", "Crysalme", "Empire",
    "Givrine aux traits sévères et à la posture de commandant militaire impérial — chaque détail de son apparence exprime la discipline. Sa peau présente des plaques de cristallisation autour de ses avant-bras et de ses épaules, résultat d'années de combat en armure de Glace qu'elle génère elle-même. Elle porte en permanence une lame d'acier tempéré dans une gaine de glace compressée à sa hanche — une lame standard, mais dont la poignée reste froide même en plein soleil.",
    "Kryss est l'Empire dans ses meilleures intentions : rigoureuse, efficace, convaincue que l'ordre prévient la souffrance. Elle a vu des Élus non encadrés se détruire et détruire les autres par ignorance de leur propre puissance. Sa méthode d'encadrement est sévère mais pas cruelle. Elle traite ses adversaires avec le même respect distant qu'elle accorderait à une force naturelle — pas personnellement hostile, juste à neutraliser.",
    "Officier de combat de l'Empire à Crysalme, responsable de la pacification des zones où des Élus Glace libres s'organisent en résistance. Sa technique combine la Glace défensive (Mur de Glace, Congélation) avec des frappes précises qui exploitent Fragilité Cristalline — elle congèle d'abord, frappe ensuite, avec des dégâts ×2.5. Verglass identifie les cibles, elle les neutralise.",
    "Kryss entre en mêlée après avoir congelé son périmètre — Congélation sur les cases adjacentes à sa position crée une zone de ralentissement permanent. Mur de Glace pour fermer les flancs. Souffle Glacial de contact déclenche Fragilité Cristalline sur la cible directement adjacente. Frappe physique amplifiée ×2.5 sur la cible congelée. Éclat de Glace pour les cibles qui gardent de la distance. Avalanche si encerclée.",
    "Dans les cases Congélation ou Patinoire, Kryss gagne +30% de résistance et ses dégâts physiques (contact) bénéficient de Fragilité Cristalline. Souffle Glacial peut être utilisé comme action gratuite après tout déplacement (pas de coût en PM). Éclat de Glace sur une cible congelée déclenche un deuxième Éclat automatique. Passif Armure Cristalline : à chaque début de tour dans une case Glace, regagne une couche d'armure équivalent à 8% PV max."
))

write("src/data/characters/glace/067-hiver-blanc/index.ts", char_file(
    67, "Borvax", "Glace", "Artillerie", "Givrins", "Crysalme", "Dissidentes",
    "Givrin dont la silhouette est difficile à évaluer sous ses couches de vêtements d'altitude — il porte toujours plusieurs épaisseurs, non pas par besoin thermique (il ne ressent pas le froid) mais pour dissimuler la préparation de ses lancements. Ses mains sont les seules parties visibles : larges, avec des articulations hyperboliques qui lui permettent de lancer des blocs de glace compressée à des distances théoriquement impossibles pour un non-élémentaire. Ses yeux sont d'un gris chargé, comme ciel de blizzard.",
    "Borvax pense en portées et en angles d'attaque. Il a mémorisé les trajectoires optimales de Tempête de Grêle pour chaque configuration de terrain possible à Crysalme et à Asterciel. Sa patience militaire est celle d'un homme qui a appris que le premier tir est rarement le bon mais que le cinquième l'est presque toujours. Les Dissidentes l'utilisent comme couverture à longue portée lors des extractions.",
    "Artilleur des Dissidentes pour les opérations glacées de Crysalme. Ses Tempêtes de Grêle couvrent des zones impossibles à atteindre par les mages au contact. Sa spécialité : créer une zone de Patinoire à longue portée (via son modificateur de portée) avant que les agents de terrain comme Frosta n'y pénètrent — les ennemis dans la Patinoire glissent et ne peuvent pas maintenir leurs positions défensives.",
    "Borvax commence par créer des Patinoires aux positions ennemies clés à portée maximale. Tempête de Grêle sur les zones congelées décuple les dégâts via Fragilité Cristalline. Éclat de Glace en ciblage précis sur les individus qui sortent de sa zone de tempête. Pont Glacé créé à longue portée pour laisser ses alliés traverser la zone hostile. Âge de Glace en ultime pour transformer tout le terrain en Patinoire généralisée.",
    "Patinoire a sa portée doublée (8 cases au lieu de 4). Tempête de Grêle peut être dirigée manuellement (choisit les cases dans la zone). Éclat de Glace a sa portée étendue à 10 cases. Passif Bombe de Givre : ses Éclats de Glace sur des cibles déjà dans une zone Glace créent des éclaboussures de gel qui congèlent les unités adjacentes à la cible."
))

write("src/data/characters/glace/068-shiryn/index.ts", char_file(
    68, "Shiryn", "Glace", "Tireur", "Néréides", "Thalassyr", "Indépendant",
    "Néréide dont la maîtrise de la Glace est venue de l'eau — elle a appris à congeler l'Eau en vol, créant des projectiles de glace à partir de gouttelettes d'eau ambiante. Sa peau présente les écailles bleues-vertes typiques des Néréides, mais avec des cristaux de givre incrustés le long de ses avant-bras — marques permanentes de son Éveil. Elle porte des lunettes de protection thermique contre ses propres rafales d'Éclats de Glace.",
    "Shiryn est mercenaire par logique économique : son élément de Glace est recherché dans des régions chaudes où il crée un avantage maximal, et elle facture en conséquence. Elle n'a pas de problème moral avec les factions — elle travaille pour qui propose le contrat le plus intéressant techniquement. Sa seule ligne rouge : elle ne congèle jamais des enfants.",
    "Tireuse à distance spécialisée dans les environnements non-glacés — Thalassyr, l'Isthme, Varkhôl — où sa Glace crée un avantage maximal sur des adversaires sans résistance au froid. Elle crée son propre terrain favorable en déplaçant l'humidité ambiante en cristaux et en étendant progressivement des zones Glace qui n'existent pas naturellement dans ces régions.",
    "Shiryn commence par placer des Patinoires à portée optimale de ses adversaires — dans des régions non-glacées, la surprise est totale. Éclat de Glace depuis sa position en arrière. Fragilité Cristalline exploitée par ses propres tirs : elle congèle puis frappe. Brume (si interaction Eau/Glace disponible) pour s'auto-dissimuler. Tempête de Grêle si plusieurs cibles se regroupent. Pont Glacé pour repositionnement.",
    "Éclat de Glace de Shiryn est son sort basique (sans CD) en mode Tireur. Ses dégâts d'Éclat augmentent de 5% par case Glace active sur la carte. Patinoire peut être créée sur une case Eau (conversion instantanée). Passif Tireur Cryogénique : chaque Éclat de Glace sur une cible non-congelée applique un stack de gel — après 3 stacks, la cible est Congelée automatiquement."
))

write("src/data/characters/glace/069-nevex/index.ts", char_file(
    69, "Névex", "Glace", "Assassin", "Givrins", "Crysalme", "Dissidentes",
    "Givrin dont la capacité à se déplacer silencieusement sur la glace est absolue — aucun craquement, aucune vibration, comme s'il glissait sur une couche d'air entre sa peau et la surface. Sa peau est d'un bleu si pâle qu'il devient presque invisible dans les environnements enneigés. Ses yeux sont d'un gris transparent qui ne réfléchit rien. Il ne porte aucun équipement qui produit du son — même ses vêtements sont d'un matériau de givre compressé qui n'a pas de bruit de frottement.",
    "Névex a appris à tuer sans laisser de trace thermique — ses cibles se figent dans la position où elles se trouvaient sans le moindre indice de comment la mort est arrivée. Il fait ça pour les Dissidentes parce qu'ils lui ont offert les cibles qu'il estime mériter ce traitement : les agents impériaux qui catalogisent les Élus par la force. Sa froideur n'est pas émotionnelle — c'est technique.",
    "Assassin des Dissidentes à Crysalme et au-delà, spécialisé dans l'élimination des agents de catalogisation impériaux. Sa méthode : créer une Patinoire autour de la cible (limitant ses déplacements), approcher via les zones de glace où il est invisible, appliquer Fracturation à courte portée pour un maximum de dégâts amplifiés par Fragilité Cristalline. Aucun corps ne porte de blessure visible — juste une vitrifaction soudaine.",
    "Névex crée en amont une Patinoire autour de la cible pour limiter ses routes de fuite. Il s'approche via les zones Glace où son profil thermique est indétectable. Souffle Glacial au contact déclenche Fragilité Cristalline. Éclat de Glace à bout portant depuis une position adjacente invisible. Fracturation si la cible est Congelée — dégâts maximaux. Il disparaît dans la Patinoire avant que les alliés de la cible comprennent.",
    "Souffle Glacial de Névex depuis une case Glace invisible est instantané (sans délai de lancement). Éclat de Glace tiré depuis une position adjacente à la cible inflige ×2.5 dégâts. Fracturation peut cibler une seule case (dégâts concentrés sur une cible au lieu de zone). Passif Invisibilité Cryogénique : dans une case Congélation ou Patinoire, Névex est invisible pour les ennemis à plus de 2 cases de distance."
))

write("src/data/characters/glace/070-glacen/index.ts", char_file(
    70, "Glacen", "Glace", "Escrimeur", "Givrins", "Crysalme", "Empire",
    "Givrin au maintien de duelliste impérial dont la particularité physique est une lame formée de glace compressée à une densité équivalente à l'acier — qu'il régénère et adapte en combat selon les besoins. Sa peau est d'un bleu gris uniforme, sans les craquelures des Givrins trop actifs. Ses yeux évaluent les adversaires avec la précision d'un géomètre. Porte une armure légère de cristal empilé sur les points vitaux — plus résistante que l'acier standard, plus légère aussi.",
    "Glacen est un technicien du duel. Il ne cherche pas la victoire rapide — il cherche la victoire propre, celle qui démontre la supériorité de technique sur la puissance brute. Sa loyauté à l'Empire vient de son respect pour les structures : un empire qui catalogue et encadre les Élus évite les catastrophes que génèrent les Élus non formés. Il a vu assez de destructions accidentelles pour en être convaincu.",
    "Duelliste d'élite de l'Empire déployé contre les agents des Dissidentes qui ont un profil de combat. Sa technique : créer une Patinoire contrôlée autour de l'espace de duel, puis utiliser sa supériorité de mobilité sur la glace (les non-Givrins glissent, lui non) pour dominer le corps à corps. Verglass lui identifie les adversaires dignes ; il les neutralise en duel officieux.",
    "Glacen définit l'espace de duel avec Patinoire — ses adversaires glissent, lui maintient sa stabilité parfaite de Givrin natif. Souffle Glacial de contact déclenche Fragilité Cristalline et ralentit. Éclat de Glace en riposte à distance si l'adversaire tente de s'échapper de sa Patinoire. Congélation sur la cible quand elle est ralentie. Fracturation finale avec dégâts ×2.5 via Fragilité Cristalline.",
    "Dans sa Patinoire, Glacen ne subit aucun malus de mouvement (maîtrise native). Souffle Glacial de Glacen en corps à corps ignore la résistance au Froid. Éclat de Glace tiré après un Souffle Glacial du même tour bénéficie automatiquement de Fragilité Cristalline. Passif Duelliste des Glaces : en combat contre une seule cible dans une zone Glace, ses sorts ont -1 tour de cooldown."
))

write("src/data/characters/glace/071-boryn/index.ts", char_file(
    71, "Boryn", "Glace", "Vanguard", "Givrins", "Crysalme", "Convergence",
    "Givrin d'une envergure de glacier — large, stable, avançant avec une inertie qui rend chaque tentative d'arrêt futile. Sa peau est d'une couleur de glace ancienne, légèrement verte, caractéristique des Givrins qui ont habité des profondeurs glacées. Des stalactites de givre se forment spontanément sur ses épaules et son casque lors des combats — non pas décoratifs mais fonctionnels, des lames de glace qui se brisent à l'impact pour causer des dégâts supplémentaires.",
    "Boryn incarne la conviction de la Convergence : l'énergie des Élus appartient au flux commun du monde, et résister à ce flux est aussi vain que résister à un glacier. Il n'est pas cruel — il est inévitable. Ses opérations de front de la Convergence dans les zones glacées sont documentées comme les moins violentes statistiquement, non pas parce qu'il évite la force, mais parce que ses adversaires capitulent souvent avant le contact.",
    "Avant-garde de la Convergence dans les zones glacées de Crysalme où des communautés d'Élus Glace tentent de maintenir leur indépendance. Boryn initie les avancées qui permettent aux équipes de la Convergence de s'établir dans des zones contrôlées par les Dissidentes. Sa Patinoire d'initiation transforme le terrain à son avantage avant même que l'ennemi réalise que l'avancée a commencé.",
    "Boryn initie avec Patinoire étendue sur la ligne ennemie — leurs positions défensives deviennent des pièges où ils glissent. Il avance dans sa Patinoire avec Mur de Glace sur les flancs pour concentrer l'ennemi devant lui. Avalanche quand les adversaires sont regroupés par sa Patinoire. Glacûrhn le suit derrière pour tenir ce que Boryn a déstabilisé. Âge de Glace comme ultime quand la ligne est rompue.",
    "Patinoire de Boryn s'étend de 1 case supplémentaire dans toutes les directions à chaque tour qu'il avance. Il n'a aucun malus de mouvement dans sa propre Patinoire. Mur de Glace peut être lancé en mouvement (sans s'arrêter). Avalanche lancée depuis sa Patinoire a son rayon doublé. Passif Avancée Glaciaire : chaque case qu'il traverse se congèle automatiquement pendant 2 tours."
))

write("src/data/characters/glace/072-tundra/index.ts", char_file(
    72, "Tundra", "Glace", "Gardien", "Givrins", "Crysalme", "Dissidentes",
    "Givrine massive dont la présence dans une pièce fait baisser la température ambiante de plusieurs degrés — une manifestation passive de sa maîtrise qui n'a jamais été contrôlée et qu'elle ne cherche plus à contrôler. Sa peau est d'un blanc pur avec des veines bleues visibles, caractéristique des Givrins les plus anciens dans la lignée. Ses yeux sont de la couleur de la glace polaire — un bleu presque blanc. Elle parle rarement, et quand elle parle, sa voix semble venir de loin, comme le vent à travers une crevasse.",
    "Tundra protège comme une toundra protège — pas activement, mais par sa nature même. Ceux qui entrent dans son rayon de protection survivent parce qu'elle leur est hostile à elle-même : elle absorbe ce qui les menaçait. Sa loyauté aux Dissidentes est née de la protection : son village givrin a été le premier à cacher des Élus fugitifs quand les purges ont commencé. Elle était là. Elle y est restée.",
    "Gardienne des refuges souterrains glacés des Dissidentes dans les profondeurs de Crysalme — des grottes naturelles transformées en abris par des décennies de Congélation stratégique qui maintient une température stable. Ses Murs de Glace ne sont pas des fortifications — ils sont des architectures d'abri. Chaque refuge qu'elle construit peut accueillir trente Élus fugitifs pendant une saison.",
    "Tundra crée des Murs de Glace défensifs en architecture concentriques — pas une muraille plate mais une structure qui absorbe les impacts dans plusieurs couches. Congélation sur tout ennemi qui approche à portée. Pont Glacé pour créer des routes de fuite pour les protégés. Avalanche si la ligne est percée. Souffle Glacial sur les assaillants au contact. Âge de Glace en dernier recours — transforme tout en terrain Glace qu'elle maîtrise parfaitement.",
    "Mur de Glace de Tundra résiste à 3 fois plus de dégâts et régénère 10% de sa résistance par tour. Congélation sur un attaquant redirige 30% des dégâts de cet attaquant vers lui-même (gelure des propres énergies). Pont Glacé créé par Tundra peut être traversé par des non-Élus sans risque. Passif Gardienne du Froid : les alliés dans un rayon de 3 cases reçoivent 25% moins de dégâts élémentaires tant qu'elle est debout."
))

write("src/data/characters/glace/073-la-tempete-blanche/index.ts", char_file(
    73, "La Tempête Blanche", "Glace", "Spécialiste", "Aérides", "Asterciel", "Indépendant",
    "Aéride dont l'identité physique est devenue secondaire à l'effet qu'elle produit — un givre permanent à 1 mètre autour d'elle en toutes circonstances, une aura de cristallisation qui transforme l'humidité de l'air en neige fine à tout moment. On ne voit pas son visage distinctement à cause de cette brume de givre permanente. Ses ailes vestigiales se sont développées au-delà de la normale — non pas assez pour voler, mais assez pour créer des courants d'air glacé qu'elle dirige. Sa voix porte à travers sa propre tempête sans effort apparent.",
    "La Tempête Blanche ne se définit pas comme un individu — elle se définit comme un phénomène météorologique avec une conscience. Cette perspective lui donne une forme de sérénité absolue face aux conflits entre factions : elle voit tout depuis la hauteur où les distinctions humaines disparaissent. Elle intervient quand la Glace elle-même est menacée, pas quand des humains se disputent.",
    "Phénomène climatique ambulant qu'Asterciel et Crysalme se disputent la paternité depuis des décennies. La Tempête Blanche était initialement une Aéride nommée différemment — les archives divergent. Sa transformation en phénomène permanent a commencé lors d'une Tempête de Grêle ratée qui a duré trois jours. Depuis, elle est ce qu'elle a créé. Toutes les factions lui ont offert alliance et toutes ont reçu le même silence.",
    "La Tempête Blanche agit depuis partout dans la zone Glace qu'elle crée. Âge de Glace permanent transforme tout le champ en son domaine. Tempête de Grêle depuis n'importe quelle case Glace sur la carte. Fracturation en chaîne sur toutes les structures cristallines existantes. Avalanche multidirectionnelle. Elle ne se positionne pas — elle est présente dans chaque case Glace.",
    "Peut lancer tous ses sorts depuis n'importe quelle case Glace sur la carte. Âge de Glace est permanent tant qu'elle combat. Tempête de Grêle peut cibler simultanément 3 zones différentes. Passif Tempête Perpétuelle : chaque tour, toutes les cases Glace s'étendent de 1 case dans une direction aléatoire — son terrain croît constamment."
))

print("Glace: 13 characters written")

# =============================================================================
# ELECTRIQUE — Impulsion · Innovation · Réseaux · Connexion instantanée
# Spells: Arc Électrique, Charge, Éclair, Court-Circuit, EMP, Batterie Géante,
#         Tempête Statique, Transfert, Surcharge Totale, ULTIME — Tempête de Foudre
# Passifs: Conductivité (dégâts electrique se propagent), Surcharge (sur-kill → explosion)
# Species: Aérides/Asterciel, Hommes-Liens/Isthme, Umbriens/Noctéa
# =============================================================================

write("src/data/characters/electrique/091-volta/index.ts", char_file(
    91, "Volta", "Electrique", "Enchanteur-Soutien", "Aérides", "Asterciel", "Dissidentes",
    "Aéride aux cheveux perpétuellement dressés par une charge électrostatique qui ne se dissipe jamais complètement. Sa peau est d'un brun doré caractéristique des Aérides d'Asterciel, avec des arborescences de Lichtenberg bleues visibles aux avant-bras et au cou — marques de foudre interne canalisée. Ses yeux sont d'un jaune électrique intense qui luisent légèrement dans l'obscurité. Elle parle vite, bouge vite, et a apparemment oublié ce que c'est que de s'asseoir.",
    "Volta croit que l'électricité partage ses propriétés avec l'information : elle connecte, accélère, synchronise. Son rôle de soutien est celui d'un nœud de réseau — elle s'assure que chaque allié reçoit exactement l'impulsion dont il a besoin au bon moment. Sa nervosité visible est une manifestation de ce principe : elle est toujours en train de traiter plusieurs flux simultanément.",
    "Ingénieure de réseau des Dissidentes à Asterciel, responsable de la maintenance des systèmes de communication électrique que les Dissidentes utilisent pour coordonner leurs réseaux d'exfiltration dans des conditions où la transmission magique est surveillée. Ses Batteries Géantes alimentent les relais de communication clandestins d'Asterciel. Elle maintient en état de fonctionnement un réseau que l'Empire cherche à court-circuiter.",
    "Volta commence par déployer une Batterie Géante sur la position centrale de l'équipe — tous les alliés dans son rayon gagnent des bonus de PM par tour. EMP pour neutraliser les sorts défensifs ennemis coûteux avant les offensives de ses alliés. Arc Électrique via Conductivité se propage entre les cibles ennemies proches. Transfert pour repositionner un allié en danger. Tempête Statique comme couverture si la ligne est percée.",
    "Batterie Géante de Volta double le gain de PM de ses alliés dans le rayon et peut être rechargée à distance. EMP de Volta neutralise également les passifs ennemis pendant 2 tours. Transfert peut être utilisé sur un allié (pas seulement sur elle-même) — repositionnement d'urgence jusqu'à 8 cases. Passif Nœud de Réseau : ses Arc Électriques se propagent entre alliés aussi bien qu'entre ennemis, transmettant des bonus plutôt que des dégâts."
))

write("src/data/characters/electrique/092-arkyn/index.ts", char_file(
    92, "Arkyn", "Electrique", "Enchanteur-Capteur", "Aérides", "Asterciel", "Empire",
    "Aéride dont la maîtrise de l'électricité s'exprime dans une précision technique qui contraste avec la nature chaotique de son élément. Sa peau ne porte pas d'arborescences de Lichtenberg — les décharges qu'il produit sont trop contrôlées pour laisser des marques. Il porte des gants de capture électrique qui lui permettent de maintenir des charges en tension sans les libérer, créant une menace permanente visible. Ses yeux sont calmes, méthodiques — ceux d'un analyste, pas d'un combattant.",
    "Arkyn est l'Empire dans sa fonction de catalogue : identifier, analyser, catalogiser. Son Électrique sert à localiser les Élus à travers leur signature électromagnétique — chaque Élu émet une fréquence distinctive que ses instruments captent à distance. Sa conviction est sincère : un Élu non catalogisé est comme un circuit sans cartographie — dangereux pour lui-même.",
    "Agent de renseignement électromagnétique de l'Empire à Asterciel. Son Court-Circuit peut désactiver temporairement les manifestations élémentaires d'un Élu — une forme de capture non-léthale qu'il préfère à la force directe. Il a catalogisé trente-sept Élus en cinq ans d'opérations, tous sans violence significative. Volta lui échappe depuis trois ans — leurs fréquences ne correspondent pas.",
    "Arkyn repère ses cibles via EMP préventif qui révèle les signatures électriques de tous les Élus dans son rayon. Court-Circuit sur la cible prioritaire pour désactiver ses capacités élémentaires pendant 3 tours. Arc Électrique pour maintenir la pression. Batterie Géante comme piège — attire les ennemis qui croient en bénéficier. Transfert pour se repositionner si la cible contre-attaque. Éclair pour les cibles en fuite.",
    "EMP d'Arkyn révèle les signatures électriques de toutes les unités (cachées ou non) dans un rayon de 8. Court-Circuit de Arkyn dure 3 tours et cible les passifs élémentaires en priorité. Arc Électrique propagé via Conductivité partage également les effets de Court-Circuit entre cibles connectées. Passif Analyse Électromagnétique : il voit les cooldowns et PM actuels de toutes les unités dans son rayon."
))

write("src/data/characters/electrique/093-thormass/index.ts", char_file(
    93, "Thormass", "Electrique", "Juggernaut", "Aérides", "Asterciel", "Convergence",
    "Aéride d'une carrure inhabituelle pour son peuple — les Aérides tendent vers le léger, lui est dense, compact, avec une musculature qui contredit l'image aérienne de son espèce. Sa peau est parcourue d'arborescences de Lichtenberg permanentes sur tout son corps — résultat de sa première Surcharge Totale non contrôlée à l'adolescence. Ces marques lui donnent l'apparence d'un être dessiné par la foudre elle-même. Ses yeux ne clignotent presque jamais.",
    "Thormass croit que la Convergence a raison pour des raisons différentes de celles qu'elle avance publiquement. La vraie raison, selon lui : un Élu électrique isolé finit par attirer la foudre sur son environnement. La puissance non partagée se retourne sur elle-même. Il en sait quelque chose — sa première Surcharge a failli le tuer et a tué un ami. La Convergence lui évite de recommencer.",
    "Vétéran de campagnes électriques de la Convergence dans les zones d'Asterciel où des groupes d'Élus Electrique tentent de maintenir des réseaux d'indépendance. Sa Surcharge Totale peut court-circuiter des systèmes électriques entiers — installations de surveillance impériales ou réseaux des Dissidentes, selon le camp qui s'y est installé. Il frappe les deux si nécessaire.",
    "Thormass avance avec Charge pour accélérer vers la ligne ennemie. Arc Électrique via Conductivité se propage entre les adversaires regroupés — tout groupe dense subit des dégâts en chaîne. Batterie Géante sur sa position pour alimenter sa Surcharge Totale. Tempête Statique pour maintenir le contrôle de zone. Surcharge Totale sur tout le champ une fois la Batterie chargée — dégâts globaux massifs.",
    "Charge de Thormass déclenche un Arc Électrique automatique sur la cible d'impact et les unités adjacentes. Tempête Statique créée par Thormass gagne +50% de dégâts par Batterie Géante active dans le rayon. Surcharge Totale de Thormass peut être chargée pendant 2 tours pour doubler son effet. Passif Conducteur Massif : toutes les cases que Thormass traverse deviennent des cases Charge (cases électriques actives) pendant 3 tours."
))

write("src/data/characters/electrique/094-spark/index.ts", char_file(
    94, "Spark", "Electrique", "Plongeur", "Aérides", "Asterciel", "Dissidentes",
    "Aéride jeune dont la maîtrise de l'électricité est intuitive et explosive — elle ne réfléchit pas avant d'agir, elle agit, et les éclairs suivent. Sa peau est d'un bronze lumineux avec des éclats de lumière électrique qui se produisent involontairement lors d'émotions fortes. Ses cheveux sont perpétuellement en mouvement même sans vent. Elle porte des équipements légers et peu d'armure — la vitesse est sa seule protection.",
    "Spark est enthousiaste à une intensité qui déstabilise les gens calmes. Elle croit sincèrement que chaque mission est la plus importante qu'elle ait jamais faite, ce qui la rend parfois imprudente et souvent décisive. Sa loyauté aux Dissidentes est viscérale — son frère aîné est dans leur réseau, et tant qu'il y sera, elle aussi.",
    "Agent de terrain des Dissidentes à Asterciel spécialisée dans les interventions rapides — elle est là et partie avant que l'adversaire ait compris ce qui s'est passé. Son Transfert utilisé sur elle-même lui permet de traverser des lignes en une seconde. Volta la couvre depuis l'arrière, elle plonge.",
    "Spark utilise Transfert pour se téléporter directement sur la cible prioritaire. Arc Électrique au contact déclenche Conductivité qui se propage aux alliés ennemis adjacents. Court-Circuit pour désactiver la réponse élémentaire immédiate de la cible. Charge si la téléportation n'est pas disponible. Éclair en fuite pour ralentir les poursuivants. Elle ne reste jamais plus d'un tour au même endroit.",
    "Transfert de Spark peut être utilisé une fois par tour sans cooldown (son déplacement de base). Arc Électrique après Transfert déclenche automatiquement Conductivité sans coût supplémentaire. Court-Circuit lancé depuis la même case que la cible (distance 0) neutralise également les passifs pour 2 tours. Passif Éclair Vivant : chaque déplacement via Transfert laisse une trace électrique — les ennemis qui traversent ces cases dans les 2 tours suivants reçoivent des dégâts."
))

write("src/data/characters/electrique/095-fulgur/index.ts", char_file(
    95, "Fulgur", "Electrique", "Mage-Burst", "Aérides", "Asterciel", "Indépendant",
    "Aéride dont l'électricité s'accumule avant d'exploser — son corps porte l'aspect d'un condensateur vivant : des zones de peau qui s'illuminent progressivement au fur et à mesure qu'il charge son énergie, passant du bleu pâle au blanc intense avant la décharge. Ses arborescences de Lichtenberg sont dynamiques — elles changent de motif selon le niveau de charge. Il porte des vêtements anti-statiques spéciaux pour éviter de se décharger accidentellement lors des déplacements.",
    "Fulgur est un perfectionniste de la décharge optimale. Il peut attendre des heures dans la position de charge parfaite pour un seul tir de Surcharge Totale au moment précis. Cette patience extrême le rend indépendant — aucune faction ne peut lui donner des objectifs qui correspondent à ses critères de timing précis. Il accepte des contrats où les paramètres lui permettent de choisir le moment.",
    "Mercenaire électrique indépendant dont la réputation repose sur une statistique : ses Surcharges Totales ont un taux de neutralisation de 100% sur les cibles qu'il a visées. Le secret : il ne tire jamais sans être sûr. Ce qui implique qu'il peut passer deux heures à charger sans attaquer, pendant lesquelles Volta ou ses alliés doivent protéger sa position.",
    "Fulgur se place en position protégée derrière ses alliés. Batterie Géante pour alimenter sa charge. Arc Électrique et Charge accumulés pour maximiser les stacks. Quand les conditions sont optimales (ennemis regroupés, Conductivité activée, maximum de Batteries actives), Surcharge Totale — décharge globale qui traverse tout le champ via Conductivité. Court-Circuit préventif sur les cibles qui pourraient interrompre sa charge.",
    "Surcharge Totale de Fulgur peut être chargée pendant 3 tours pour tripler son effet. Chaque Batterie Géante active sur la carte augmente ses dégâts de 30%. Conductivité propagée depuis sa Surcharge Totale atteint toutes les unités ennemies sur la carte (pas seulement adjeacentes). Passif Accumulation Maximale : chaque tour sans attaquer augmente ses prochains dégâts de 20% (max ×4)."
))

write("src/data/characters/electrique/096-elexyn/index.ts", char_file(
    96, "Elexyn", "Electrique", "Battlemage", "Aérides", "Asterciel", "Empire",
    "Aéride à l'allure de stratège militaire — uniforme impérial adapté pour laisser les bras libres, avec des plaques conductrices intégrées dans les épaulettes qui amplifient ses décharges de contact. Sa peau porte des arborescences fines et contrôlées, signe d'un Électrique discipliné par des années de formation impériale. Ses yeux évaluent en permanence les distances et les angles de propagation — Conductivité est une question de géométrie autant que de magie.",
    "Elexyn est convaincu que l'Électrique est l'élément de la civilisation — les réseaux, les systèmes, les connexions qui rendent le collectif possible. L'Empire, selon lui, est ce réseau à l'échelle politique. Travailler pour l'Empire, c'est travailler pour l'interconnexion du monde. Cette conviction sincère le rend efficace et légèrement dogmatique.",
    "Officier de terrain de l'Empire à Asterciel, spécialisé dans la disruption des réseaux de communication clandestins que les Dissidentes maintiennent via l'électricité. Ses Court-Circuits peuvent désactiver les relais de Volta — ce qu'Arkyn ne peut pas faire seul. Ensemble, ils forment une équipe de suppression qui isole les Dissidentes électriques de leurs réseaux.",
    "Elexyn entre en mêlée avec Charge pour projeter la cible hors de son réseau allié. Arc Électrique au contact déclenche Conductivité propagée. Court-Circuit sur la cible pour désactiver sa connexion à sa Batterie Géante alliée. Tempête Statique pour contrôle de zone persistant. Batterie Géante sur sa position pour ses propres bonus. EMP préventif sur les positions de communication ennemies.",
    "Court-Circuit d'Elexyn désactive également les Batteries Géantes ennemies dans un rayon de 3. Arc Électrique de contact déclenche Conductivité sur un rayon de 3 cases (portée amplifiée). Tempête Statique créée pendant une Batterie Géante active a ses dégâts doublés. Passif Réseau Tactique : les alliés Électrique dans un rayon de 5 partagent leurs stacks de Conductivité avec lui."
))

write("src/data/characters/electrique/097-bolte/index.ts", char_file(
    97, "Bolte", "Electrique", "Artillerie", "Umbriens", "Noctéa", "Dissidentes",
    "Umbrien dont la maîtrise de l'Électrique contraste avec l'aspect typique de son peuple — sa peau sombre porte des arborescences de Lichtenberg bleues lumineuses qui font de lui l'opposé d'un Umbrien discret. Il a accepté cette visibilité comme compromis nécessaire : son rôle d'artillerie électrique ne permet pas l'invisibilité. Ses mains sont couvertes de gants conducteurs renforcés qui amplifient la portée de ses Éclairs. Il porte des protections oculaires contre ses propres éclairs à longue portée.",
    "Bolte est une anomalie culturelle à Noctéa — un Umbrien qui accepte d'être visible. Sa théorie : si tu dois être vu de toute façon (l'électricité n'est pas discrète), autant en faire un avantage tactique. Sa présence lumineuse attire l'attention ennemie vers lui pendant que ses alliés umbriens opèrent dans l'ombre. Les Dissidentes l'utilisent précisément comme distraction lumineuse.",
    "Artilleur des Dissidentes à Noctéa dont la visibilité électrique est un outil tactique délibéré. Ses Éclairs à longue portée couvrent les opérations des agents des Ténèbres qui travaillent dans les zones sombres. Sylvara et Onyx opèrent dans ses ombres portées pendant qu'il absorbe l'attention impériale avec ses arborescences lumineuses.",
    "Bolte déploie Batterie Géante à sa position pour alimenter ses frappes longue portée. Éclair sur les cibles prioritaires identifiées par Arkyn (partage de données entre éléments Electrique). Tempête Statique pour maintenir la pression de zone. Court-Circuit sur les cibles qui tentent d'utiliser des sorts de détection. Surcharge Totale quand la Batterie est pleine. Sa position lumineuse attire les ennemis loin des opérations de Ténèbres en cours.",
    "Éclair de Bolte a sa portée étendue à 10 cases et peut ricocher entre 2 cibles via Conductivité. Tempête Statique peut être déployée à 8 cases de distance (sans limite de ligne de vue). Batterie Géante de Bolte se charge deux fois plus vite. Passif Attrait Électrique : sa présence lumineuse augmente la probabilité que les ennemis le ciblent lui plutôt que ses alliés non-lumineux de 40% — bouclier involontaire."
))

write("src/data/characters/electrique/098-zelyne/index.ts", char_file(
    98, "Zelyne", "Electrique", "Tireur", "Aérides", "Asterciel", "Indépendant",
    "Aéride fine dont les cheveux ont été entièrement remplacés par des filaments d'électricité statique permanente — non pas une coiffure, mais une manifestation physique de son contrôle de l'Électrique. Elle ne peut pas les toucher sans décharge. Sa peau est d'un bronze clair, presque dorée, avec des arborescences très fines qui ressemblent à des circuits imprimés. Ses yeux sont d'un ambre électrique. Elle porte des équipements de précision sur les poignets qui lui permettent de calibrer l'intensité de ses Arc Électriques.",
    "Zelyne est mercenaire parce que l'indépendance lui permet de refuser les cibles qu'elle juge non méritées. Elle a une liste personnelle de critères d'acceptation de contrats — aucune cible civile, aucune cible non-élémentaire, jamais de missions de suppression de communautés. Dans ces limites, elle travaille pour qui paie.",
    "Tireuse électrique indépendante d'Asterciel dont les Arc Électriques de précision peuvent atteindre des cibles à des distances où les autres Électriques ne peuvent plus maintenir la cohérence du sort. Sa particularité : elle utilise Conductivité non pas pour propager les dégâts mais pour créer des réseaux de connexion entre ses propres positions et ses cibles — un câblage invisible qui lui permet de déclencher des décharges à retardement.",
    "Zelyne place des balises électriques à distance via Arc Électrique qui ne se déchargent pas immédiatement mais attendent un signal. Batterie Géante pour alimenter les décharges multiples. Quand plusieurs balises sont en place, elle déclenche simultanément via Surcharge partielle — toutes les balises se déchargent en même temps. Court-Circuit sur les cibles qui tentent de neutraliser ses balises. Transfert pour repositionnement rapide.",
    "Arc Électrique de Zelyne peut être réglé en mode 'balise' — il se pose sur la cible sans dégâts, et se décharge au moment choisi (max 3 tours plus tard). Elle peut maintenir jusqu'à 5 balises actives simultanément. Conductivité se propage depuis ses balises plutôt que depuis sa position. Passif Réseau de Foudre : lorsque 3 balises ou plus se déchargent simultanément, l'effet de Surcharge Totale est déclenché automatiquement."
))

write("src/data/characters/electrique/099-electra/index.ts", char_file(
    99, "Électra", "Electrique", "Assassin", "Umbriens", "Noctéa", "Dissidentes",
    "Umbrienne dont la peau sombre porte des arborescences de Lichtenberg d'un bleu particulièrement vif — le contraste est saisissant, presque artistique. Elle a appris à les contrôler au point de les éteindre complètement pour se fondre dans les zones sombres de Noctéa, et à les allumer brusquement pour aveugler temporairement des adversaires au contact. Ses mouvements sont d'une économie absolue — chaque geste est calculé pour la vitesse maximale.",
    "Électra est à la croisée de deux éléments dans son opératoire : l'invisibilité de l'Umbrien et la vitesse de l'Électrique. Elle utilise l'ombre pour approcher et l'électricité pour frapper. Sa loyauté aux Dissidentes est émotionnelle — elle a grandi dans un réseau de protection des Élus et n'a jamais connu autre chose que cette solidarité.",
    "Assassine des Dissidentes à Noctéa spécialisée dans l'élimination rapide des agents impériaux qui entrent dans les zones sombres en pensant y être à l'abri. Elle inverse l'avantage : dans l'obscurité, ses éclairs sont exponentiellement plus visibles et donc plus déstabilisants. Elle allume les arborescences au moment de l'impact pour l'effet de désorientation maximum.",
    "Électra approche dans les zones d'ombre de Noctéa (arborescences éteintes, Umbrien standard). Au moment optimal, elle allume ses arborescences pour aveugler la cible au contact. Arc Électrique à bout portant déclenche Conductivité sur les alliés adjacents. Court-Circuit pour désactiver la réponse élémentaire de la cible. Transfert pour sortir avant que les alliés ennemis réagissent. Éclair en fuite si poursuivie.",
    "Ses arborescences peuvent être activées comme attaque de lumière aveuglante (rayon 2, aveugle 1 tour). Arc Électrique à portée 1 (contact) déclenche Court-Circuit simultanément sans coût PM supplémentaire. Transfert de Électra peut cibler une case Ombre (zone Ténèbres) comme destination. Passif Double Nature : dans une zone Ténèbres, ses arborescences sont invisibles — elle peut approcher sans signature électrique détectable."
))

write("src/data/characters/electrique/100-chayn/index.ts", char_file(
    100, "Châyn", "Electrique", "Escrimeur", "Aérides", "Asterciel", "Empire",
    "Aéride dont le style de combat a intégré l'électricité dans chaque technique martiale — ses frappes portent une charge électrique qui s'ajoute aux dégâts physiques. Sa peau porte des arborescences de Lichtenberg aux mains et aux avant-bras, particulièrement denses aux points d'impact de ses frappes. Il porte une armure légère de plumes conductrices — une adaptation aéride qui lui permet de distribuer les décharges sur toute sa surface plutôt que de les concentrer.",
    "Châyn est l'Empire comme idéal de maîtrise — la discipline au service de la précision. Son électricité n'est jamais chaotique : chaque décharge est mesurée, ciblée, économe. Il serve l'Empire parce que l'Empire lui offre les adversaires les plus complexes à vaincre techniquement. Sa loyauté est esthétique autant qu'idéologique.",
    "Duelliste d'élite de l'Empire à Asterciel, responsable de la neutralisation d'agents des Dissidentes qui ont un profil de combat supérieur. Sa particularité : il n'utilise jamais deux fois la même séquence dans un duel — chaque combat est une improvisation au sein d'une structure maîtrisée. Arkyn l'identifie les cibles, Châyn les neutralise en combat direct.",
    "Châyn engage en Corps à corps avec Arc Électrique intégré dans chaque frappe — Conductivité se propage via ses impacts physiques. Court-Circuit sur la cible quand elle tente d'utiliser ses capacités élémentaires. Charge pour projeter et repositionner un adversaire dans une zone défavorable. Tempête Statique de zone si multiple adversaires. Transfert pour se repositionner instantanément autour de sa cible.",
    "Ses frappes physiques déclenchent Arc Électrique automatiquement (en plus de leurs dégâts normaux). Court-Circuit de Châyn peut interrompre un sort en cours de lancement ennemi. Charge peut être utilisée vers le bas ou vers le haut (verticalement). Passif Duelliste Conducteur : chaque échange de frappes avec la même cible accumule des stacks de Conductivité — après 3 échanges, Surcharge automatique sur la cible."
))

write("src/data/characters/electrique/102-egide-foudre/index.ts", char_file(
    102, "Aeglyn", "Electrique", "Gardien", "Aérides", "Asterciel", "Dissidentes",
    "Aéride d'une envergure imposante dont la particularité principale est une aura électrique passive — un champ électrostatique permanent dans un rayon d'un mètre qui dévie les projectiles non-conducteurs et absorbe les impacts magiques de faible intensité. Sa peau est couverte d'arborescences de Lichtenberg uniformément réparties sur tout son corps, signe d'une maîtrise diffuse plutôt que concentrée. Ses yeux sont d'un jaune lumineux stable qui ne s'intensifie jamais — la constance est son identité.",
    "Aeglyn protège sans discrimination — son champ électrostatique s'applique à tous les alliés dans son rayon, quel que soit leur élément. Cette égalité dans la protection lui a valu une réputation de neutralité qui attire des agents des Dissidentes de tous les éléments. Il n'est pas politique — il est fonctionnel.",
    "Gardien des points de ralliement des Dissidentes à Asterciel — les positions où les agents convergent entre opérations. Son champ électrostatique crée une zone de sécurité que les agents impériaux ne peuvent pas pénétrer sans déclencher une alerte. Volta l'utilise comme point d'ancrage de son réseau de Batteries Géantes.",
    "Aeglyn maintient Batterie Géante active sur sa position en permanence — elle alimente à la fois ses alliés et son propre champ défensif. EMP préventif sur les zones d'approche ennemies. Arc Électrique sur les agents qui pénètrent malgré tout dans sa zone de protection. Tempête Statique si la position est assaillie massivement. Il ne quitte jamais sa position de gardien.",
    "Son champ électrostatique passif dévie 25% de tous les dégâts à distance sur lui et ses alliés dans un rayon de 2. EMP d'Aeglyn peut être maintenu en continu (consomme PM par tour) plutôt que ponctuellement. Batterie Géante d'Aeglyn ne peut pas être court-circuitée par des effets ennemis. Passif Champ de Protection : les alliés dans son rayon de 3 bénéficient d'une résistance à l'Électrique de 40% et absorbent 10% des dégâts Électriques pour les convertir en PM."
))

write("src/data/characters/electrique/103-le-conducteur/index.ts", char_file(
    103, "Le Conducteur", "Electrique", "Spécialiste", "Hommes-Liens", "Isthme", "Indépendant",
    "Homme-Lien dont le corps est devenu un circuit vivant — les arborescences de Lichtenberg couvrent 90% de sa surface corporelle, y compris le visage, formant un réseau si dense qu'il ressemble à une carte de câblage plutôt qu'à une peau humaine. Il ne génère pas l'électricité : il la conduit, la redirige, l'amplifie depuis des sources externes. Dans une zone sans source électrique, il est ordinaire. Dans une zone avec Batteries Géantes et Tempêtes Statiques, il est indestructible.",
    "Le Conducteur n'a pas d'identité indépendante de son réseau. Il est ce que le réseau lui permet d'être — plus de Batteries actives, plus de puissance; moins de Batteries, moins d'existence. Cette dépendance lui a appris la valeur de la construction systémique plutôt que de la puissance individuelle. Il sert n'importe quelle faction qui comprend ce principe.",
    "Phénomène unique parmi les Hommes-Liens de l'Isthme. Son Éveil électrique n'a pas créé la capacité de générer de l'électricité — il a créé la capacité de la conduire parfaitement depuis n'importe quelle source dans un rayon de 10 cases. Il est le nœud central de tout réseau électrique actif. L'Empire, les Dissidentes et la Convergence se disputent régulièrement son service.",
    "Le Conducteur ne génère rien — il amplifie et redirige. Il centralise tout le réseau électrique allié : toutes les Batteries Géantes, toutes les Tempêtes Statiques, tous les Arc Électriques convergent vers lui et il les redistribue où ils sont le plus efficaces. Surcharge Totale depuis lui-même avec l'énergie de tout le réseau simultanément est sa signature absolue.",
    "Peut rediriger n'importe quel sort Électrique d'un allié vers n'importe quelle cible dans son rayon (amplificateur de réseau). Toutes les Batteries Géantes alliées doublent leur production quand il est dans leur rayon. Surcharge Totale canalisée depuis le réseau entier décuple ses dégâts. Passif Supraconducteur : l'électricité ne lui inflige jamais de dégâts — au lieu de ça, elle le soigne à 50% des dégâts qu'il aurait dû recevoir."
))

print("Electrique: 13 characters written (note: 101-korryn kept, written separately)")

# =============================================================================
# PLANTE — Croissance · Fertilité · Symbiose · Propagation · Patience
# Spells: Vrille, Croissance, Camouflage, Mur de Ronces, Pont de Lianes,
#         Spores, Parasitage, Forêt Instantanée, Plante Carnivore, ULTIME — Jungle Primordiale
# Passifs: Régénération Naturelle (soigne en cases Plante), Prolifération (cases Plante se propagent)
# Species: Sylvans/Sylvera, Chthoniens/Ormn-Dur
# =============================================================================

write("src/data/characters/plante/121-sylvara/index.ts", char_file(
    121, "Sorvane", "Plante", "Enchanteur-Soutien", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvane aux cheveux composés de lianes vivantes qui se déplacent légèrement même sans vent, répondant aux humeurs et aux intentions plutôt qu'à la physique ordinaire. Sa peau est d'un vert-brun de terre forestière, avec des motifs de feuilles nervurées qui deviennent visibles en lumière oblique. Elle porte des vêtements de fibres végétales tressées qui poussent lentement — ses tenues changent de forme au fil des mois, grandissant plutôt que s'usant. Ses yeux sont d'un vert profond et immobile comme une forêt par temps calme.",
    "Sorvane croit que soutenir est la forme de présence la plus fondamentale — les racines qui permettent à l'arbre de pousser ne se vantent pas d'être indispensables. Elle déteste la gloire individuelle des combattants offensifs non pas par jalousie mais par conviction que le collectif est toujours plus que la somme de ses parties. Les Dissidentes l'ont reconnue pour cette conviction.",
    "Coordinatrice des réseaux végétaux de communication et de refuges des Dissidentes à Sylvera — les arbres-mémoire qui transmettent les messages entre agents, les racines-tunnels qui permettent les déplacements clandestins. Ses Ponts de Lianes ne sont pas temporaires : elle en a tissé un réseau permanent sous Sylvera qui dure depuis dix ans et que l'Empire ne peut pas détecter.",
    "Sorvane commence par Croissance — des cases Plante en réseau sur les positions de ses alliés, leur donnant Régénération Naturelle. Camouflage sur les agents qui ont besoin de discrétion. Pont de Lianes pour relier les positions et permettre des déplacements rapides. Mur de Ronces sur les approches ennemies. Plante Carnivore sur les positions défensives critiques. Thornax et Virold la protègent pendant qu'elle tisse le terrain.",
    "Croissance crée 3×3 cases Plante et les alliés dedans régénèrent 8% PV par tour (double du normal). Pont de Lianes de Sorvane peut être parcouru par tous les alliés sans coût de PM. Mur de Ronces créé par Sorvane soigne également les alliés adjacents de 5% PV par tour. Passif Nœud de Sylvera : ses Ponts de Lianes persistent jusqu'à destruction active — ils ne disparaissent pas à la fin de leur durée normale."
))

write("src/data/characters/plante/122-epine-noire/index.ts", char_file(
    122, "Spinyx", "Plante", "Enchanteur-Capteur", "Sylvans", "Sylvera", "Empire",
    "Sylvan dont l'apparence physique reflète sa spécialisation — des épines de bois noir acéré poussent naturellement de ses épaules, ses avant-bras et le dos de ses mains, les rétractant ou les déployant à volonté. Sa peau est d'un brun sombre parsemé de motifs qui ressemblent à de l'écorce striée, plus sombre que la majorité des Sylvans. Il porte ces épines comme ornements autant que comme armes, et les réarrange selon ses humeurs avec la désinvolture d'un être accoutumé à ce que son corps soit une extension de sa volonté.",
    "Spinyx croit dans l'Empire pour des raisons pragmatiques : la structure impériale est la seule qui lui permet d'exercer sa maîtrise des Ronces dans un cadre légal. Sans encadrement, ses pièges seraient illégaux dans la majorité des régions. L'Empire lui fournit le mandat pour opérer. Sa loyauté est contractuelle mais sincère dans les termes de ce contrat.",
    "Agent de terrain de l'Empire à Sylvera spécialisé dans la capture d'Élus Plante qui refusent la catalogisation. Sa méthode : créer des labyrinthes de Murs de Ronces autour des positions ennemies, en ajoutant des Parasitages qui épuisent progressivement les PM, jusqu'à ce que la cible soit incapable de résister à la capture. Il n'utilise jamais de méthodes létales si une alternative est disponible.",
    "Spinyx prépare le terrain avant l'action : Mur de Ronces en configuration labyrinthique autour de la zone d'opération. Parasitage sur les cases que ses cibles traversent — drain de PM progressif. Vrille pour immobiliser les cibles qui tentent de s'extraire. Spores pour ralentir et désorienner. Plante Carnivore en dernier recours pour les cibles qui résistent encore. Sorvane est sa cible principale depuis deux ans.",
    "Mur de Ronces de Spinyx peut être configuré en couloir dirigé (canal d'un seul passage). Parasitage se propage automatiquement aux cases adjacentes après 2 tours (effet viral). Vrille de Spinyx immobilise pendant 3 tours au lieu de 2. Passif Labyrinthe Épineux : ses Murs de Ronces sont impénétrables physiquement (aucun passage possible sauf via Pont de Lianes) et drainent 2 PM par tour à quiconque tente de les traverser."
))

write("src/data/characters/plante/123-thornax/index.ts", char_file(
    123, "Thornax", "Plante", "Juggernaut", "Sylvans", "Sylvera", "Convergence",
    "Sylvan d'une taille qui évoque un vieux chêne plus qu'un être humain — large, dense, avec une peau dont la texture est indiscernable de l'écorce épaisse par endroits. Des racines vivantes émergent de ses pieds quand il se stabilise et s'ancrent dans le sol, augmentant sa résistance aux déplacements forcés. Sa voix est profonde et lente comme la pousse des arbres. Ses bras ont la section d'une branche maîtresse.",
    "Thornax est patient avec la conviction de celui qui a vu des forêts pousser depuis des graines. La Convergence lui a fait sens parce qu'elle partage cette vision à long terme — la puissance des Élus doit être redistribuée comme la forêt redistribue ses ressources entre ses membres. Il est l'arbre qui donne de l'ombre pour que les autres poussent.",
    "Pilier de front de la Convergence à Sylvera, Thornax est ce qui ne recule pas. Les racines qu'il étend lui permettent de tenir des positions que des forces trois fois supérieures ne peuvent pas déloger. Sa Forêt Instantanée transforme des terrains dégagés en zones forestières qui favorisent tous les Élus Plante alliés. Sorvane le soutient, il tient la ligne.",
    "Thornax s'ancre dans sa position (racines déployées : immunisé aux déplacements forcés). Forêt Instantanée transforme la zone environnante en terrain Plante. Mur de Ronces sur les flancs. Plante Carnivore sur les accès principaux — quiconque approche entre dans sa zone de soin/dégâts. Régénération Naturelle dans les cases Plante le soigne en continu. Vrille sur les ennemis qui tentent de le contourner.",
    "Dans une case Plante, Thornax gagne +50% d'armure et ses dégâts infligent Régénération Naturelle à ses alliés adjacents (partage du soin). Mur de Ronces autour de Thornax se régénère de 20% de sa résistance par tour. Forêt Instantanée lancée par Thornax crée des cases Plante permanentes (non temporaires). Passif Racines Profondes : ses racines le lient à la case — impossible de le déplacer contre sa volonté tant qu'elles sont actives."
))

write("src/data/characters/plante/124-dryana/index.ts", char_file(
    124, "Dryana", "Plante", "Plongeur", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvane dont la particularité physique est la capacité de se fondre dans la végétation au point de ne plus se distinguer d'un arbre ou d'un buisson à quelques mètres. Ses membres sont longs et s'adaptent naturellement aux postures arboricoles. Sa peau change légèrement de teinte selon la végétation environnante — pas d'invisibilité totale, mais une dissonance visuelle significative. Elle se déplace dans les zones boisées avec la fluidité d'un animal sauvage.",
    "Dryana pense en termes de lignes de fuite plutôt que de fronts d'attaque. Sa plongée dans les lignes ennemies n'est jamais une charge — c'est une insertion via les failles végétales qu'elle crée elle-même. Les Dissidentes l'utilisent pour les missions où atteindre une position sans être vue est plus important que d'y arriver vite.",
    "Agent de terrain des Dissidentes à Sylvera spécialisée dans les insertions via les zones végétales. Ses Ponts de Lianes créent des voies d'accès que les capteurs de l'Empire ne détectent pas. Elle a exfiltré quatre Élus depuis des installations impériales en passant sous les murs grâce à des tunnels de Croissance.",
    "Dryana commence par créer un Pont de Lianes jusqu'à la position cible — un corridor végétal invisible aux capteurs standards. Camouflage sur sa propre position pendant l'approche. Vrille sur la cible pour l'immobiliser au contact. Spores pour désorienter. Plante Carnivore si elle doit tenir une position. Elle repart via le même Pont de Lianes avec la cible ou la mission accomplie.",
    "Pont de Lianes de Dryana peut traverser des murs et obstacles physiques (passage souterrain). Camouflage dure le double du temps normal et s'applique également aux alliés adjacents. Vrille lancée depuis Camouflage immobilise instantanément (sans délai). Passif Symbiose Forestière : dans une zone de végétation naturelle ou une case Plante, Dryana est indétectable par tous les moyens de détection non-magiques."
))

write("src/data/characters/plante/125-pollyn/index.ts", char_file(
    125, "Pollyn", "Plante", "Mage-Burst", "Sylvans", "Sylvera", "Indépendant",
    "Sylvan dont les émanations polliniques sont permanentes — une aura de particules végétales visibles dans les environnements lumineux qui le rend impossible à approcher discrètement (les particules réagissent à l'air déplacé). Sa peau est couverte de motifs rappelant des fleurs épanouies, qui s'intensifient avant une décharge massive de Spores. Ses yeux sont d'un vert-jaune de pollen. Il parle avec des métaphores botaniques que personne autour de lui ne comprend toujours.",
    "Pollyn est fasciné par le potentiel destructeur de la biologie végétale — pas par cruauté mais par émerveillement scientifique. Sa Jungle Primordiale n'est pas un ultime d'attaque pour lui, c'est un laboratoire de terrain grandeur nature. Il est indépendant parce qu'aucune faction ne peut tolérer quelqu'un qui déploie un écosystème complet pour tester une hypothèse.",
    "Botaniste et mercenaire de Sylvera dont les services sont achetés par qui lui offre le terrain d'expérimentation le plus intéressant. Sa Jungle Primordiale a transformé plusieurs zones de combat en forêts permanentes — effets secondaires non voulus de ses tests qui lui valent un statut ambigu dans plusieurs régions.",
    "Pollyn sème le terrain d'abord : Croissance et Parasitage sur les positions ennemies. Spores pour accumuler les effets de ralentissement et de désorientaton. Plante Carnivore en points clés. Quand le terrain est suffisamment envahi, Jungle Primordiale — tout devient forêt, toute la zone tombe sous les effets Plante massifs. Forêt Instantanée en préparation de la Jungle.",
    "Spores de Pollyn restent actives 3 tours supplémentaires et s'accumulent (chaque stack augmente l'effet). Jungle Primordiale de Pollyn crée une forêt permanente dans un rayon de 8 cases. Plante Carnivore peut cibler 3 cases simultanément. Passif Pollinisation Massive : ses sorts Plante ont 30% de chance de créer une case Plante supplémentaire adjacente à leur zone d'effet."
))

write("src/data/characters/plante/126-rootek/index.ts", char_file(
    126, "Rootek", "Plante", "Battlemage", "Sylvans", "Sylvera", "Empire",
    "Sylvan dont la maîtrise de la Plante s'est orientée vers le combat rapproché — des racines émergent de ses poings lors des frappes physiques, enserrant les cibles à l'impact. Sa peau est d'un vert-brun de sous-bois, avec des veines de sève visibles aux avant-bras qui pulsent rythmiquement. Il porte une armure d'écorce compressée sur le torse et les bras — flexible mais extrêmement résistante aux dégâts physiques et élémentaires non-Feu.",
    "Rootek sert l'Empire parce qu'il a vu ce que font les Élus Plante sans encadrement : des Jungles Primordiales accidentelles qui détruisent des villages entiers. Son propre Éveil a failli tuer ses proches. La structure impériale, selon lui, est le treillis que la plante a besoin pour grandir sans détruire.",
    "Officier de combat de l'Empire à Sylvera responsable de la neutralisation des Élus Plante rebelles. Sa technique combine le combat au contact avec des Parasitages qui épuisent progressivement les adversaires — ils se battent de moins en moins bien au fur et à mesure que leurs PM diminuent. Spinyx lui identifie les cibles, il les neutralise.",
    "Rootek entre en mêlée avec Parasitage préposé sur les cases qu'il anticipe d'occuper — ses adversaires perdent des PM à chaque case. Mur de Ronces pour fermer les flancs et concentrer l'ennemi devant lui. Vrille au contact pour immobiliser. Plante Carnivore sur sa propre position pour se soigner en combat. Spores pour maintenir la désorientation. Forêt Instantanée si dépassé numériquement.",
    "Parasitage de Rootek se propage via ses frappes physiques (contact déclenche Parasitage sur la cible). Vrille au contact est instantanée (pas de délai). Plante Carnivore active sur sa position le soigne de 8% PV par tour en continu. Passif Combat Symbiotique : dans une case Plante, toutes ses attaques physiques déclenchent Régénération Naturelle sur lui-même, soignant 5% des dégâts infligés."
))

write("src/data/characters/plante/127-sporen/index.ts", char_file(
    127, "Sporen", "Plante", "Artillerie", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvan dont les sacs polliniques sous la peau des joues et du cou — caractéristiques de certaines lignées sylvanes spécialisées — lui permettent de lancer des Spores à longue portée sans geste mécanique visible. Sa peau est d'un vert mousseux, uniforme, avec une texture légèrement poreuse. Il parle peu et observe beaucoup, évaluant en permanence les vecteurs de propagation optimaux. Ses yeux sont d'un jaune-vert de spore.",
    "Sporen pense en termes de propagation et de zones d'infection. Chaque cible touchée par ses Spores est un point de départ d'une contamination qui se propage selon des modèles qu'il a passé des années à cartographier. Sa patience est celle d'un naturaliste : il attend le bon moment de vent, le bon angle, la bonne configuration d'adversaires.",
    "Artilleur biologique des Dissidentes à Sylvera. Ses Spores créent des zones de désorientation persistante qui couvrent les opérations des agents de terrain comme Dryana. Sa Jungle Primordiale à longue portée a transformé plusieurs positions impériales avancées en zones végétales impraticables.",
    "Sporen maintient distance maximale, Camouflage sur sa position. Spores en séquence sur les positions ennemies denses — propagation progressive. Parasitage à longue portée sur les zones derrière les lignes ennemies. Forêt Instantanée à portée pour transformer les zones de combat en terrain favorable. Jungle Primordiale sur toute la zone quand la configuration est optimale.",
    "Spores de Sporen ont une portée de 9 cases (au lieu de 5) et se propagent automatiquement aux cases adjacentes. Forêt Instantanée peut être lancée à 9 cases. Parasitage à portée de 7 cases. Passif Propagation Systémique : ses Spores infectent automatiquement les cases adjacentes à la cible pendant 2 tours supplémentaires, créant une zone d'infection croissante."
))

write("src/data/characters/plante/128-seve-vive/index.ts", char_file(
    128, "Sylvex", "Plante", "Tireur", "Sylvans", "Sylvera", "Indépendant",
    "Sylvane dont les cheveux sont des tiges végétales vivantes qui s'étendent et se rétractent selon sa volonté, lui servant à la fois de capteurs directionnels et de projectiles végétaux. Sa peau est d'un vert clair printanier, presque luisante de sève en surface. Ses yeux sont d'un amber-vert végétal. Elle porte peu d'équipement — ses tiges lui servent d'outil universel, de lien, de bras supplémentaires, de projectiles selon le besoin.",
    "Sylvex est indépendante parce que ses compétences sont trop spécifiques pour n'importe quelle faction. Elle tire des Vrilles à longue portée avec une précision qui surprend — une Vrille n'est pas censée être un sort de précision, mais entre ses mains, c'est un filin de capture exact. Elle loue ses services comme spécialiste de la capture non-létale.",
    "Spécialiste de la capture à longue portée de Sylvera. Ses Vrilles et ses Ponts de Lianes lui permettent de maintenir des cibles à distance ou de créer des voies vers elles sans combat direct. Sa réputation dans les milieux des Dissidentes : fiable pour récupérer des cibles vivantes dans des situations où la force directe créerait des dommages collatéraux.",
    "Sylvex maintient sa distance, utilise Camouflage pour se dissimuler. Vrille à portée maximale pour immobiliser la cible. Pont de Lianes comme voie d'approche pour ses alliés sans elle-même bouger. Parasitage sur la cible immobilisée pour drainer ses PM. Plante Carnivore sur la case de la cible pour maintenir la pression. Spores si des renforts arrivent.",
    "Vrille de Sylvex a une portée de 9 cases et peut cibler 2 cibles adjacentes simultanément (double Vrille). Pont de Lianes peut être lancé depuis la position d'une Vrille active (extension de portée). Parasitage sur une cible Vrillée se propage automatiquement à 2 cases adjacentes. Passif Tir de Précision Végétal : ses Vrilles ne peuvent pas être déviées ou interceptées par des sorts de protection physique."
))

write("src/data/characters/plante/129-grimpant/index.ts", char_file(
    129, "Grymphe", "Plante", "Assassin", "Chthoniens", "Ormn-Dur", "Dissidentes",
    "Chthonien dont la maîtrise de la Plante est venue du contact avec les champignons bioluminescents des cavernes d'Ormn-Dur — sa peau porte des taches de bioluminescence verte-blanche qui s'activent dans l'obscurité totale. Sa façon de se déplacer emprunte aux champignons : il s'attache aux surfaces verticales via des filaments végétaux invisibles et peut se déplacer sur des murs ou des plafonds. Il n'y a pas de surface qui lui soit inaccessible dans une zone végétale ou humide.",
    "Grymphe a appris à considérer la tridimensionnalité du mouvement comme la première arme. Ses adversaires pensent en termes de sol et de lignes de vue horizontales ; lui arrive depuis le plafond ou depuis une paroi verticale. Dans les zones végétales, il est indétectable. Dans les zones minérales d'Ormn-Dur, il est simplement discret.",
    "Assassin des Dissidentes opérant entre Ormn-Dur et Sylvera, spécialisé dans les cibles qui se pensent protégées par la verticalité de leurs positions défensives. Ses Ponts de Lianes lui permettent d'atteindre des cibles sur des plateformes élevées que d'autres agents ne peuvent pas rejoindre. Dryana lui fournit les données de terrain depuis les zones végétales.",
    "Grymphe approche via des surfaces verticales (murs, arbres, plafonds dans les cavernes). Pont de Lianes vers la position cible depuis une hauteur. Camouflage pendant l'approche. Vrille au contact pour immobiliser. Spores pour désorienter avant la frappe principale. Plante Carnivore sur la case de la cible comme outil de maintien. Il repart par la même voie verticale.",
    "Grymphe se déplace sur surfaces verticales sans coût PM supplémentaire. Pont de Lianes peut être créé verticalement (accès aux hauteurs et profondeurs). Vrille lancée depuis une position élevée vers une cible en contrebas est automatiquement un immobilisateur (sans résistance possible). Passif Grimpeur Silencieux : ses déplacements sur surfaces verticales ne génèrent aucune alerte, même à proximité directe d'ennemis."
))

write("src/data/characters/plante/130-lianen/index.ts", char_file(
    130, "Lianen", "Plante", "Escrimeur", "Sylvans", "Sylvera", "Empire",
    "Sylvan dont les lianes constituent une partie intégrante de son combat — non pas comme sorts mais comme extensions physiques permanentes de ses bras. Ces lianes vivantes sont enroulées autour de ses avant-bras au repos et se déroulent en combat pour atteindre, saisir ou frapper à des distances supérieures à ses bras normaux. Sa peau est d'un vert sombre de forêt profonde. Ses yeux sont d'un vert intense, presque agressif.",
    "Lianen est pragmatique dans sa loyauté impériale — l'Empire lui fournit les mandats qui lui permettent d'utiliser ses lianes-armes sans restrictions légales. Il n'est pas idéologique. Ce qui l'intéresse, c'est la maîtrise technique de son combat, et l'Empire lui donne les adversaires qui développent cette maîtrise.",
    "Duelliste de l'Empire à Sylvera, responsable de la neutralisation d'agents des Dissidentes dans des confrontations directes. Ses lianes-armes lui donnent une portée de corps à corps étendue qui surprend des adversaires habituels aux distances standards de duel.",
    "Lianen engage en corps à corps étendu — ses lianes atteignent des cibles à 3 cases. Vrille intégrée dans ses lianes immobilise au contact. Mur de Ronces pour fermer les routes de fuite de sa cible dans le duel. Parasitage sur la case de duel pour drainer les PM progressivement. Plante Carnivore sur sa propre position pour se soigner. Spores si multiple adversaires.",
    "Vrille de Lianen peut être utilisée comme attaque de corps à corps à portée 3 (lianes). Mur de Ronces créé en cercle autour d'une cible (cage végétale). Dans une case Plante, sa portée de mêlée s'étend à 4 cases. Passif Extension Végétale : ses lianes s'allongent de 1 case par case Plante existante dans un rayon de 4 — en forêt dense, sa portée de mêlée peut atteindre 6 cases."
))

write("src/data/characters/plante/131-barriere-verte/index.ts", char_file(
    131, "Virold", "Plante", "Vanguard", "Sylvans", "Sylvera", "Convergence",
    "Sylvan d'une hauteur qui rappelle les arbres de Sylvera plutôt que ses habitants — presque deux mètres, avec une présence qui rend les forêts denses plus étroites. Sa peau est d'un vert-brun de forêt vieille, avec des motifs d'écorce sur les épaules et les bras. Des bourgeons de végétation poussent et tombent sur ses vêtements en permanence — il est en croissance constante. Sa voix porte dans les bois comme si elle venait de plusieurs directions à la fois.",
    "Virold incarne la conviction de la Convergence appliquée à la Plante : la forêt appartient à tous ses membres — les arbres partagent leurs ressources via les réseaux mycorhiziens. Les Élus devraient faire de même. Il initie les avancées de la Convergence à Sylvera avec la patience d'un jardinier plutôt que d'un guerrier.",
    "Avant-garde de la Convergence dans les zones forestières de Sylvera où des communautés d'Élus Plante tentent de maintenir leur indépendance. Son Forêt Instantanée d'initiation transforme des zones dégagées en terrain qui favorise ses alliés. Thornax le suit pour tenir ce qu'il a transformé.",
    "Virold initie avec Forêt Instantanée sur la zone d'opération — transformation immédiate en terrain Plante favorable. Mur de Ronces sur les flancs de l'avancée. Pont de Lianes pour que ses alliés traversent rapidement. Jungle Primordiale pour l'initiation maximale quand les conditions sont réunies. Croissance continue pour maintenir la régénération de ses alliés dans la forêt créée.",
    "Forêt Instantanée de Virold couvre une zone 7×7 (au lieu de 5×5). Il n'a aucun malus de déplacement dans les zones végétales (y compris Mur de Ronces et Forêt dense). Jungle Primordiale lancée depuis une Forêt Instantanée existante double son effet. Passif Avant-Garde Forestière : chaque case qu'il traverse se transforme en case Plante pendant 3 tours, créant une traînée de terrain favorable."
))

write("src/data/characters/plante/132-foret-vivante/index.ts", char_file(
    132, "Dendrix", "Plante", "Gardien", "Sylvans", "Sylvera", "Dissidentes",
    "Sylvane dont la peau est incrustée de mousses vivantes, de lichens et de petits champignons qui lui ont valu son surnom dans certains cercles — elle ressemble à un arbre qui a appris à marcher. Ces organismes symbiotiques lui fournissent une armure naturelle régénérative et une perception étendue du territoire végétal environnant via les réseaux mycorhiziens. Ses cheveux sont entièrement composés de végétaux différents — elle ne coupe jamais car couper serait blesser.",
    "Dendrix protège comme une forêt protège — non pas de façon spectaculaire, mais par une présence constante et pervasive. Elle n'est jamais absente ; elle étend simplement sa zone de protection selon les besoins. Sa loyauté aux Dissidentes est fondamentale : ils protègent la forêt elle-même autant que les Élus qui y vivent.",
    "Gardienne des refuges forestiers des Dissidentes à Sylvera — les zones de végétation dense où les Élus fugitifs se cachent. Ses réseaux mycorhiziens lui permettent de surveiller un rayon de plusieurs kilomètres depuis une position fixe. Elle alerte quand des agents impériaux approchent avant qu'ils ne soient à portée de détection standard.",
    "Dendrix crée des Forêts Instantanées défensives autour des positions à protéger. Mur de Ronces en architecture concentriques. Plante Carnivore sur les points d'entrée. Régénération Naturelle sur tous ses protégés. Parasitage sur les approches ennemies. Camouflage sur les Élus non-combattants qui ont besoin de discrétion. Elle ne bouge pas — elle étend.",
    "Forêt Instantanée de Dendrix est permanente dans les zones où elle est plantée (ne disparaît pas). Mur de Ronces soigne les alliés adjacents de 6% PV par tour. Plante Carnivore de Dendrix soigne 12% PV (au lieu de standard) et peut cibler une zone 2×2. Passif Réseau Mycorhizien : elle perçoit toute activité dans un rayon de 8 cases via les réseaux végétaux — aucune surprise n'est possible dans son domaine."
))

write("src/data/characters/plante/133-l-entrelace/index.ts", char_file(
    133, "L'Entrelacé", "Plante", "Spécialiste", "Sylvans", "Sylvera", "Indépendant",
    "Sylvan dont la frontière entre son corps et la végétation environnante est devenue imperceptible. Des racines et des lianes émergent de son dos, de ses bras, parfois de son visage, et se connectent aux plantes environnantes de façon permanente. Quand il reste immobile dans une forêt, il devient indistinguable d'un arbre ordinaire. Ses yeux sont d'un vert presque bioluminescent dans l'obscurité, seule partie de lui qui ne peut pas se camoufler.",
    "L'Entrelacé a cessé de se penser comme un individu il y a longtemps. Il est un nœud dans un réseau plus vaste, une conscience localisée dans le système végétal de Sylvera. Cette perspective lui donne une sérénité que ses alliés trouvent parfois troublante : il ne s'inquiète jamais, parce que même sa mort serait une transformation plutôt qu'une fin.",
    "Phénomène unique de Sylvera dont les chroniques sylvanes attestent l'existence depuis deux cents ans — peut-être le même être, peut-être la même conscience transmise. Les archives de toutes les factions mentionnent L'Entrelacé dans des contextes impossibles si c'était un être ordinaire. L'Empire a cessé de le catalogiser après trois tentatives infructueuses.",
    "L'Entrelacé opère depuis la totalité du réseau végétal de Sylvera. Ses Vrilles, Plante Carnivore et Parasitage s'activent depuis n'importe quelle case végétale sur la carte. Jungle Primordiale permanente dans toute zone où il a déjà opéré. Il ne combat pas directement — la forêt combat pour lui.",
    "Peut lancer tous ses sorts depuis n'importe quelle case Plante sur la carte (réseau végétal comme corps étendu). Jungle Primordiale est permanente dans les zones où il l'a activée. Parasitage et Plante Carnivore s'activent automatiquement dans un rayon de 5 cases autour de n'importe quelle case Plante. Passif Symbiose Totale : sa mort ne le supprime pas — sa conscience migre dans le réseau végétal le plus proche pour réémerger au tour suivant (une fois par combat)."
))

print("Plante: 13 characters written")
print("\nAll done! Written: Glace (13), Electrique (12+1), Plante (13)")
